/**
 * Generated from archetype_logic/badge images/icon_prompts.json.
 * Do not edit by hand. Run: node scripts/generateArchetypeBadgeMap.mjs
 *
 * Canonical art: badges/composed/*.png (build_badges.py). npm run dev/build runs sync:badges → public/badges for Vite.
 */

export const ARCHETYPE_BADGE_PUBLIC_DIR = '/badges';

export const ARCHETYPE_BADGE_FILENAME_BY_NAME: Record<string, string> = {
  "The Captain": "001_the_captain.png",
  "The Opportunist": "002_the_opportunist.png",
  "The Value GM": "003_the_value_gm.png",
  "The Calculated Risk": "004_the_calculated_risk.png",
  "The Cold Calculation": "289_the_cold_calculation.png",
  "The Free Agent": "005_the_free_agent.png",
  "The Computer": "006_the_computer.png",
  "The Scout Team": "007_the_scout_team.png",
  "The Opportunist's Gambit": "008_the_opportunists_gambit.png",
  "The Evaluator": "009_the_evaluator.png",
  "The Disciplined": "010_the_disciplined.png",
  "The Pure Play": "011_the_pure_play.png",
  "The Robot": "012_the_robot.png",
  "The Automaton": "290_the_automaton.png",
  "The Stabilizer": "013_the_stabilizer.png",
  "The Ballast": "014_the_ballast.png",
  "The Sleeper": "015_the_sleeper.png",
  "The Formula": "016_the_formula.png",
  "The Proof": "291_the_proof.png",
  "The Scout": "017_the_scout.png",
  "The Talent Evaluator": "073_the_talent_evaluator.png",
  "The Value Hunter": "018_the_value_hunter.png",
  "The Prospector": "217_the_prospector.png",
  "The Analyst": "019_the_analyst.png",
  "The Examiner": "074_the_examiner.png",
  "The Steady Hand": "020_the_steady_hand.png",
  "The Ironhand": "075_the_ironhand.png",
  "The Market Timer": "021_the_market_timer.png",
  "The Window Spotter": "076_the_window_spotter.png",
  "The Accountant": "022_the_accountant.png",
  "The Ledger": "292_the_ledger.png",
  "The Even Keel": "023_the_even_keel.png",
  "The Sleeper Agent": "024_the_sleeper_agent.png",
  "The Neutral": "025_the_neutral.png",
  "The Indexer": "026_the_indexer.png",
  "The Pivot": "027_the_pivot.png",
  "The Redirect": "028_the_redirect.png",
  "The Spreadsheet Classic": "029_the_spreadsheet_classic.png",
  "The Safe Harbor": "030_the_safe_harbor.png",
  "The Chaos Agent": "031_the_chaos_agent.png",
  "The Actuarial": "032_the_actuarial.png",
  "The Underwriter": "218_the_underwriter.png",
  "The Minimalist": "033_the_minimalist.png",
  "The Spartan Draft": "293_the_spartan_draft.png",
  "The Pure Opportunist": "034_the_pure_opportunist.png",
  "The Algorithm": "035_the_algorithm.png",
  "The Cipher": "294_the_cipher.png",
  "The Monk": "036_the_monk.png",
  "The Ascetic": "219_the_ascetic.png",
  "The Iconoclast": "037_the_iconoclast.png",
  "The Heretic": "220_the_heretic.png",
  "The Spartan Analyst": "038_the_spartan_analyst.png",
  "The Commander in Chief": "039_the_commander_in_chief.png",
  "The Dispatch": "077_the_dispatch.png",
  "The Field General": "040_the_field_general.png",
  "The Commanding Officer": "078_the_commanding_officer.png",
  "The Strategist": "041_the_strategist.png",
  "The Planner": "079_the_planner.png",
  "The Even Hand": "042_the_even_hand.png",
  "The Opportunist's Mirror": "043_the_opportunists_mirror.png",
  "The Systems Thinker": "044_the_systems_thinker.png",
  "The Deliberate": "045_the_deliberate.png",
  "The Open Field": "046_the_open_field.png",
  "The Draft Engine": "047_the_draft_engine.png",
  "The Quiet Storm": "048_the_quiet_storm.png",
  "The Grinding Stone": "221_the_grinding_stone.png",
  "The Maverick's Twin": "049_the_mavericks_twin.png",
  "The Logician": "050_the_logician.png",
  "The Rationalist": "295_the_rationalist.png",
  "The Pragmatist": "051_the_pragmatist.png",
  "The Measured": "296_the_measured.png",
  "The Free Thinker": "052_the_free_thinker.png",
  "The Cold Eye": "053_the_cold_eye.png",
  "The Dispassionate": "297_the_dispassionate.png",
  "The Disciplined Pro": "054_the_disciplined_pro.png",
  "The Stoic": "055_the_stoic.png",
  "The Unflinching": "298_the_unflinching.png",
  "The Pure BPA": "056_the_pure_bpa.png",
  "The Long Game": "057_the_long_game.png",
  "The Marathon": "299_the_marathon.png",
  "The Contrarian's Cousin": "058_the_contrarians_cousin.png",
  "The Underdog": "059_the_underdog.png",
  "The Arbitrage": "060_the_arbitrage.png",
  "The Workhorse's Cousin": "061_the_workhorses_cousin.png",
  "The Dark Horse": "062_the_dark_horse.png",
  "The Longshot Contender": "222_the_longshot_contender.png",
  "The Smart Money": "063_the_smart_money.png",
  "The Informed Edge": "223_the_informed_edge.png",
  "The Steady Maverick": "064_the_steady_maverick.png",
  "The Maverick": "065_the_maverick.png",
  "The Outlier": "080_the_outlier.png",
  "The Data Driven": "066_the_data_driven.png",
  "The Controlled Burn": "067_the_controlled_burn.png",
  "The Wildcard": "068_the_wildcard.png",
  "The Quant": "069_the_quant.png",
  "The Modeler": "300_the_modeler.png",
  "The Minimalist Pro": "070_the_minimalist_pro.png",
  "The Free Spirit": "071_the_free_spirit.png",
  "The Pure Value": "072_the_pure_value.png",
  "The Empire": "081_the_empire.png",
  "The Franchise": "082_the_franchise.png",
  "The Dynasty": "083_the_dynasty.png",
  "The Ironclad Plan": "084_the_ironclad_plan.png",
  "The Power Broker": "085_the_power_broker.png",
  "The Freight Train": "224_the_freight_train.png",
  "The Executive Suite": "086_the_executive_suite.png",
  "The General": "087_the_general.png",
  "The Bold Franchise": "088_the_bold_franchise.png",
  "The War Room": "089_the_war_room.png",
  "The Stronghold": "090_the_stronghold.png",
  "The Librarian": "091_the_librarian.png",
  "The Veteran": "092_the_veteran.png",
  "The Upside Seeker": "093_the_upside_seeker.png",
  "The Bold": "094_the_bold.png",
  "The Methodical": "095_the_methodical.png",
  "The TE Hoarder": "096_the_te_hoarder.png",
  "The Hero": "097_the_hero.png",
  "The Stack Master": "098_the_stack_master.png",
  "The Bulwark": "099_the_bulwark.png",
  "The Complete Package": "100_the_complete_package.png",
  "The Fundamentalist": "101_the_fundamentalist.png",
  "The Conservative": "102_the_conservative.png",
  "The Cautious": "301_the_cautious.png",
  "The Air Raid Classic": "103_the_air_raid_classic.png",
  "The Air Raid Zero": "302_the_air_raid_zero.png",
  "The Reliable": "104_the_reliable.png",
  "The Wildcatter": "105_the_wildcatter.png",
  "The Systematic": "106_the_systematic.png",
  "The Enduring": "107_the_enduring.png",
  "The Gambit": "108_the_gambit.png",
  "The Methodist": "109_the_methodist.png",
  "The Blue Collar": "110_the_blue_collar.png",
  "The Lone Wolf": "111_the_lone_wolf.png",
  "The Spartan General": "112_the_spartan_general.png",
  "The Sure Thing": "113_the_sure_thing.png",
  "The Certainty": "225_the_certainty.png",
  "The Luxury Tax": "114_the_luxury_tax.png",
  "The Balance Sheet": "115_the_balance_sheet.png",
  "The Blueprint": "116_the_blueprint.png",
  "The Schematic": "303_the_schematic.png",
  "The Signal Caller": "117_the_signal_caller.png",
  "The Franchise QB": "118_the_franchise_qb.png",
  "The Immovable Object": "119_the_immovable_object.png",
  "The Cornerstone": "120_the_cornerstone.png",
  "The Load Bearing": "226_the_load_bearing.png",
  "The Value Engineer": "121_the_value_engineer.png",
  "The Reliable Duo": "122_the_reliable_duo.png",
  "The Twin Pillars": "227_the_twin_pillars.png",
  "The Late Bloomer": "123_the_late_bloomer.png",
  "The Second Wind": "228_the_second_wind.png",
  "The Hard Hat": "124_the_hard_hat.png",
  "The Steel Toed": "229_the_steel_toed.png",
  "The Bet Hedger": "125_the_bet_hedger.png",
  "The Mileage": "126_the_mileage.png",
  "The Fortress Wall": "127_the_fortress_wall.png",
  "The Thunder": "128_the_thunder.png",
  "The Return on Investment": "129_the_return_on_investment.png",
  "The Old School": "130_the_old_school.png",
  "The Backfield Boss": "131_the_backfield_boss.png",
  "The Classicist": "132_the_classicist.png",
  "The Traditionalist": "133_the_traditionalist.png",
  "The Ground & Pound": "134_the_ground_and_pound.png",
  "The Arbitrageur": "135_the_arbitrageur.png",
  "The Iron Curtain": "136_the_iron_curtain.png",
  "The Brute Force": "137_the_brute_force.png",
  "The Sledgehammer": "138_the_sledgehammer.png",
  "The Workhorse": "139_the_workhorse.png",
  "The Ground Game": "140_the_ground_game.png",
  "The Run First": "141_the_run_first.png",
  "The Bruiser": "142_the_bruiser.png",
  "The Battering Ram": "230_the_battering_ram.png",
  "The Lone Ranger": "143_the_lone_ranger.png",
  "The Run Committee": "144_the_run_committee.png",
  "The Blue Chip": "231_the_blue_chip.png",
  "The Big Four": "232_the_big_four.png",
  "The Asset Manager": "233_the_asset_manager.png",
  "The Grand Slam": "234_the_grand_slam.png",
  "The Big Three": "235_the_big_three.png",
  "The GM": "236_the_gm.png",
  "The Power Play": "237_the_power_play.png",
  "The Triple Header": "238_the_triple_header.png",
  "The Brass Tacks": "239_the_brass_tacks.png",
  "The Long Shot": "240_the_long_shot.png",
  "The Underdog Play": "241_the_underdog_play.png",
  "The Reliable Roster": "242_the_reliable_roster.png",
  "The Late Surge": "243_the_late_surge.png",
  "The Loaded Roster": "244_the_loaded_roster.png",
  "The Complete Roster": "245_the_complete_roster.png",
  "The Balanced Attack": "246_the_balanced_attack.png",
  "The Dual Threat": "247_the_dual_threat.png",
  "The Diversified": "248_the_diversified.png",
  "The Coalition": "249_the_coalition.png",
  "The Alliance": "304_the_alliance.png",
  "The Contrarian": "250_the_contrarian.png",
  "The Dissenter": "305_the_dissenter.png",
  "The Diversified Portfolio": "251_the_diversified_portfolio.png",
  "The Chaos Theory": "252_the_chaos_theory.png",
  "The Spartan": "253_the_spartan.png",
  "The Stripped Down": "306_the_stripped_down.png",
  "The Iron Will": "254_the_iron_will.png",
  "The Maverick's Mirror": "255_the_mavericks_mirror.png",
  "The Stoic's Formula": "256_the_stoics_formula.png",
  "The Power Formation": "257_the_power_formation.png",
  "The Triple Crown": "258_the_triple_crown.png",
  "The War Room General": "259_the_war_room_general.png",
  "The Triple Threat": "260_the_triple_threat.png",
  "The Draft Board": "261_the_draft_board.png",
  "The Formation": "262_the_formation.png",
  "The Gambler's Gambit": "263_the_gamblers_gambit.png",
  "The Draft Room": "264_the_draft_room.png",
  "The Trenches": "265_the_trenches.png",
  "The Return on Rushes": "266_the_return_on_rushes.png",
  "The Lottery Ticket": "267_the_lottery_ticket.png",
  "The Value Play": "268_the_value_play.png",
  "The Workhorse Classic": "269_the_workhorse_classic.png",
  "The Hammer Drop": "270_the_hammer_drop.png",
  "The Mileage Counter": "271_the_mileage_counter.png",
  "The Portfolio": "272_the_portfolio.png",
  "The Full House": "273_the_full_house.png",
  "The Machine": "274_the_machine.png",
  "The Trench Worker": "275_the_trench_worker.png",
  "The Gridiron": "276_the_gridiron.png",
  "The Meat and Potatoes": "277_the_meat_and_potatoes.png",
  "The Powerhouse": "278_the_powerhouse.png",
  "The Hammer": "279_the_hammer.png",
  "The Strongman": "280_the_strongman.png",
  "The Behemoth": "281_the_behemoth.png",
  "The Tank": "282_the_tank.png",
  "The Juggernaut": "283_the_juggernaut.png",
  "The Steel Curtain": "284_the_steel_curtain.png",
  "The Bulldozer": "285_the_bulldozer.png",
  "The No-QB Club": "286_the_no_qb_club.png",
  "The Gunslinger's Nemesis": "287_the_gunslingers_nemesis.png",
  "The Old Faithful": "288_the_old_faithful.png",
  "The Lock In": "145_the_lock_in.png",
  "The Two Premium": "146_the_two_premium.png",
  "The Premium Purist": "147_the_premium_purist.png",
  "The Methodical Premium": "148_the_methodical_premium.png",
  "The Early Adopter": "149_the_early_adopter.png",
  "The Structured Gamble": "150_the_structured_gamble.png",
  "The Signal First": "151_the_signal_first.png",
  "The Bold Departure": "152_the_bold_departure.png",
  "The QB Truther": "153_the_qb_truther.png",
  "The Locked In": "154_the_locked_in.png",
  "The Last Resort Premium": "155_the_last_resort_premium.png",
  "The Late Value": "156_the_late_value.png",
  "The Deep Value": "157_the_deep_value.png",
  "The Longshot": "158_the_longshot.png",
  "The Waiver Wire Maestro": "159_the_waiver_wire_maestro.png",
  "The Steady Builder": "160_the_steady_builder.png",
  "The Hail Mary Classic": "161_the_hail_mary_classic.png",
  "The Process Builder": "162_the_process_builder.png",
  "The Safe Inversion": "163_the_safe_inversion.png",
  "The Inverted Draft": "164_the_inverted_draft.png",
  "The Value Inversion": "165_the_value_inversion.png",
  "The Patient Investor": "166_the_patient_investor.png",
  "The Late Bloomer Special": "167_the_late_bloomer_special.png",
  "The Efficiency Play": "168_the_efficiency_play.png",
  "The Deep Sleeper": "169_the_deep_sleeper.png",
  "The Waiver King": "170_the_waiver_king.png",
  "The Wire to Wire": "171_the_wire_to_wire.png",
  "The Safe Chaos": "172_the_safe_chaos.png",
  "The Chaos Premium": "173_the_chaos_premium.png",
  "The Value Chaos": "174_the_value_chaos.png",
  "The Survivalist": "175_the_survivalist.png",
  "The Dumpster Fire Chic": "176_the_dumpster_fire_chic.png",
  "The Spartan Builder": "177_the_spartan_builder.png",
  "The Minimalist Extreme": "178_the_minimalist_extreme.png",
  "The Total Chaos": "179_the_total_chaos.png",
  "The Pure Contrarian": "180_the_pure_contrarian.png",
  "The Premium Build": "181_the_premium_build.png",
  "The Kelce-Allen Special": "182_the_kelce_allen_special.png",
  "The Non-Conformist": "183_the_non_conformist.png",
  "The Unorthodox": "184_the_unorthodox.png",
  "The Upside Down": "185_the_upside_down.png",
  "The Contrarian Formula": "186_the_contrarian_formula.png",
  "The Steady Signal": "187_the_steady_signal.png",
  "The Air Strike": "188_the_air_strike.png",
  "The Quarterback First": "189_the_quarterback_first.png",
  "The Safe Premium": "190_the_safe_premium.png",
  "The Premium TE Play": "191_the_premium_te_play.png",
  "The TE Premium Value": "192_the_te_premium_value.png",
  "The Patient": "193_the_patient.png",
  "The Gambler's Process": "194_the_gamblers_process.png",
  "The Efficiency Expert": "195_the_efficiency_expert.png",
  "The Patient Builder": "196_the_patient_builder.png",
  "The Late Skill Surge": "197_the_late_skill_surge.png",
  "The Optimizer's Path": "198_the_optimizers_path.png",
  "The Cautious Premium": "199_the_cautious_premium.png",
  "The TE Believer": "200_the_te_believer.png",
  "The Balanced Premium": "201_the_balanced_premium.png",
  "The Patient Drafter": "202_the_patient_drafter.png",
  "The Slow Burn": "203_the_slow_burn.png",
  "The Contrarian BPA": "204_the_contrarian_bpa.png",
  "The Deliberate Builder": "205_the_deliberate_builder.png",
  "The Delayed Attack": "206_the_delayed_attack.png",
  "The Process": "207_the_process.png",
  "The TE Anchor": "208_the_te_anchor.png",
  "The TE Truther": "209_the_te_truther.png",
  "The TE Value Hunter": "210_the_te_value_hunter.png",
  "The Grinder's Path": "211_the_grinders_path.png",
  "The Hail Mary": "212_the_hail_mary.png",
  "The Uncommon Value": "213_the_uncommon_value.png",
  "The Minimalist Builder": "214_the_minimalist_builder.png",
  "The Chaos Builder": "215_the_chaos_builder.png",
  "The Robot Builder": "216_the_robot_builder.png",
  "The Fortress": "307_the_fortress.png",
  "The Two Towers": "308_the_two_towers.png",
  "The Dual Anchor": "309_the_dual_anchor.png",
  "The Star Collector": "310_the_star_collector.png",
  "The Synergist": "311_the_synergist.png",
  "The Ironclad": "312_the_ironclad.png",
  "The Big Play": "313_the_big_play.png",
  "The Executive": "314_the_executive.png",
  "The Rock": "315_the_rock.png",
  "The High Roller": "316_the_high_roller.png",
  "The Purist": "317_the_purist.png",
  "The Steady Anchor": "318_the_steady_anchor.png",
  "The Boom or Bust": "319_the_boom_or_bust.png",
  "The Daredevil": "320_the_daredevil.png",
  "The Troika": "321_the_troika.png",
  "The Professor": "322_the_professor.png",
  "The Pairing": "323_the_pairing.png",
  "The Dynamic Duo": "324_the_dynamic_duo.png",
  "The Veteran Move": "325_the_veteran_move.png",
  "The Showstopper": "326_the_showstopper.png",
  "The Anchor": "327_the_anchor.png",
  "The All-In": "328_the_all_in.png",
  "The Pragmatic Renegade": "329_the_pragmatic_renegade.png",
  "The Renegade": "330_the_renegade.png",
  "The Moonshot": "331_the_moonshot.png",
  "The Logician's Ghost": "332_the_logicians_ghost.png",
  "The Franchise Builder": "333_the_franchise_builder.png",
  "The Architect": "334_the_architect.png",
  "The Commander": "335_the_commander.png",
  "The Gambler": "336_the_gambler.png",
  "The Tactician": "337_the_tactician.png",
  "The Signal Corps": "338_the_signal_corps.png",
  "The Air Raid": "339_the_air_raid.png",
  "The Field Marshal": "340_the_field_marshal.png",
  "The Pillar": "341_the_pillar.png",
  "The Premium Collector": "342_the_premium_collector.png",
  "The Route Runner": "343_the_route_runner.png",
  "The Wide Open": "344_the_wide_open.png",
  "The Value Seeker": "345_the_value_seeker.png",
  "The Grinder": "346_the_grinder.png",
  "The Boom Factory": "347_the_boom_factory.png",
  "The Realist": "348_the_realist.png",
  "The Foundation": "349_the_foundation.png",
  "The Double Down": "350_the_double_down.png",
  "The Optimizer": "351_the_optimizer.png",
  "The Safe Bet": "352_the_safe_bet.png",
  "The Streaker": "353_the_streaker.png",
  "The Efficient Market": "354_the_efficient_market.png",
  "The Steady Receiver": "355_the_steady_receiver.png",
  "The Spreadsheet": "356_the_spreadsheet.png",
  "The Bedrock": "357_the_bedrock.png",
  "The Swing Trader": "358_the_swing_trader.png",
  "The Anarchist": "359_the_anarchist.png",
  "The Pure Chaos": "360_the_pure_chaos.png",
  "The Special Teams Stan": "361_the_special_teams_stan.png",
  "The Kicker Truther": "362_the_kicker_truther.png",
  "The Double Dipper": "363_the_double_dipper.png",
  "The DST Hoarder": "364_the_dst_hoarder.png",
  "The Ostrich": "365_the_ostrich.png",
  "The Opening Kickoff": "366_the_opening_kickoff.png",
  "The Special Teams First Ballot": "367_the_special_teams_first_ballot.png",
  "The Homer": "368_the_homer.png",
  "The One Trick Pony": "369_the_one_trick_pony.png",
  "The Hometown Hero": "370_the_hometown_hero.png",
  "The Time Traveler": "371_the_time_traveler.png",
  "The Fantasy Hipster": "372_the_fantasy_hipster.png",
  "The Anti-ADP": "373_the_anti_adp.png",
  "The Injury Magnet": "374_the_injury_magnet.png",
  "The Rookie Truther": "375_the_rookie_truther.png",
  "The Old Boys Club": "376_the_old_boys_club.png",
  "The RB Apocalypse": "377_the_rb_apocalypse.png",
  "The Air Show": "378_the_air_show.png",
  "The Quarterback Factory": "379_the_quarterback_factory.png",
  "The TE Convention": "380_the_te_convention.png",
  "The Zero Position": "381_the_zero_position.png",
  "The Panic Button": "382_the_panic_button.png",
  "The YOLO": "383_the_yolo.png",
  "The Handcuff Army": "384_the_handcuff_army.png",
  "The Lottery Ticket Booth": "385_the_lottery_ticket_booth.png",
  "The Fantasy Sommelier": "386_the_fantasy_sommelier.png",
  "The Alphabetical": "387_the_alphabetical.png",
  "The Retirement Watch": "388_the_retirement_watch.png",
  "The Dynasty Dropout": "389_the_dynasty_dropout.png"
};

/** Master archetype # from icon_prompts (standard 1–360, chaos 361+). Used to sort Badges grid. Improviser has no entry. */
export const BADGE_MASTER_SORT_ID_BY_NAME: Record<string, number> = {
  "The Captain": 1,
  "The Opportunist": 2,
  "The Value GM": 3,
  "The Calculated Risk": 4,
  "The Cold Calculation": 289,
  "The Free Agent": 5,
  "The Computer": 6,
  "The Scout Team": 7,
  "The Opportunist's Gambit": 8,
  "The Evaluator": 9,
  "The Disciplined": 10,
  "The Pure Play": 11,
  "The Robot": 12,
  "The Automaton": 290,
  "The Stabilizer": 13,
  "The Ballast": 14,
  "The Sleeper": 15,
  "The Formula": 16,
  "The Proof": 291,
  "The Scout": 17,
  "The Talent Evaluator": 73,
  "The Value Hunter": 18,
  "The Prospector": 217,
  "The Analyst": 19,
  "The Examiner": 74,
  "The Steady Hand": 20,
  "The Ironhand": 75,
  "The Market Timer": 21,
  "The Window Spotter": 76,
  "The Accountant": 22,
  "The Ledger": 292,
  "The Even Keel": 23,
  "The Sleeper Agent": 24,
  "The Neutral": 25,
  "The Indexer": 26,
  "The Pivot": 27,
  "The Redirect": 28,
  "The Spreadsheet Classic": 29,
  "The Safe Harbor": 30,
  "The Chaos Agent": 31,
  "The Actuarial": 32,
  "The Underwriter": 218,
  "The Minimalist": 33,
  "The Spartan Draft": 293,
  "The Pure Opportunist": 34,
  "The Algorithm": 35,
  "The Cipher": 294,
  "The Monk": 36,
  "The Ascetic": 219,
  "The Iconoclast": 37,
  "The Heretic": 220,
  "The Spartan Analyst": 38,
  "The Commander in Chief": 39,
  "The Dispatch": 77,
  "The Field General": 40,
  "The Commanding Officer": 78,
  "The Strategist": 41,
  "The Planner": 79,
  "The Even Hand": 42,
  "The Opportunist's Mirror": 43,
  "The Systems Thinker": 44,
  "The Deliberate": 45,
  "The Open Field": 46,
  "The Draft Engine": 47,
  "The Quiet Storm": 48,
  "The Grinding Stone": 221,
  "The Maverick's Twin": 49,
  "The Logician": 50,
  "The Rationalist": 295,
  "The Pragmatist": 51,
  "The Measured": 296,
  "The Free Thinker": 52,
  "The Cold Eye": 53,
  "The Dispassionate": 297,
  "The Disciplined Pro": 54,
  "The Stoic": 55,
  "The Unflinching": 298,
  "The Pure BPA": 56,
  "The Long Game": 57,
  "The Marathon": 299,
  "The Contrarian's Cousin": 58,
  "The Underdog": 59,
  "The Arbitrage": 60,
  "The Workhorse's Cousin": 61,
  "The Dark Horse": 62,
  "The Longshot Contender": 222,
  "The Smart Money": 63,
  "The Informed Edge": 223,
  "The Steady Maverick": 64,
  "The Maverick": 65,
  "The Outlier": 80,
  "The Data Driven": 66,
  "The Controlled Burn": 67,
  "The Wildcard": 68,
  "The Quant": 69,
  "The Modeler": 300,
  "The Minimalist Pro": 70,
  "The Free Spirit": 71,
  "The Pure Value": 72,
  "The Empire": 81,
  "The Franchise": 82,
  "The Dynasty": 83,
  "The Ironclad Plan": 84,
  "The Power Broker": 85,
  "The Freight Train": 224,
  "The Executive Suite": 86,
  "The General": 87,
  "The Bold Franchise": 88,
  "The War Room": 89,
  "The Stronghold": 90,
  "The Librarian": 91,
  "The Veteran": 92,
  "The Upside Seeker": 93,
  "The Bold": 94,
  "The Methodical": 95,
  "The TE Hoarder": 96,
  "The Hero": 97,
  "The Stack Master": 98,
  "The Bulwark": 99,
  "The Complete Package": 100,
  "The Fundamentalist": 101,
  "The Conservative": 102,
  "The Cautious": 301,
  "The Air Raid Classic": 103,
  "The Air Raid Zero": 302,
  "The Reliable": 104,
  "The Wildcatter": 105,
  "The Systematic": 106,
  "The Enduring": 107,
  "The Gambit": 108,
  "The Methodist": 109,
  "The Blue Collar": 110,
  "The Lone Wolf": 111,
  "The Spartan General": 112,
  "The Sure Thing": 113,
  "The Certainty": 225,
  "The Luxury Tax": 114,
  "The Balance Sheet": 115,
  "The Blueprint": 116,
  "The Schematic": 303,
  "The Signal Caller": 117,
  "The Franchise QB": 118,
  "The Immovable Object": 119,
  "The Cornerstone": 120,
  "The Load Bearing": 226,
  "The Value Engineer": 121,
  "The Reliable Duo": 122,
  "The Twin Pillars": 227,
  "The Late Bloomer": 123,
  "The Second Wind": 228,
  "The Hard Hat": 124,
  "The Steel Toed": 229,
  "The Bet Hedger": 125,
  "The Mileage": 126,
  "The Fortress Wall": 127,
  "The Thunder": 128,
  "The Return on Investment": 129,
  "The Old School": 130,
  "The Backfield Boss": 131,
  "The Classicist": 132,
  "The Traditionalist": 133,
  "The Ground & Pound": 134,
  "The Arbitrageur": 135,
  "The Iron Curtain": 136,
  "The Brute Force": 137,
  "The Sledgehammer": 138,
  "The Workhorse": 139,
  "The Ground Game": 140,
  "The Run First": 141,
  "The Bruiser": 142,
  "The Battering Ram": 230,
  "The Lone Ranger": 143,
  "The Run Committee": 144,
  "The Blue Chip": 231,
  "The Big Four": 232,
  "The Asset Manager": 233,
  "The Grand Slam": 234,
  "The Big Three": 235,
  "The GM": 236,
  "The Power Play": 237,
  "The Triple Header": 238,
  "The Brass Tacks": 239,
  "The Long Shot": 240,
  "The Underdog Play": 241,
  "The Reliable Roster": 242,
  "The Late Surge": 243,
  "The Loaded Roster": 244,
  "The Complete Roster": 245,
  "The Balanced Attack": 246,
  "The Dual Threat": 247,
  "The Diversified": 248,
  "The Coalition": 249,
  "The Alliance": 304,
  "The Contrarian": 250,
  "The Dissenter": 305,
  "The Diversified Portfolio": 251,
  "The Chaos Theory": 252,
  "The Spartan": 253,
  "The Stripped Down": 306,
  "The Iron Will": 254,
  "The Maverick's Mirror": 255,
  "The Stoic's Formula": 256,
  "The Power Formation": 257,
  "The Triple Crown": 258,
  "The War Room General": 259,
  "The Triple Threat": 260,
  "The Draft Board": 261,
  "The Formation": 262,
  "The Gambler's Gambit": 263,
  "The Draft Room": 264,
  "The Trenches": 265,
  "The Return on Rushes": 266,
  "The Lottery Ticket": 267,
  "The Value Play": 268,
  "The Workhorse Classic": 269,
  "The Hammer Drop": 270,
  "The Mileage Counter": 271,
  "The Portfolio": 272,
  "The Full House": 273,
  "The Machine": 274,
  "The Trench Worker": 275,
  "The Gridiron": 276,
  "The Meat and Potatoes": 277,
  "The Powerhouse": 278,
  "The Hammer": 279,
  "The Strongman": 280,
  "The Behemoth": 281,
  "The Tank": 282,
  "The Juggernaut": 283,
  "The Steel Curtain": 284,
  "The Bulldozer": 285,
  "The No-QB Club": 286,
  "The Gunslinger's Nemesis": 287,
  "The Old Faithful": 288,
  "The Lock In": 145,
  "The Two Premium": 146,
  "The Premium Purist": 147,
  "The Methodical Premium": 148,
  "The Early Adopter": 149,
  "The Structured Gamble": 150,
  "The Signal First": 151,
  "The Bold Departure": 152,
  "The QB Truther": 153,
  "The Locked In": 154,
  "The Last Resort Premium": 155,
  "The Late Value": 156,
  "The Deep Value": 157,
  "The Longshot": 158,
  "The Waiver Wire Maestro": 159,
  "The Steady Builder": 160,
  "The Hail Mary Classic": 161,
  "The Process Builder": 162,
  "The Safe Inversion": 163,
  "The Inverted Draft": 164,
  "The Value Inversion": 165,
  "The Patient Investor": 166,
  "The Late Bloomer Special": 167,
  "The Efficiency Play": 168,
  "The Deep Sleeper": 169,
  "The Waiver King": 170,
  "The Wire to Wire": 171,
  "The Safe Chaos": 172,
  "The Chaos Premium": 173,
  "The Value Chaos": 174,
  "The Survivalist": 175,
  "The Dumpster Fire Chic": 176,
  "The Spartan Builder": 177,
  "The Minimalist Extreme": 178,
  "The Total Chaos": 179,
  "The Pure Contrarian": 180,
  "The Premium Build": 181,
  "The Kelce-Allen Special": 182,
  "The Non-Conformist": 183,
  "The Unorthodox": 184,
  "The Upside Down": 185,
  "The Contrarian Formula": 186,
  "The Steady Signal": 187,
  "The Air Strike": 188,
  "The Quarterback First": 189,
  "The Safe Premium": 190,
  "The Premium TE Play": 191,
  "The TE Premium Value": 192,
  "The Patient": 193,
  "The Gambler's Process": 194,
  "The Efficiency Expert": 195,
  "The Patient Builder": 196,
  "The Late Skill Surge": 197,
  "The Optimizer's Path": 198,
  "The Cautious Premium": 199,
  "The TE Believer": 200,
  "The Balanced Premium": 201,
  "The Patient Drafter": 202,
  "The Slow Burn": 203,
  "The Contrarian BPA": 204,
  "The Deliberate Builder": 205,
  "The Delayed Attack": 206,
  "The Process": 207,
  "The TE Anchor": 208,
  "The TE Truther": 209,
  "The TE Value Hunter": 210,
  "The Grinder's Path": 211,
  "The Hail Mary": 212,
  "The Uncommon Value": 213,
  "The Minimalist Builder": 214,
  "The Chaos Builder": 215,
  "The Robot Builder": 216,
  "The Fortress": 307,
  "The Two Towers": 308,
  "The Dual Anchor": 309,
  "The Star Collector": 310,
  "The Synergist": 311,
  "The Ironclad": 312,
  "The Big Play": 313,
  "The Executive": 314,
  "The Rock": 315,
  "The High Roller": 316,
  "The Purist": 317,
  "The Steady Anchor": 318,
  "The Boom or Bust": 319,
  "The Daredevil": 320,
  "The Troika": 321,
  "The Professor": 322,
  "The Pairing": 323,
  "The Dynamic Duo": 324,
  "The Veteran Move": 325,
  "The Showstopper": 326,
  "The Anchor": 327,
  "The All-In": 328,
  "The Pragmatic Renegade": 329,
  "The Renegade": 330,
  "The Moonshot": 331,
  "The Logician's Ghost": 332,
  "The Franchise Builder": 333,
  "The Architect": 334,
  "The Commander": 335,
  "The Gambler": 336,
  "The Tactician": 337,
  "The Signal Corps": 338,
  "The Air Raid": 339,
  "The Field Marshal": 340,
  "The Pillar": 341,
  "The Premium Collector": 342,
  "The Route Runner": 343,
  "The Wide Open": 344,
  "The Value Seeker": 345,
  "The Grinder": 346,
  "The Boom Factory": 347,
  "The Realist": 348,
  "The Foundation": 349,
  "The Double Down": 350,
  "The Optimizer": 351,
  "The Safe Bet": 352,
  "The Streaker": 353,
  "The Efficient Market": 354,
  "The Steady Receiver": 355,
  "The Spreadsheet": 356,
  "The Bedrock": 357,
  "The Swing Trader": 358,
  "The Anarchist": 359,
  "The Pure Chaos": 360,
  "The Special Teams Stan": 361,
  "The Kicker Truther": 362,
  "The Double Dipper": 363,
  "The DST Hoarder": 364,
  "The Ostrich": 365,
  "The Opening Kickoff": 366,
  "The Special Teams First Ballot": 367,
  "The Homer": 368,
  "The One Trick Pony": 369,
  "The Hometown Hero": 370,
  "The Time Traveler": 371,
  "The Fantasy Hipster": 372,
  "The Anti-ADP": 373,
  "The Injury Magnet": 374,
  "The Rookie Truther": 375,
  "The Old Boys Club": 376,
  "The RB Apocalypse": 377,
  "The Air Show": 378,
  "The Quarterback Factory": 379,
  "The TE Convention": 380,
  "The Zero Position": 381,
  "The Panic Button": 382,
  "The YOLO": 383,
  "The Handcuff Army": 384,
  "The Lottery Ticket Booth": 385,
  "The Fantasy Sommelier": 386,
  "The Alphabetical": 387,
  "The Retirement Watch": 388,
  "The Dynasty Dropout": 389
};

/** Public URL for a composed archetype badge PNG, or undefined if unknown (e.g. The Improviser). */
export function getArchetypeBadgePublicUrl(archetypeName: string): string | undefined {
  const filename = ARCHETYPE_BADGE_FILENAME_BY_NAME[archetypeName.trim()];
  if (!filename) return undefined;
  return `${ARCHETYPE_BADGE_PUBLIC_DIR}/${filename}`;
}
