-- PPR / season / non-superflex baseline rankings
-- Inserts into baseline_community_rankings (matches players by name, season=2025)
-- Adds FA rookies to baseline_rookies if not in players or already in baseline_rookies

WITH parsed (input_name, position, avg_rank, is_fa) AS (
  VALUES
    ('Ja''Marr Chase', 'WR', 1.7::numeric, false),
    ('Bijan Robinson', 'RB', 2.0::numeric, false),
    ('Puka Nacua', 'WR', 2.3::numeric, false),
    ('Jaxon Smith-Njigba', 'WR', 4.0::numeric, false),
    ('Jahmyr Gibbs', 'RB', 5.0::numeric, false),
    ('CeeDee Lamb', 'WR', 6.7::numeric, false),
    ('Amon-Ra St. Brown', 'WR', 7.3::numeric, false),
    ('Christian McCaffrey', 'RB', 7.5::numeric, false),
    ('Justin Jefferson', 'WR', 10.8::numeric, false),
    ('Drake London', 'WR', 11.3::numeric, false),
    ('Malik Nabers', 'WR', 11.3::numeric, false),
    ('Jonathan Taylor', 'RB', 11.5::numeric, false),
    ('De''Von Achane', 'RB', 12.0::numeric, false),
    ('Nico Collins', 'WR', 14.2::numeric, false),
    ('Rashee Rice', 'WR', 15.2::numeric, false),
    ('Chris Olave', 'WR', 17.7::numeric, false),
    ('George Pickens', 'WR', 17.8::numeric, false),
    ('Ashton Jeanty', 'RB', 18.7::numeric, false),
    ('Trey McBride', 'TE', 19.0::numeric, false),
    ('Brock Bowers', 'TE', 19.0::numeric, false),
    ('James Cook III', 'RB', 19.0::numeric, false),
    ('A.J. Brown', 'WR', 20.8::numeric, false),
    ('Omarion Hampton', 'RB', 23.2::numeric, false),
    ('Chase Brown', 'RB', 24.2::numeric, false),
    ('Josh Allen', 'QB', 25.0::numeric, false),
    ('Tetairoa McMillan', 'WR', 25.2::numeric, false),
    ('Tee Higgins', 'WR', 28.5::numeric, false),
    ('Lamar Jackson', 'QB', 29.0::numeric, false),
    ('Drake Maye', 'QB', 29.7::numeric, false),
    ('Saquon Barkley', 'RB', 31.0::numeric, false),
    ('Garrett Wilson', 'WR', 31.7::numeric, false),
    ('Josh Jacobs', 'RB', 33.3::numeric, false),
    ('Bucky Irving', 'RB', 35.0::numeric, false),
    ('Breece Hall', 'RB', 37.7::numeric, false),
    ('Davante Adams', 'WR', 38.0::numeric, false),
    ('Joe Burrow', 'QB', 38.7::numeric, false),
    ('Ladd McConkey', 'WR', 39.0::numeric, false),
    ('Jameson Williams', 'WR', 40.3::numeric, false),
    ('Zay Flowers', 'WR', 40.7::numeric, false),
    ('Derrick Henry', 'RB', 41.5::numeric, false),
    ('Jaylen Waddle', 'WR', 43.7::numeric, false),
    ('DeVonta Smith', 'WR', 44.5::numeric, false),
    ('Kyren Williams', 'RB', 46.0::numeric, false),
    ('Terry McLarin', 'WR', 46.2::numeric, false),
    ('Kenneth Walker III', 'RB', 46.7::numeric, false),
    ('Luther Burden III', 'WR', 46.7::numeric, false),
    ('Mike Evans', 'WR', 47.3::numeric, false),
    ('RJ Harvey', 'RB', 50.8::numeric, false),
    ('Harold Fannin Jr.', 'TE', 52.5::numeric, false),
    ('Colston Loveland', 'TE', 52.8::numeric, false),
    ('Courtland Sutton', 'WR', 53.3::numeric, false),
    ('Emeka Egbuka', 'WR', 53.5::numeric, false),
    ('Travis Etienne Jr.', 'RB', 53.7::numeric, false),
    ('Jayden Daniels', 'QB', 53.8::numeric, false),
    ('Cam Skattebo', 'RB', 53.8::numeric, false),
    ('TreVeyon Henderson', 'RB', 54.0::numeric, false),
    ('Javonte Williams', 'RB', 55.3::numeric, false),
    ('Christian Watson', 'WR', 57.2::numeric, false),
    ('Jalen Hurts', 'QB', 58.8::numeric, false),
    ('Quinshon Judkins', 'RB', 61.8::numeric, false),
    ('DK Metcalf', 'WR', 62.7::numeric, false),
    ('Jakobi Meyers', 'WR', 64.2::numeric, false),
    ('Rome Odunze', 'WR', 64.5::numeric, false),
    ('Tucker Kraft', 'TE', 64.5::numeric, false),
    ('Jaxson Dart', 'QB', 65.0::numeric, false),
    ('D''Andre Swift', 'RB', 66.0::numeric, false),
    ('Brian Thomas Jr.', 'WR', 66.3::numeric, false),
    ('Tyler Warren', 'TE', 68.0::numeric, false),
    ('Ricky Pearsall', 'WR', 68.8::numeric, false),
    ('Justin Herbert', 'QB', 70.3::numeric, false),
    ('Jaylen Warren', 'RB', 70.3::numeric, false),
    ('Stefon Diggs', 'WR', 73.5::numeric, false),
    ('Chris Godwin Jr.', 'WR', 74.7::numeric, false),
    ('Kyle Monangai', 'RB', 80.0::numeric, false),
    ('Trevor Lawrence', 'QB', 80.3::numeric, false),
    ('Rhamondre Stevenson', 'RB', 81.0::numeric, false),
    ('Rico Dowdle', 'RB', 82.2::numeric, false),
    ('Caleb Williams', 'QB', 82.3::numeric, false),
    ('Tony Pollard', 'RB', 83.3::numeric, false),
    ('Marvin Harrison Jr.', 'WR', 84.3::numeric, false),
    ('Michael Wilson', 'WR', 84.3::numeric, false),
    ('Sam LaPorta', 'TE', 85.3::numeric, false),
    ('Michael Pittman Jr.', 'WR', 86.8::numeric, false),
    ('Patrick Mahomes II', 'QB', 88.8::numeric, false),
    ('Kyle Pitts Sr.', 'TE', 89.3::numeric, false),
    ('Blake Corum', 'RB', 91.7::numeric, false),
    ('Dak Prescott', 'QB', 93.3::numeric, false),
    ('Brock Purdy', 'QB', 93.3::numeric, false),
    ('Jordan Addison', 'WR', 94.0::numeric, false),
    ('James Conner', 'RB', 95.2::numeric, false),
    ('Bhayshul Tuten', 'RB', 95.2::numeric, false),
    ('Wan''Dale Robinson', 'WR', 96.8::numeric, false),
    ('Chuba Hubbard', 'RB', 99.0::numeric, false),
    ('Quentin Johnston', 'WR', 100.5::numeric, false),
    ('Dalton Kincaid', 'TE', 100.5::numeric, false),
    ('Woody Marks', 'RB', 100.8::numeric, false),
    ('Aaron Jones Sr.', 'RB', 100.8::numeric, false),
    ('Trey Benson', 'RB', 102.0::numeric, false),
    ('Khalil Shakir', 'WR', 102.7::numeric, false),
    ('Zach Charbonnet', 'RB', 103.7::numeric, false),
    ('Alec Pierce', 'WR', 104.5::numeric, false),
    ('Jauan Jennings', 'WR', 104.8::numeric, false),
    ('Alvin Kamara', 'RB', 105.7::numeric, false),
    ('Matthew Stafford', 'QB', 105.8::numeric, false),
    ('Bo Nix', 'QB', 106.3::numeric, false),
    ('Oronde Gadsden II', 'TE', 106.8::numeric, false),
    ('Jake Ferguson', 'TE', 107.7::numeric, false),
    ('Brenton Strange', 'TE', 108.8::numeric, false),
    ('Jordan Love', 'QB', 109.0::numeric, false),
    ('Jared Goff', 'QB', 111.5::numeric, false),
    ('Parker Washington', 'WR', 111.7::numeric, false),
    ('Juwan Johnson', 'TE', 113.2::numeric, false),
    ('Travis Hunter', 'WR', 114.0::numeric, false),
    ('Baker Mayfield', 'QB', 116.5::numeric, false),
    ('DJ Moore', 'WR', 116.7::numeric, false),
    ('Tyreek Hill', 'WR', 117.2::numeric, true),
    ('David Montgomery', 'RB', 120.5::numeric, false),
    ('Jacory Croskey-Merritt', 'RB', 121.3::numeric, false),
    ('Jayden Higgins', 'WR', 121.5::numeric, false),
    ('Malik Willis', 'QB', 123.0::numeric, false),
    ('Xavier Worthy', 'WR', 123.3::numeric, false),
    ('Tyler Shough', 'QB', 124.5::numeric, false),
    ('Dylan Sampson', 'RB', 124.8::numeric, false),
    ('Jayden Reed', 'WR', 125.2::numeric, false),
    ('George Kittle', 'TE', 127.7::numeric, false),
    ('Josh Downs', 'WR', 129.0::numeric, false),
    ('Braelon Allen', 'RB', 129.8::numeric, false),
    ('Dalton Schultz', 'TE', 129.8::numeric, false),
    ('C.J. Stroud', 'QB', 130.0::numeric, false),
    ('Deebo Samuel Sr.', 'WR', 130.0::numeric, false),
    ('Kenneth Gainwell', 'RB', 133.2::numeric, false),
    ('Tyler Allgeier', 'RB', 133.3::numeric, false),
    ('Sam Darnold', 'QB', 136.5::numeric, false),
    ('Jalen Coker', 'WR', 136.7::numeric, false),
    ('Dallas Goedert', 'TE', 137.8::numeric, false),
    ('Kyler Murray', 'QB', 138.5::numeric, false),
    ('Tyjae Spears', 'RB', 139.0::numeric, false),
    ('Tyrone Tracy Jr.', 'RB', 141.5::numeric, false),
    ('Adonai Mitchell', 'WR', 144.2::numeric, false),
    ('Cam Ward', 'QB', 144.5::numeric, false),
    ('Jerry Jeudy', 'WR', 145.3::numeric, false),
    ('Troy Franklin', 'WR', 145.8::numeric, false),
    ('J.K. Dobbins', 'RB', 146.0::numeric, false),
    ('Hunter Henry', 'TE', 148.0::numeric, false),
    ('Jordan Mason', 'RB', 148.0::numeric, false),
    ('Rachaad White', 'RB', 150.7::numeric, false),
    ('Houston Texans', 'D/ST', 151.0::numeric, false),
    ('Kaleb Johnson', 'RB', 151.3::numeric, false),
    ('Rashid Shaheed', 'WR', 156.0::numeric, false),
    ('Jeremiyah Love', 'RB', 156.3::numeric, true),
    ('Chimere Dike', 'WR', 157.5::numeric, false),
    ('Bryce Young', 'QB', 159.3::numeric, false),
    ('Brandon Aiyuk', 'WR', 159.5::numeric, false),
    ('Travis Kelce', 'TE', 161.2::numeric, false),
    ('Tre Harris', 'WR', 161.8::numeric, false),
    ('Denver Broncos', 'D/ST', 162.0::numeric, false),
    ('Carnell Tate', 'WR', 162.7::numeric, true),
    ('Devin Neal', 'RB', 163.0::numeric, false),
    ('K.C. Concepcion', 'WR', 163.8::numeric, true),
    ('Tank Bigsby', 'RB', 165.7::numeric, false),
    ('Isaiah Likely', 'TE', 165.7::numeric, false),
    ('Isiah Pacheco', 'RB', 165.8::numeric, false),
    ('Matthew Golden', 'WR', 165.8::numeric, false),
    ('Jaylin Noel', 'WR', 166.0::numeric, false),
    ('Seattle Seahawks', 'D/ST', 166.0::numeric, false),
    ('Jordyn Tyson', 'WR', 167.0::numeric, true),
    ('Mark Andrews', 'TE', 167.0::numeric, false),
    ('Romeo Doubs', 'WR', 167.8::numeric, false),
    ('Fernando Mendoza', 'QB', 170.3::numeric, true),
    ('Elic Ayomanor', 'WR', 170.7::numeric, false),
    ('Kimani Vidal', 'RB', 171.5::numeric, false),
    ('Philadelphia Eagles', 'D/ST', 171.8::numeric, false),
    ('Makai Lemon', 'WR', 172.8::numeric, true),
    ('Los Angeles Rams', 'D/ST', 173.0::numeric, false),
    ('J.J. McCarthy', 'QB', 174.3::numeric, false),
    ('Kayshon Boutte', 'WR', 174.3::numeric, false),
    ('Keaton Mitchell', 'RB', 176.7::numeric, false),
    ('Pat Bryant', 'WR', 178.2::numeric, false),
    ('Minnesota Vikings', 'D/ST', 183.0::numeric, false),
    ('Brian Robinson Jr.', 'RB', 183.3::numeric, false),
    ('Theo Johnson', 'TE', 184.7::numeric, false),
    ('Kendre Miller', 'RB', 185.0::numeric, false),
    ('New England Patriots', 'D/ST', 185.0::numeric, false),
    ('Jacksonville Jaguars', 'D/ST', 186.0::numeric, false),
    ('Brandon Aubrey', 'K', 187.0::numeric, false),
    ('Los Angeles Chargers', 'D/ST', 188.0::numeric, false),
    ('Green Bay Packers', 'D/ST', 190.0::numeric, false),
    ('Joe Mixon', 'RB', 190.2::numeric, false),
    ('Michael Penix Jr.', 'QB', 190.7::numeric, false),
    ('Isaiah Davis', 'RB', 190.8::numeric, false),
    ('Pittsburgh Steelers', 'D/ST', 191.0::numeric, false),
    ('Denzel Boston', 'WR', 128.0::numeric, true),
    ('Ka''imi Fairbairn', 'K', 192.0::numeric, false),
    ('Tre Tucker', 'WR', 192.8::numeric, false),
    ('Cam Little', 'K', 193.0::numeric, false),
    ('Ryan Flournoy', 'WR', 194.0::numeric, false),
    ('Darnell Mooney', 'WR', 195.0::numeric, false),
    ('Cleveland Browns', 'D/ST', 196.0::numeric, false),
    ('Cameron Dicker', 'K', 198.0::numeric, false),
    ('Jalen McMillan', 'WR', 198.8::numeric, false),
    ('Evan McPherson', 'K', 201.3::numeric, false),
    ('T.J. Hockenson', 'TE', 203.2::numeric, false),
    ('Jason Myers', 'K', 204.5::numeric, false),
    ('Daniel Jones', 'QB', 205.2::numeric, false),
    ('Tyler Loop', 'K', 207.2::numeric, false),
    ('Emanuel Wilson', 'RB', 208.2::numeric, false),
    ('Terrance Ferguson', 'TE', 208.8::numeric, false),
    ('Kansas City Chiefs', 'D/ST', 209.0::numeric, false),
    ('Jaylen Wright', 'RB', 209.3::numeric, false),
    ('Andy Borregales', 'K', 209.7::numeric, false),
    ('Keon Coleman', 'WR', 211.5::numeric, false),
    ('AJ Barner', 'TE', 211.5::numeric, false),
    ('Mack Hollins', 'WR', 211.7::numeric, false),
    ('Marvin Mims Jr.', 'WR', 212.2::numeric, false),
    ('Detroit Lions', 'D/ST', 213.0::numeric, false),
    ('Eddy Pineiro', 'K', 213.0::numeric, false),
    ('Isaac TeSlaa', 'WR', 213.5::numeric, false),
    ('Jadarian Price', 'RB', 110.3::numeric, true),
    ('Chase McLaughlin', 'K', 215.2::numeric, false),
    ('Calvin Ridley', 'WR', 216.2::numeric, false),
    ('Cairo Santos', 'K', 216.2::numeric, false),
    ('Mason Taylor', 'TE', 216.5::numeric, false),
    ('Jonathon Brooks', 'RB', 217.8::numeric, false),
    ('Emmett Johnson', 'RB', 119.0::numeric, true),
    ('Buffalo Bills', 'D/ST', 220.0::numeric, false),
    ('Brashard Smith', 'RB', 220.5::numeric, false),
    ('Xavier Legette', 'WR', 220.5::numeric, false),
    ('Rashod Bateman', 'WR', 220.8::numeric, false),
    ('Kyle Williams', 'WR', 222.0::numeric, false),
    ('Harrison Mevis', 'K', 222.3::numeric, false),
    ('Najee Harris', 'RB', 223.0::numeric, false),
    ('Keenan Allen', 'WR', 225.2::numeric, false),
    ('Dontayvion Wicks', 'WR', 225.3::numeric, false),
    ('Sean Tucker', 'RB', 226.3::numeric, false),
    ('Jonah Coleman', 'RB', 134.7::numeric, true),
    ('Jerome Ford', 'RB', 209.2::numeric, false),
    ('Gunnar Helm', 'TE', 230.8::numeric, false),
    ('Ray Davis', 'RB', 230.8::numeric, false),
    ('Chris Rodriguez Jr.', 'RB', 233.3::numeric, false),
    ('Cooper Kupp', 'WR', 234.7::numeric, false),
    ('Jake Bates', 'K', 236.2::numeric, false),
    ('Baltimore Ravens', 'D/ST', 237.3::numeric, false),
    ('Tory Horton', 'WR', 239.5::numeric, false),
    ('Darius Slayton', 'WR', 240.3::numeric, false),
    ('David Njoku', 'TE', 241.3::numeric, false),
    ('Chig Okonkwo', 'TE', 242.7::numeric, false),
    ('Ollie Gordon II', 'RB', 243.3::numeric, false),
    ('Ty Johnson', 'RB', 245.5::numeric, false),
    ('Jaleel McLaughlin', 'RB', 246.2::numeric, false),
    ('Isaiah Bond', 'WR', 248.0::numeric, false),
    ('Tank Dell', 'WR', 249.8::numeric, false),
    ('Colby Parkinson', 'TE', 251.0::numeric, false),
    ('Chris Boswell', 'K', 252.0::numeric, false),
    ('Shedeur Sanders', 'QB', 259.2::numeric, false),
    ('Wil Lutz', 'K', 259.3::numeric, false),
    ('Jalen Royals', 'WR', 260.2::numeric, false),
    ('Pat Freiermuth', 'TE', 260.5::numeric, false),
    ('Evan Engram', 'TE', 261.5::numeric, false),
    ('Atlanta Falcons', 'D/ST', 261.8::numeric, false),
    ('Charlie Smyth', 'K', 251.2::numeric, false),
    ('Konata Mumpfield', 'WR', 264.3::numeric, false),
    ('Isaac Guerendo', 'RB', 254.0::numeric, false),
    ('Harrison Butker', 'K', 265.8::numeric, false),
    ('Cade Otton', 'TE', 265.8::numeric, false),
    ('Jack Bech', 'WR', 267.0::numeric, false),
    ('Andrei Iosivas', 'WR', 257.8::numeric, false),
    ('Devaughn Vele', 'WR', 269.0::numeric, false),
    ('Omar Cooper Jr.', 'WR', 168.0::numeric, true),
    ('New Orleans Saints', 'D/ST', 270.5::numeric, false),
    ('Mike Washington Jr.', 'RB', 175.5::numeric, true),
    ('Kenyon Sadiq', 'TE', 225.0::numeric, true),
    ('Jacoby Brissett', 'QB', 274.3::numeric, false),
    ('San Francisco 49ers', 'D/ST', 251.8::numeric, false),
    ('Christian Kirk', 'WR', 266.4::numeric, false),
    ('Malachi Fields', 'WR', 187.0::numeric, true),
    ('Bam Knight', 'RB', 266.8::numeric, false),
    ('Audric Estime', 'RB', 267.4::numeric, false),
    ('Jake Tonges', 'TE', 268.2::numeric, false),
    ('Marquise Brown', 'WR', 277.0::numeric, false),
    ('Malik Davis', 'RB', 270.6::numeric, false),
    ('Chris Brazzell II', 'WR', 197.0::numeric, true),
    ('Calvin Austin III', 'WR', 271.4::numeric, false),
    ('Jaydon Blue', 'RB', 280.2::numeric, false),
    ('Luke McCaffrey', 'WR', 280.5::numeric, false),
    ('Kaytron Allen', 'RB', 202.5::numeric, true),
    ('Tyquan Thornton', 'WR', 275.4::numeric, false),
    ('Noah Gray', 'TE', 276.6::numeric, false),
    ('DJ Giddens', 'RB', 284.0::numeric, false),
    ('Aaron Rodgers', 'QB', 271.0::numeric, false),
    ('Dont''e Thornton Jr.', 'WR', 277.0::numeric, false),
    ('Mac Jones', 'QB', 284.2::numeric, false),
    ('LeQuint Allen Jr.', 'RB', 278.4::numeric, false),
    ('Elijah Sarratt', 'WR', 219.0::numeric, true),
    ('Cedric Tillman', 'WR', 286.7::numeric, false),
    ('Malik Washington', 'WR', 290.5::numeric, false),
    ('Germie Bernard', 'WR', 228.5::numeric, true),
    ('Devin Singletary', 'RB', 285.0::numeric, false),
    ('Zachariah Branch', 'WR', 233.0::numeric, true),
    ('Mike Gesicki', 'TE', 285.6::numeric, false),
    ('Chris Brooks', 'RB', 287.0::numeric, false),
    ('George Holani', 'RB', 293.2::numeric, false),
    ('Nicholas Singleton', 'RB', 235.5::numeric, true),
    ('Tua Tagovailoa', 'QB', 293.0::numeric, false),
    ('Eli Stowers', 'TE', 266.3::numeric, true),
    ('Olamide Zaccheaus', 'WR', 297.7::numeric, false),
    ('Justice Hill', 'RB', 291.0::numeric, false),
    ('John Bates', 'TE', 292.0::numeric, false),
    ('Trevor Etienne', 'RB', 291.6::numeric, false),
    ('Tez Johnson', 'WR', 299.0::numeric, false),
    ('John Metchie III', 'WR', 297.4::numeric, false),
    ('Antonio Williams', 'WR', 256.0::numeric, true),
    ('Indianapolis Colts', 'D/ST', 294.8::numeric, false),
    ('Ben Sinnott', 'TE', 288.0::numeric, false),
    ('Will Reichard', 'K', 258.5::numeric, false),
    ('Darren Waller', 'TE', 279.0::numeric, false),
    ('Jarquez Hunter', 'RB', 295.4::numeric, false),
    ('Jaylin Lane', 'WR', 303.7::numeric, false),
    ('MarShawn Lloyd', 'RB', 295.8::numeric, false),
    ('Joshua Palmer', 'WR', 305.8::numeric, false),
    ('Demond Claiborne', 'RB', 267.0::numeric, true),
    ('Elijah Arroyo', 'TE', 286.0::numeric, false),
    ('Michael Mayer', 'TE', 287.0::numeric, false),
    ('Jordan James', 'RB', 314.2::numeric, false),
    ('Xavier Hutchinson', 'WR', 310.8::numeric, false),
    ('Michael Carter', 'RB', 305.8::numeric, false),
    ('Chris Bell', 'WR', 303.5::numeric, true),
    ('Will Shipley', 'RB', 311.0::numeric, false),
    ('DeMario Douglas', 'WR', 312.8::numeric, false),
    ('Samaje Perine', 'RB', 311.5::numeric, false),
    ('Miami Dolphins', 'D/ST', 310.4::numeric, false),
    ('Emari Demercado', 'RB', 307.8::numeric, false),
    ('Jalen Nailor', 'WR', 314.8::numeric, false),
    ('Anthony Richardson Sr.', 'QB', 306.4::numeric, false),
    ('Tahj Brooks', 'RB', 315.0::numeric, false),
    ('Tommy Myers', 'TE', 288.0::numeric, true),
    ('Greg Dulcich', 'TE', 297.5::numeric, false),
    ('Kareem Hunt', 'RB', 316.8::numeric, false),
    ('Austin Ekeler', 'RB', 317.2::numeric, false),
    ('Geno Smith', 'QB', 315.0::numeric, false),
    ('Nick Chubb', 'RB', 317.2::numeric, false),
    ('Darnell Washington', 'TE', 306.5::numeric, false),
    ('Zane Gonzalez', 'K', 314.7::numeric, false),
    ('Joe Milton III', 'QB', 319.0::numeric, false),
    ('Tyler Higbee', 'TE', 322.0::numeric, false),
    ('Jawhar Jordan', 'RB', 315.2::numeric, false),
    ('Terrell Jennings', 'RB', 330.5::numeric, false),
    ('Tyrod Taylor', 'QB', 307.5::numeric, false),
    ('Ty Simpson', 'QB', 311.0::numeric, true),
    ('Antonio Gibson', 'RB', 313.7::numeric, false),
    ('Raheim Sanders', 'RB', 328.8::numeric, false),
    ('Dameon Pierce', 'RB', 334.0::numeric, false),
    ('Marcus Mariota', 'QB', 347.5::numeric, false)
),
aliases (input_name, db_name) AS (
  VALUES
    ('Patrick Mahomes II', 'Patrick Mahomes'),
    ('Deebo Samuel Sr.', 'Deebo Samuel'),
    ('Aaron Jones Sr.', 'Aaron Jones'),
    ('Anthony Richardson Sr.', 'Anthony Richardson'),
    ('Chris Godwin Jr.', 'Chris Godwin'),
    ('Brian Thomas Jr.', 'Brian Thomas'),
    ('Kyle Pitts Sr.', 'Kyle Pitts'),
    ('Michael Pittman Jr.', 'Michael Pittman'),
    ('Marvin Harrison Jr.', 'Marvin Harrison'),
    ('Ollie Gordon II', 'Ollie Gordon'),
    ('Chris Rodriguez Jr.', 'Chris Rodriguez'),
    ('Terry McLarin', 'Terry McLaurin'),
    ('Jonathon Brooks', 'Jonathan Brooks'),
    ('Travis Etienne Jr.', 'Travis Etienne'),
    ('Michael Penix Jr.', 'Michael Penix')
),
lookup AS (
  SELECT 
    p.input_name,
    p.position,
    p.avg_rank,
    p.is_fa,
    COALESCE(a.db_name, p.input_name) AS match_name
  FROM parsed p
  LEFT JOIN aliases a ON a.input_name = p.input_name
),

-- Insert baseline_community_rankings for all players that exist in players (season 2025)
ins_baseline AS (
  INSERT INTO public.baseline_community_rankings (scoring_format, league_type, is_superflex, player_id, rank)
  SELECT 
    'ppr'::text,
    'season'::text,
    false,
    pl.id,
    l.avg_rank
  FROM lookup l
  INNER JOIN public.players pl ON pl.name = l.match_name AND pl.season = 2025
  ON CONFLICT (scoring_format, league_type, is_superflex, player_id)
  DO UPDATE SET rank = EXCLUDED.rank
)

-- Insert FA rookies not in players and not already in baseline_rookies
INSERT INTO public.baseline_rookies (name, position, rank, scoring_format, league_type, is_superflex)
SELECT l.input_name, l.position, l.avg_rank, 'ppr'::text, 'season'::text, false
FROM lookup l
WHERE l.is_fa = true
  AND NOT EXISTS (
    SELECT 1 FROM public.players p
    WHERE (p.name = l.match_name OR p.name = l.input_name) AND p.season = 2025
  )
  AND NOT EXISTS (
    SELECT 1 FROM public.baseline_rookies br
    WHERE br.name = l.input_name
      AND br.scoring_format = 'ppr'
      AND br.league_type = 'season'
      AND br.is_superflex = false
  )
ON CONFLICT (scoring_format, league_type, is_superflex, name) DO NOTHING;
