-- PPR / dynasty / non-superflex baseline rankings
-- Inserts into baseline_community_rankings (matches players by name, season=2025)
-- Adds FA rookies to baseline_rookies if not in players or already in baseline_rookies

WITH parsed (input_name, position, avg_rank, is_fa) AS (
  VALUES
    ('Ja''Marr Chase', 'WR', 1.1::numeric, false),
    ('Puka Nacua', 'WR', 2.7::numeric, false),
    ('Jaxon Smith-Njigba', 'WR', 3.3::numeric, false),
    ('Bijan Robinson', 'RB', 4.7::numeric, false),
    ('Jahmyr Gibbs', 'RB', 5.8::numeric, false),
    ('CeeDee Lamb', 'WR', 6.3::numeric, false),
    ('Justin Jefferson', 'WR', 6.5::numeric, false),
    ('Amon-Ra St. Brown', 'WR', 8.1::numeric, false),
    ('Malik Nabers', 'WR', 9.4::numeric, false),
    ('Ashton Jeanty', 'RB', 10.8::numeric, false),
    ('Drake London', 'WR', 11.6::numeric, false),
    ('De''Von Achane', 'RB', 12.1::numeric, false),
    ('James Cook III', 'RB', 15.8::numeric, false),
    ('Jonathan Taylor', 'RB', 15.9::numeric, false),
    ('Nico Collins', 'WR', 16.3::numeric, false),
    ('George Pickens', 'WR', 18.1::numeric, false),
    ('Omarion Hampton', 'RB', 18.4::numeric, false),
    ('Tetairoa McMillan', 'WR', 20.2::numeric, false),
    ('Josh Allen', 'QB', 22.0::numeric, false),
    ('Brock Bowers', 'TE', 22.4::numeric, false),
    ('Rashee Rice', 'WR', 22.6::numeric, false),
    ('Garrett Wilson', 'WR', 24.2::numeric, false),
    ('Trey McBride', 'TE', 25.3::numeric, false),
    ('Chris Olave', 'WR', 25.5::numeric, false),
    ('Jeremiyah Love', 'RB', 27.0::numeric, true),
    ('Ladd McConkey', 'WR', 29.1::numeric, false),
    ('Drake Maye', 'QB', 29.6::numeric, false),
    ('Emeka Egbuka', 'WR', 30.9::numeric, false),
    ('A.J. Brown', 'WR', 34.0::numeric, false),
    ('Tee Higgins', 'WR', 34.8::numeric, false),
    ('Breece Hall', 'RB', 35.0::numeric, false),
    ('Jordyn Tyson', 'WR', 35.8::numeric, true),
    ('Bucky Irving', 'RB', 36.1::numeric, false),
    ('Carnell Tate', 'WR', 38.0::numeric, true),
    ('Zay Flowers', 'WR', 39.5::numeric, false),
    ('Brian Thomas Jr.', 'WR', 40.5::numeric, false),
    ('Makai Lemon', 'WR', 40.6::numeric, true),
    ('TreVeyon Henderson', 'RB', 40.6::numeric, false),
    ('Rome Odunze', 'WR', 40.8::numeric, false),
    ('Lamar Jackson', 'QB', 41.0::numeric, false),
    ('DeVonta Smith', 'WR', 41.5::numeric, false),
    ('Jayden Daniels', 'QB', 41.6::numeric, false),
    ('Joe Burrow', 'QB', 41.8::numeric, false),
    ('Jameson Williams', 'WR', 41.9::numeric, false),
    ('Colston Loveland', 'TE', 42.7::numeric, false),
    ('Chase Brown', 'RB', 43.0::numeric, false),
    ('Marvin Harrison Jr.', 'WR', 44.9::numeric, false),
    ('Jaylen Waddle', 'WR', 45.4::numeric, false),
    ('Luther Burden III', 'WR', 46.4::numeric, false),
    ('Christian McCaffrey', 'RB', 47.5::numeric, false),
    ('Saquon Barkley', 'RB', 48.0::numeric, false),
    ('Tyler Warren', 'TE', 48.3::numeric, false),
    ('Jalen Hurts', 'QB', 51.1::numeric, false),
    ('Patrick Mahomes II', 'QB', 52.0::numeric, false),
    ('Tucker Kraft', 'TE', 53.3::numeric, false),
    ('Harold Fannin Jr.', 'TE', 55.2::numeric, false),
    ('Quinshon Judkins', 'RB', 55.5::numeric, false),
    ('Kenneth Walker III', 'RB', 55.9::numeric, false),
    ('Kyren Williams', 'RB', 56.8::numeric, false),
    ('Sam LaPorta', 'TE', 58.0::numeric, false),
    ('Justin Herbert', 'QB', 58.3::numeric, false),
    ('Josh Jacobs', 'RB', 58.9::numeric, false),
    ('Caleb Williams', 'QB', 60.0::numeric, false),
    ('RJ Harvey', 'RB', 60.0::numeric, false),
    ('Kyle Pitts Sr.', 'TE', 64.4::numeric, false),
    ('Jordan Addison', 'WR', 64.8::numeric, false),
    ('Jaxson Dart', 'QB', 65.2::numeric, false),
    ('DK Metcalf', 'WR', 66.9::numeric, false),
    ('Cam Skattebo', 'RB', 67.6::numeric, false),
    ('Bo Nix', 'QB', 71.8::numeric, false),
    ('Travis Etienne Jr.', 'RB', 72.0::numeric, false),
    ('Christian Watson', 'WR', 72.3::numeric, false),
    ('Ricky Pearsall', 'WR', 72.7::numeric, false),
    ('Brock Purdy', 'QB', 72.8::numeric, false),
    ('Travis Hunter', 'WR', 76.5::numeric, false),
    ('Trevor Lawrence', 'QB', 76.6::numeric, false),
    ('Javonte Williams', 'RB', 77.6::numeric, false),
    ('Denzel Boston', 'WR', 78.0::numeric, true),
    ('Dalton Kincaid', 'TE', 79.8::numeric, false),
    ('Terry McLaurin', 'WR', 80.8::numeric, false),
    ('Courtland Sutton', 'WR', 82.1::numeric, false),
    ('Derrick Henry', 'RB', 82.5::numeric, false),
    ('Michael Pittman Jr.', 'WR', 83.3::numeric, false),
    ('Xavier Worthy', 'WR', 83.9::numeric, false),
    ('Oronde Gadsden II', 'TE', 84.8::numeric, false),
    ('Davante Adams', 'WR', 86.6::numeric, false),
    ('Michael Wilson', 'WR', 88.0::numeric, false),
    ('Jordan Love', 'QB', 88.0::numeric, false),
    ('Jakobi Meyers', 'WR', 88.5::numeric, false),
    ('D''Andre Swift', 'RB', 90.3::numeric, false),
    ('DJ Moore', 'WR', 90.6::numeric, false),
    ('Wan''Dale Robinson', 'WR', 90.9::numeric, false),
    ('Jayden Higgins', 'WR', 92.3::numeric, false),
    ('Jake Ferguson', 'TE', 92.7::numeric, false),
    ('Dak Prescott', 'QB', 96.3::numeric, false),
    ('K.C. Concepcion', 'WR', 97.2::numeric, true),
    ('Jonah Coleman', 'RB', 98.3::numeric, true),
    ('Alec Pierce', 'WR', 99.2::numeric, false),
    ('Quentin Johnston', 'WR', 99.3::numeric, false),
    ('Kenyon Sadiq', 'TE', 100.3::numeric, true),
    ('George Kittle', 'TE', 100.4::numeric, false),
    ('Khalil Shakir', 'WR', 100.6::numeric, false),
    ('Jaylen Warren', 'RB', 101.0::numeric, false),
    ('Brenton Strange', 'TE', 101.2::numeric, false),
    ('Brandon Aiyuk', 'WR', 104.3::numeric, false),
    ('Kyle Monangai', 'RB', 104.9::numeric, false),
    ('Baker Mayfield', 'QB', 105.6::numeric, false),
    ('Zach Charbonnet', 'RB', 105.7::numeric, false),
    ('Jayden Reed', 'WR', 106.0::numeric, false),
    ('Eli Stowers', 'TE', 106.5::numeric, true),
    ('Matthew Golden', 'WR', 108.3::numeric, false),
    ('Mike Evans', 'WR', 108.4::numeric, false),
    ('Jauan Jennings', 'WR', 109.0::numeric, false),
    ('C.J. Stroud', 'QB', 109.5::numeric, false),
    ('Fernando Mendoza', 'QB', 112.8::numeric, true),
    ('Jared Goff', 'QB', 113.5::numeric, false),
    ('Chris Godwin Jr.', 'WR', 113.8::numeric, false),
    ('Josh Downs', 'WR', 114.0::numeric, false),
    ('Blake Corum', 'RB', 115.1::numeric, false),
    ('Woody Marks', 'RB', 115.5::numeric, false),
    ('Trey Benson', 'RB', 116.7::numeric, false),
    ('Stefon Diggs', 'WR', 118.0::numeric, false),
    ('Bhayshul Tuten', 'RB', 120.2::numeric, false),
    ('Sam Darnold', 'QB', 120.3::numeric, false),
    ('Rhamondre Stevenson', 'RB', 122.5::numeric, false),
    ('Mason Taylor', 'TE', 124.2::numeric, false),
    ('Parker Washington', 'WR', 124.7::numeric, false),
    ('Rico Dowdle', 'RB', 125.1::numeric, false),
    ('Dallas Goedert', 'TE', 128.8::numeric, false),
    ('Jalen Coker', 'WR', 130.2::numeric, false),
    ('Troy Franklin', 'WR', 131.1::numeric, false),
    ('Chuba Hubbard', 'RB', 132.4::numeric, false),
    ('David Montgomery', 'RB', 134.9::numeric, false),
    ('Theo Johnson', 'TE', 135.1::numeric, false),
    ('Terrance Ferguson', 'TE', 135.6::numeric, false),
    ('Deebo Samuel Sr.', 'WR', 136.6::numeric, false),
    ('Romeo Doubs', 'WR', 136.9::numeric, false),
    ('Tyreek Hill', 'WR', 137.7::numeric, true),
    ('Tyrone Tracy Jr.', 'RB', 138.6::numeric, false),
    ('Kyler Murray', 'QB', 138.8::numeric, false),
    ('Tre Harris', 'WR', 138.9::numeric, false),
    ('Cam Ward', 'QB', 127.2::numeric, false),
    ('Rashid Shaheed', 'WR', 141.2::numeric, false),
    ('Tyler Allgeier', 'RB', 142.0::numeric, false),
    ('Jalen McMillan', 'WR', 142.7::numeric, false),
    ('Jerry Jeudy', 'WR', 145.4::numeric, false),
    ('Mark Andrews', 'TE', 145.7::numeric, false),
    ('Bryce Young', 'QB', 145.8::numeric, false),
    ('Juwan Johnson', 'TE', 146.3::numeric, false),
    ('Isaiah Likely', 'TE', 146.8::numeric, false),
    ('Matthew Stafford', 'QB', 147.8::numeric, false),
    ('Tony Pollard', 'RB', 150.3::numeric, false),
    ('Jacory Croskey-Merritt', 'RB', 150.7::numeric, false),
    ('J.J. McCarthy', 'QB', 150.8::numeric, false),
    ('Michael Trigg', 'TE', 151.6::numeric, true),
    ('Elic Ayomanor', 'WR', 151.8::numeric, false),
    ('T.J. Hockenson', 'TE', 152.6::numeric, false),
    ('Jaylin Noel', 'WR', 152.8::numeric, false),
    ('Kayshon Boutte', 'WR', 153.9::numeric, false),
    ('Michael Penix Jr.', 'QB', 153.9::numeric, false),
    ('Malachi Fields', 'WR', 154.0::numeric, true),
    ('Daniel Jones', 'QB', 155.9::numeric, false),
    ('Pat Bryant', 'WR', 157.1::numeric, false),
    ('Adonai Mitchell', 'WR', 157.3::numeric, false),
    ('Tyler Shough', 'QB', 144.6::numeric, false),
    ('Kenneth Gainwell', 'RB', 158.8::numeric, false),
    ('Omar Cooper Jr.', 'WR', 159.2::numeric, true),
    ('Chris Brazzell II', 'WR', 159.5::numeric, true),
    ('Mike Washington Jr.', 'RB', 160.4::numeric, true),
    ('Hunter Henry', 'TE', 161.8::numeric, false),
    ('Jadarian Price', 'RB', 163.1::numeric, true),
    ('Tyjae Spears', 'RB', 166.3::numeric, false),
    ('J.K. Dobbins', 'RB', 166.5::numeric, false),
    ('Dalton Schultz', 'TE', 169.8::numeric, false),
    ('Kyle Williams', 'WR', 172.6::numeric, false),
    ('Alvin Kamara', 'RB', 172.6::numeric, false),
    ('AJ Barner', 'TE', 160.8::numeric, false),
    ('Chimere Dike', 'WR', 172.9::numeric, false),
    ('David Njoku', 'TE', 173.7::numeric, false),
    ('Keon Coleman', 'WR', 174.9::numeric, false),
    ('Kaleb Johnson', 'RB', 175.9::numeric, false),
    ('Tory Horton', 'WR', 176.6::numeric, false),
    ('Elijah Arroyo', 'TE', 179.8::numeric, false),
    ('Darnell Mooney', 'WR', 180.4::numeric, false),
    ('Jordan Mason', 'RB', 180.7::numeric, false),
    ('Tua Tagovailoa', 'QB', 180.9::numeric, false),
    ('Dylan Sampson', 'RB', 181.9::numeric, false),
    ('Isaac TeSlaa', 'WR', 182.6::numeric, false),
    ('Germie Bernard', 'WR', 182.8::numeric, true),
    ('Elijah Sarratt', 'WR', 184.3::numeric, true),
    ('Aaron Jones Sr.', 'RB', 184.8::numeric, false),
    ('Rachaad White', 'RB', 186.3::numeric, false),
    ('Zachariah Branch', 'WR', 186.8::numeric, true),
    ('James Conner', 'RB', 186.9::numeric, false),
    ('Emmett Johnson', 'RB', 187.6::numeric, true),
    ('Calvin Ridley', 'WR', 187.8::numeric, false),
    ('Antonio Williams', 'WR', 188.0::numeric, true),
    ('Chris Bell', 'WR', 188.5::numeric, true),
    ('Tank Dell', 'WR', 189.8::numeric, false),
    ('Ja''Kobi Lane', 'WR', 189.8::numeric, true),
    ('Marvin Mims Jr.', 'WR', 190.3::numeric, false),
    ('Brian Robinson Jr.', 'RB', 190.4::numeric, false),
    ('Travis Kelce', 'TE', 190.7::numeric, false),
    ('Isiah Pacheco', 'RB', 191.2::numeric, false),
    ('Braelon Allen', 'RB', 192.4::numeric, false),
    ('Tank Bigsby', 'RB', 192.8::numeric, false),
    ('Pat Freiermuth', 'TE', 197.8::numeric, false),
    ('Jonathon Brooks', 'RB', 197.8::numeric, false),
    ('Chig Okonkwo', 'TE', 198.1::numeric, false),
    ('Kimani Vidal', 'RB', 198.7::numeric, false),
    ('Cade Otton', 'TE', 199.1::numeric, false),
    ('Dontayvion Wicks', 'WR', 202.3::numeric, false),
    ('Devin Neal', 'RB', 205.0::numeric, false),
    ('Rashod Bateman', 'WR', 195.2::numeric, false),
    ('Anthony Richardson Sr.', 'QB', 205.8::numeric, false),
    ('Shedeur Sanders', 'QB', 195.9::numeric, false),
    ('Christian Kirk', 'WR', 206.8::numeric, false),
    ('Evan Engram', 'TE', 207.1::numeric, false),
    ('Malik Willis', 'QB', 175.9::numeric, false),
    ('Kaytron Allen', 'RB', 211.4::numeric, true),
    ('Cedric Tillman', 'WR', 201.5::numeric, false),
    ('Nicholas Singleton', 'RB', 211.7::numeric, true),
    ('Jack Bech', 'WR', 202.2::numeric, false),
    ('Cooper Kupp', 'WR', 214.6::numeric, false),
    ('Ty Simpson', 'QB', 216.0::numeric, true),
    ('Tez Johnson', 'WR', 219.8::numeric, false),
    ('Xavier Legette', 'WR', 210.8::numeric, false),
    ('Ollie Gordon II', 'RB', 220.4::numeric, false),
    ('Ray Davis', 'RB', 221.1::numeric, false),
    ('Tre Tucker', 'WR', 212.7::numeric, false),
    ('Michael Mayer', 'TE', 214.5::numeric, false),
    ('Keenan Allen', 'WR', 214.7::numeric, false),
    ('Jaylen Wright', 'RB', 225.4::numeric, false),
    ('Sean Tucker', 'RB', 226.8::numeric, false),
    ('Malik Washington', 'WR', 220.6::numeric, false),
    ('Ben Sinnott', 'TE', 211.2::numeric, false),
    ('Marquise Brown', 'WR', 222.6::numeric, false),
    ('Justin Fields', 'QB', 214.1::numeric, false),
    ('DeMario Douglas', 'WR', 226.8::numeric, false),
    ('Darius Slayton', 'WR', 229.2::numeric, false),
    ('Geno Smith', 'QB', 232.3::numeric, false),
    ('Devaughn Vele', 'WR', 232.8::numeric, false),
    ('Kendre Miller', 'RB', 239.7::numeric, false),
    ('Keaton Mitchell', 'RB', 240.1::numeric, false),
    ('Mac Jones', 'QB', 213.7::numeric, false),
    ('Demond Claiborne', 'RB', 252.2::numeric, true),
    ('Najee Harris', 'RB', 245.1::numeric, false),
    ('Jalen Royals', 'WR', 246.6::numeric, false),
    ('Joe Mixon', 'RB', 238.4::numeric, false),
    ('Isaiah Bond', 'WR', 247.0::numeric, false),
    ('Skyler Bell', 'WR', 254.8::numeric, true),
    ('Gunnar Helm', 'TE', 194.0::numeric, false),
    ('Jaydon Blue', 'RB', 251.7::numeric, false),
    ('Brashard Smith', 'RB', 254.3::numeric, false),
    ('Joshua Palmer', 'WR', 241.5::numeric, false),
    ('Chris Rodriguez Jr.', 'RB', 253.3::numeric, false),
    ('Isaiah Davis', 'RB', 261.4::numeric, false),
    ('Andrei Iosivas', 'WR', 247.1::numeric, false),
    ('Roman Wilson', 'WR', 255.7::numeric, false),
    ('Cole Kmet', 'TE', 241.1::numeric, false),
    ('Adam Randall', 'RB', 275.4::numeric, true),
    ('Roman Hemby', 'RB', 276.5::numeric, true),
    ('Ryan Flournoy', 'WR', 235.1::numeric, false),
    ('Emanuel Wilson', 'RB', 254.8::numeric, false),
    ('DJ Giddens', 'RB', 271.1::numeric, false),
    ('Aaron Rodgers', 'QB', 237.0::numeric, false),
    ('Ja''Tavion Sanders', 'TE', 248.9::numeric, false),
    ('Jarquez Hunter', 'RB', 283.6::numeric, false),
    ('Jonnu Smith', 'TE', 261.7::numeric, false),
    ('Colby Parkinson', 'TE', 230.0::numeric, false),
    ('Dont''e Thornton Jr.', 'WR', 252.9::numeric, false),
    ('Calvin Austin III', 'WR', 263.1::numeric, false),
    ('Isaac Guerendo', 'RB', 285.3::numeric, false),
    ('Jordan Whittington', 'WR', 276.1::numeric, false),
    ('Jacoby Brissett', 'QB', 227.8::numeric, false),
    ('Jaylin Lane', 'WR', 273.5::numeric, false),
    ('Luke McCaffrey', 'WR', 265.3::numeric, false),
    ('Will Shipley', 'RB', 289.3::numeric, false),
    ('Jalen Milroe', 'QB', 248.5::numeric, false),
    ('Kareem Hunt', 'RB', 277.3::numeric, false),
    ('Jake Tonges', 'TE', 236.3::numeric, false),
    ('Nick Chubb', 'RB', 279.0::numeric, false),
    ('Audric Estime', 'RB', 273.8::numeric, false),
    ('Mike Gesicki', 'TE', 254.8::numeric, false),
    ('Kirk Cousins', 'QB', 246.9::numeric, false),
    ('John Metchie III', 'WR', 260.0::numeric, false),
    ('Devin Singletary', 'RB', 279.1::numeric, false),
    ('Jerome Ford', 'RB', 287.1::numeric, false),
    ('Trevor Etienne', 'RB', 294.3::numeric, false),
    ('Tahj Brooks', 'RB', 300.4::numeric, false),
    ('Darnell Washington', 'TE', 253.9::numeric, false),
    ('Denver Broncos', 'D/ST', 231.1::numeric, false),
    ('Jameis Winston', 'QB', 261.0::numeric, false),
    ('Marcus Mariota', 'QB', 263.3::numeric, false),
    ('Philadelphia Eagles', 'D/ST', 239.6::numeric, false),
    ('Jalen Nailor', 'WR', 277.1::numeric, false),
    ('Jordan James', 'RB', 300.6::numeric, false),
    ('Savion Williams', 'WR', 281.5::numeric, false),
    ('MarShawn Lloyd', 'RB', 297.9::numeric, false),
    ('Noah Gray', 'TE', 276.9::numeric, false),
    ('Jaleel McLaughlin', 'RB', 302.1::numeric, false),
    ('Quinn Ewers', 'QB', 270.4::numeric, false),
    ('Jalen Tolbert', 'WR', 272.2::numeric, false),
    ('Brandon Aubrey', 'K', 245.3::numeric, false),
    ('Houston Texans', 'D/ST', 247.6::numeric, false),
    ('Pittsburgh Steelers', 'D/ST', 263.3::numeric, false),
    ('Justice Hill', 'RB', 303.6::numeric, false),
    ('Michael Carter', 'RB', 297.0::numeric, false),
    ('DeAndre Hopkins', 'WR', 266.6::numeric, false),
    ('Cam Little', 'K', 256.2::numeric, false),
    ('KeAndre Lambert-Smith', 'WR', 283.4::numeric, false),
    ('Minnesota Vikings', 'D/ST', 272.7::numeric, false),
    ('Harrison Butker', 'K', 261.2::numeric, false),
    ('Spencer Rattler', 'QB', 275.2::numeric, false),
    ('Kansas City Chiefs', 'D/ST', 276.3::numeric, false),
    ('Los Angeles Rams', 'D/ST', 264.0::numeric, false),
    ('Will Reichard', 'K', 247.5::numeric, false),
    ('Bam Knight', 'RB', 290.9::numeric, false),
    ('Roschon Johnson', 'RB', 291.6::numeric, false),
    ('Elijah Moore', 'WR', 268.4::numeric, true),
    ('Detroit Lions', 'D/ST', 268.9::numeric, false),
    ('Buffalo Bills', 'D/ST', 269.6::numeric, false),
    ('LeQuint Allen Jr.', 'RB', 304.3::numeric, false),
    ('Cameron Dicker', 'K', 274.0::numeric, false),
    ('Wil Lutz', 'K', 275.7::numeric, false),
    ('Darren Waller', 'TE', 276.1::numeric, false),
    ('Baltimore Ravens', 'D/ST', 290.7::numeric, false),
    ('Chris Boswell', 'K', 279.3::numeric, false),
    ('Jake Moody', 'K', 265.5::numeric, false),
    ('Xavier Restrepo', 'WR', 281.4::numeric, false),
    ('Luke Musgrave', 'TE', 294.6::numeric, false),
    ('Ty Johnson', 'RB', 312.4::numeric, false),
    ('Russell Wilson', 'QB', 268.8::numeric, false),
    ('New England Patriots', 'D/ST', 284.7::numeric, false),
    ('Tyler Lockett', 'WR', 270.4::numeric, false),
    ('Max Klare', 'TE', 141.0::numeric, true),
    ('Will Levis', 'QB', 286.8::numeric, false),
    ('Joshua Karty', 'K', 273.1::numeric, false),
    ('Noah Fant', 'TE', 299.6::numeric, false),
    ('Seattle Seahawks', 'D/ST', 278.4::numeric, false),
    ('Los Angeles Chargers', 'D/ST', 292.4::numeric, false),
    ('Brandon McManus', 'K', 279.0::numeric, false),
    ('Konata Mumpfield', 'WR', 261.7::numeric, false),
    ('Ka''imi Fairbairn', 'K', 279.1::numeric, false),
    ('Trey Lance', 'QB', 304.5::numeric, false),
    ('Will Howard', 'QB', 281.0::numeric, false),
    ('Dawson Knox', 'TE', 294.7::numeric, false),
    ('Evan McPherson', 'K', 295.9::numeric, false),
    ('Blake Grupe', 'K', 282.9::numeric, false),
    ('Washington Commanders', 'D/ST', 296.8::numeric, false),
    ('Joe Flacco', 'QB', 285.9::numeric, false),
    ('Jack Endries', 'TE', 217.6::numeric, true),
    ('Green Bay Packers', 'D/ST', 299.1::numeric, false),
    ('Greg Dulcich', 'TE', 287.6::numeric, false),
    ('Joe Milton III', 'QB', 288.6::numeric, false),
    ('Zach Ertz', 'TE', 273.0::numeric, false),
    ('Dillon Gabriel', 'QB', 290.6::numeric, false),
    ('Ted Hurst', 'WR', 181.5::numeric, true),
    ('Mack Hollins', 'WR', 292.6::numeric, false),
    ('Tyquan Thornton', 'WR', 280.7::numeric, false),
    ('Chase McLaughlin', 'K', 295.8::numeric, false),
    ('Tyler Higbee', 'TE', 307.7::numeric, false),
    ('Tyler Bass', 'K', 298.8::numeric, false),
    ('Austin Ekeler', 'RB', 310.4::numeric, false),
    ('Samaje Perine', 'RB', 301.8::numeric, false),
    ('Davis Mills', 'QB', 288.1::numeric, false),
    ('Deshaun Watson', 'QB', 302.3::numeric, false),
    ('Ja''Lynn Polk', 'WR', 250.4::numeric, false),
    ('Miles Sanders', 'RB', 308.8::numeric, false),
    ('Demarcus Robinson', 'WR', 295.9::numeric, false),
    ('Cleveland Browns', 'D/ST', 309.0::numeric, false),
    ('Jacksonville Jaguars', 'D/ST', 284.2::numeric, false),
    ('Jake Bates', 'K', 301.3::numeric, false),
    ('Antonio Gibson', 'RB', 315.0::numeric, false),
    ('Cade Stover', 'TE', 333.3::numeric, false),
    ('Phil Mafah', 'RB', 266.4::numeric, false),
    ('Brandin Cooks', 'WR', 306.6::numeric, false),
    ('Riley Leonard', 'QB', 307.0::numeric, false),
    ('Jake Elliott', 'K', 308.4::numeric, false),
    ('Kenny Pickett', 'QB', 310.1::numeric, false),
    ('Raheim Sanders', 'RB', 322.1::numeric, false),
    ('Taysom Hill', 'TE', 277.4::numeric, false),
    ('Kevin Coleman Jr.', 'WR', 206.7::numeric, true),
    ('Gabe Davis', 'WR', 304.5::numeric, false),
    ('Jawhar Jordan', 'RB', 256.8::numeric, false),
    ('Tai Felton', 'WR', 319.0::numeric, false),
    ('Eric McAlister', 'WR', 211.3::numeric, true),
    ('Gardner Minshew II', 'QB', 288.0::numeric, false),
    ('Chris Brooks', 'RB', 307.3::numeric, false),
    ('Emari Demercado', 'RB', 261.0::numeric, false),
    ('Jermaine Burton', 'WR', 289.2::numeric, true),
    ('Mason Rudolph', 'QB', 308.0::numeric, false),
    ('Garrett Nussmeier', 'QB', 262.0::numeric, true),
    ('Diontae Johnson', 'WR', 217.7::numeric, true),
    ('Jason Myers', 'K', 310.7::numeric, false),
    ('Tyren Montgomery', 'WR', 220.7::numeric, true),
    ('Deion Burks', 'WR', 222.0::numeric, true),
    ('Rasheen Ali', 'RB', 294.8::numeric, false),
    ('Tutu Atwell', 'WR', 312.5::numeric, false),
    ('Aidan O''Connell', 'QB', 298.8::numeric, false),
    ('Tanner McKee', 'QB', 317.0::numeric, false),
    ('Malik Davis', 'RB', 233.7::numeric, false),
    ('Tanner Koziol', 'TE', 234.0::numeric, true),
    ('Justin Joly', 'TE', 235.3::numeric, true),
    ('Kendrick Bourne', 'WR', 302.2::numeric, false),
    ('Tyrod Taylor', 'QB', 318.7::numeric, false),
    ('Arizona Cardinals', 'D/ST', 280.3::numeric, false),
    ('Nick Westbrook-Ikhine', 'WR', 307.6::numeric, true),
    ('Erick All Jr.', 'TE', 323.2::numeric, false),
    ('Le''Veon Moss', 'RB', 284.5::numeric, true),
    ('Treylon Burks', 'WR', 309.2::numeric, false),
    ('Malachi Corley', 'WR', 310.6::numeric, false),
    ('Efton Chism III', 'WR', 311.4::numeric, false),
    ('Jake Browning', 'QB', 315.6::numeric, false),
    ('Jahan Dotson', 'WR', 331.5::numeric, false),
    ('Jared Wiley', 'TE', 299.0::numeric, false),
    ('Carson Wentz', 'QB', 319.4::numeric, false),
    ('Dameon Pierce', 'RB', 299.8::numeric, false),
    ('Jimmy Horn Jr.', 'WR', 335.8::numeric, false),
    ('Jeremy McNichols', 'RB', 271.3::numeric, false),
    ('Dyami Brown', 'WR', 325.2::numeric, false),
    ('Greg Dortch', 'WR', 307.3::numeric, false),
    ('Xavier Hutchinson', 'WR', 327.4::numeric, false),
    ('Thomas Fidone II', 'TE', 328.4::numeric, false),
    ('Bryce Lance', 'WR', 220.0::numeric, true),
    ('KaVontae Turpin', 'WR', 328.6::numeric, false),
    ('Brenen Thompson', 'WR', 282.0::numeric, true),
    ('Tyler Loop', 'K', 282.0::numeric, false),
    ('Tyrell Shavers', 'WR', 287.7::numeric, false),
    ('Tommy Tremble', 'TE', 317.3::numeric, false),
    ('Jalin Hyatt', 'WR', 334.0::numeric, false),
    ('Zach Wilson', 'QB', 334.2::numeric, false),
    ('JuJu Smith-Schuster', 'WR', 290.3::numeric, false),
    ('Jarrett Stidham', 'QB', 334.8::numeric, false),
    ('Mitchell Evans', 'TE', 346.7::numeric, false),
    ('Austin Hooper', 'TE', 337.0::numeric, false),
    ('Damien Martinez', 'RB', 296.0::numeric, false),
    ('Khalil Herbert', 'RB', 296.7::numeric, false),
    ('Cole Payton', 'QB', 298.0::numeric, true),
    ('Tyler Huntley', 'QB', 301.7::numeric, false),
    ('Devontez Walker', 'WR', 341.6::numeric, false),
    ('Mitchell Trubisky', 'QB', 303.3::numeric, false),
    ('Jimmy Garoppolo', 'QB', 342.4::numeric, false),
    ('Curtis Samuel', 'WR', 328.0::numeric, false),
    ('Robert Henry Jr.', 'RB', 256.0::numeric, true),
    ('Noah Brown', 'WR', 329.0::numeric, false),
    ('Will Dissly', 'TE', 329.5::numeric, false),
    ('Javon Baker', 'WR', 259.0::numeric, true),
    ('Drew Allar', 'QB', 259.5::numeric, true),
    ('Josh Oliver', 'TE', 344.6::numeric, false),
    ('Theo Wease Jr.', 'WR', 265.5::numeric, false),
    ('Olamide Zaccheaus', 'WR', 347.2::numeric, false),
    ('Carson Beck', 'QB', 311.7::numeric, true),
    ('Seth McGowan', 'RB', 312.7::numeric, true),
    ('Zamir White', 'RB', 313.3::numeric, false),
    ('Matt Gay', 'K', 270.0::numeric, true),
    ('Philip Rivers', 'QB', 270.0::numeric, false),
    ('Elijah Higgins', 'TE', 348.8::numeric, false),
    ('Joe Royer', 'TE', 271.5::numeric, true),
    ('Kevin Austin Jr.', 'WR', 273.5::numeric, false),
    ('Brady Cook', 'QB', 273.5::numeric, false),
    ('Raheem Mostert', 'RB', 274.0::numeric, false),
    ('Darius Cooper', 'WR', 318.7::numeric, false),
    ('Tyler Conklin', 'TE', 341.3::numeric, false),
    ('Younghoe Koo', 'K', 282.0::numeric, true),
    ('Joshua Dobbs', 'QB', 341.8::numeric, false),
    ('J''Mari Taylor', 'RB', 325.3::numeric, true),
    ('Jahdae Walker', 'WR', 288.0::numeric, false),
    ('Tyson Bagent', 'QB', 344.5::numeric, false),
    ('Elijah Mitchell', 'RB', 288.5::numeric, false),
    ('New York Jets', 'D/ST', 291.0::numeric, false),
    ('Jam Miller', 'RB', 327.7::numeric, true),
    ('Davis Allen', 'TE', 358.0::numeric, false),
    ('Zack Moss', 'RB', 294.0::numeric, true),
    ('Aaron Anderson', 'WR', 295.5::numeric, true),
    ('Jordan Watkins', 'WR', 331.0::numeric, false),
    ('Tyler Badie', 'RB', 298.0::numeric, false),
    ('Ty Chandler', 'RB', 299.0::numeric, false),
    ('Miami Dolphins', 'D/ST', 300.5::numeric, false),
    ('Sterling Shepard', 'WR', 334.3::numeric, false),
    ('Brock Wright', 'TE', 353.0::numeric, false),
    ('New Orleans Saints', 'D/ST', 308.5::numeric, false),
    ('Isaiah Hodgins', 'WR', 308.5::numeric, false),
    ('Chicago Bears', 'D/ST', 312.5::numeric, false),
    ('George Holani', 'RB', 357.0::numeric, false),
    ('Daniel Bellinger', 'TE', 365.8::numeric, false),
    ('Isaiah Williams', 'WR', 316.5::numeric, false),
    ('Andy Dalton', 'QB', 317.5::numeric, false),
    ('Charlie Kolar', 'TE', 361.3::numeric, false),
    ('Josh Reynolds', 'WR', 330.5::numeric, false),
    ('Jason Sanders', 'K', 332.0::numeric, false),
    ('Jeremy Ruckert', 'TE', 366.5::numeric, false),
    ('Cam Akers', 'RB', 333.0::numeric, false),
    ('Alexander Mattison', 'RB', 333.5::numeric, false),
    ('Jaydn Ott', 'RB', 358.0::numeric, true),
    ('Jackson Hawes', 'TE', 360.3::numeric, false),
    ('Mitch Tinsley', 'WR', 365.0::numeric, false),
    ('Jacob Cowing', 'WR', 347.5::numeric, false),
    ('Sam Roush', 'TE', 351.0::numeric, true),
    ('Arian Smith', 'WR', 351.5::numeric, false),
    ('Hunter Long', 'TE', 369.0::numeric, false),
    ('Eli Raridon', 'TE', 358.0::numeric, true),
    ('David Sills V', 'WR', 361.0::numeric, false),
    ('Dallen Bentley', 'TE', 361.0::numeric, true),
    ('Sam Howell', 'QB', 381.8::numeric, false),
    ('John Bates', 'TE', 363.5::numeric, false),
    ('Marlin Klein', 'TE', 364.0::numeric, true),
    ('Kaelon Black', 'RB', 364.5::numeric, true),
    ('Oscar Delp', 'TE', 373.5::numeric, true)
),
aliases (input_name, db_name) AS (
  VALUES
    ('Patrick Mahomes II', 'Patrick Mahomes'),
    ('Deebo Samuel Sr.', 'Deebo Samuel'),
    ('Aaron Jones Sr.', 'Aaron Jones'),
    ('Anthony Richardson Sr.', 'Anthony Richardson'),
    ('Chris Godwin Jr.', 'Chris Godwin'),
    ('Brian Thomas Jr.', 'Brian Thomas'),
    ('Kyle Pitts Sr.', 'Kyle Pitts'),
    ('Michael Pittman Jr.', 'Michael Pittman'),
    ('Marvin Harrison Jr.', 'Marvin Harrison'),
    ('Ollie Gordon II', 'Ollie Gordon'),
    ('Chris Rodriguez Jr.', 'Chris Rodriguez'),
    ('Jonathon Brooks', 'Jonathan Brooks'),
    ('Travis Etienne Jr.', 'Travis Etienne'),
    ('Michael Penix Jr.', 'Michael Penix'),
    ('Thomas Fidone II', 'Thomas Fidone'),
    ('Erick All Jr.', 'Erick All')
),
lookup AS (
  SELECT
    p.input_name,
    p.position,
    p.avg_rank,
    p.is_fa,
    COALESCE(a.db_name, p.input_name) AS match_name
  FROM parsed p
  LEFT JOIN aliases a ON a.input_name = p.input_name
),

ins_baseline AS (
  INSERT INTO public.baseline_community_rankings (scoring_format, league_type, is_superflex, player_id, rank)
  SELECT
    'ppr'::text,
    'dynasty'::text,
    false,
    pl.id,
    l.avg_rank
  FROM lookup l
  INNER JOIN public.players pl ON pl.name = l.match_name AND pl.season = 2025
  ON CONFLICT (scoring_format, league_type, is_superflex, player_id)
  DO UPDATE SET rank = EXCLUDED.rank
)

INSERT INTO public.baseline_rookies (name, position, rank, scoring_format, league_type, is_superflex)
SELECT l.input_name, l.position, l.avg_rank, 'ppr'::text, 'dynasty'::text, false
FROM lookup l
WHERE l.is_fa = true
  AND NOT EXISTS (
    SELECT 1 FROM public.players p
    WHERE (p.name = l.match_name OR p.name = l.input_name) AND p.season = 2025
  )
  AND NOT EXISTS (
    SELECT 1 FROM public.baseline_rookies br
    WHERE br.name = l.input_name
      AND br.scoring_format = 'ppr'
      AND br.league_type = 'dynasty'
      AND br.is_superflex = false
  )
ON CONFLICT (scoring_format, league_type, is_superflex, name) DO NOTHING;
