-- Standard / dynasty / non-superflex baseline rankings
-- Inserts into baseline_community_rankings (matches players by name, season=2025)
-- Adds FA rookies to baseline_rookies if not in players or already in baseline_rookies

WITH parsed (input_name, position, avg_rank, is_fa) AS (
  VALUES
    ('Bijan Robinson', 'RB', 1::numeric, false),
    ('Jahmyr Gibbs', 'RB', 2::numeric, false),
    ('Ja''Marr Chase', 'WR', 3::numeric, false),
    ('Jaxon Smith-Njigba', 'WR', 4::numeric, false),
    ('Puka Nacua', 'WR', 5::numeric, false),
    ('Malik Nabers', 'WR', 6::numeric, false),
    ('Amon-Ra St. Brown', 'WR', 7::numeric, false),
    ('Ashton Jeanty', 'RB', 8::numeric, false),
    ('Justin Jefferson', 'WR', 9::numeric, false),
    ('De''Von Achane', 'RB', 11::numeric, false),
    ('Brock Bowers', 'TE', 12::numeric, false),
    ('Jeremiyah Love', 'RB', 13::numeric, true),
    ('CeeDee Lamb', 'WR', 14::numeric, false),
    ('Trey McBride', 'TE', 15::numeric, false),
    ('Omarion Hampton', 'RB', 16::numeric, false),
    ('Drake London', 'WR', 17::numeric, false),
    ('Jonathan Taylor', 'RB', 18::numeric, false),
    ('Josh Allen', 'QB', 19::numeric, false),
    ('James Cook', 'RB', 20::numeric, false),
    ('Drake Maye', 'QB', 21::numeric, false),
    ('Tetairoa McMillan', 'WR', 22::numeric, false),
    ('George Pickens', 'WR', 23::numeric, false),
    ('Nico Collins', 'WR', 24::numeric, false),
    ('Bucky Irving', 'RB', 25::numeric, false),
    ('TreVeyon Henderson', 'RB', 27::numeric, false),
    ('Christian McCaffrey', 'RB', 28::numeric, false),
    ('Makai Lemon', 'WR', 29::numeric, true),
    ('Carnell Tate', 'WR', 30::numeric, true),
    ('Breece Hall', 'RB', 31::numeric, false),
    ('Colston Loveland', 'TE', 32::numeric, false),
    ('Garrett Wilson', 'WR', 33::numeric, false),
    ('Chris Olave', 'WR', 34::numeric, false),
    ('Emeka Egbuka', 'WR', 35::numeric, false),
    ('Quinshon Judkins', 'RB', 37::numeric, false),
    ('Chase Brown', 'RB', 38::numeric, false),
    ('Lamar Jackson', 'QB', 39::numeric, false),
    ('Saquon Barkley', 'RB', 40::numeric, false),
    ('Jayden Daniels', 'QB', 41::numeric, false),
    ('Tyler Warren', 'TE', 42::numeric, false),
    ('Kyren Williams', 'RB', 43::numeric, false),
    ('Ladd McConkey', 'WR', 44::numeric, false),
    ('Rashee Rice', 'WR', 46::numeric, false),
    ('Marvin Harrison Jr', 'WR', 47::numeric, false),
    ('Joe Burrow', 'QB', 48::numeric, false),
    ('Jordyn Tyson', 'WR', 49::numeric, true),
    ('Caleb Williams', 'QB', 50::numeric, false),
    ('Kenneth Walker', 'RB', 51::numeric, false),
    ('Brian Thomas', 'WR', 52::numeric, false),
    ('Josh Jacobs', 'RB', 53::numeric, false),
    ('Rome Odunze', 'WR', 54::numeric, false),
    ('Cam Skattebo', 'RB', 55::numeric, false),
    ('A.J. Brown', 'WR', 56::numeric, false),
    ('Tee Higgins', 'WR', 57::numeric, false),
    ('Justin Herbert', 'QB', 58::numeric, false),
    ('Zay Flowers', 'WR', 59::numeric, false),
    ('Jonah Coleman', 'RB', 60::numeric, true),
    ('Jalen Hurts', 'QB', 61::numeric, false),
    ('Patrick Mahomes', 'QB', 63::numeric, false),
    ('Luther Burden', 'WR', 64::numeric, false),
    ('Jameson Williams', 'WR', 65::numeric, false),
    ('Denzel Boston', 'WR', 66::numeric, true),
    ('RJ Harvey', 'RB', 67::numeric, false),
    ('Travis Etienne', 'RB', 68::numeric, false),
    ('Harold Fannin', 'TE', 69::numeric, false),
    ('Jaxson Dart', 'QB', 71::numeric, false),
    ('Tucker Kraft', 'TE', 72::numeric, false),
    ('DeVonta Smith', 'WR', 73::numeric, false),
    ('Javonte Williams', 'RB', 74::numeric, false),
    ('Derrick Henry', 'RB', 75::numeric, false),
    ('Jaylen Waddle', 'WR', 76::numeric, false),
    ('Sam LaPorta', 'TE', 80::numeric, false),
    ('Bo Nix', 'QB', 81::numeric, false),
    ('Trevor Lawrence', 'QB', 82::numeric, false),
    ('KC Concepcion', 'WR', 83::numeric, true),
    ('Kyle Pitts', 'TE', 84::numeric, false),
    ('Brock Purdy', 'QB', 86::numeric, false),
    ('Kenyon Sadiq', 'TE', 87::numeric, true),
    ('Jadarian Price', 'RB', 88::numeric, true),
    ('D''Andre Swift', 'RB', 90::numeric, false),
    ('Travis Hunter', 'WR', 91::numeric, false),
    ('Emmett Johnson', 'RB', 92::numeric, true),
    ('Jordan Love', 'QB', 93::numeric, false),
    ('Oronde Gadsden', 'TE', 95::numeric, false),
    ('Fernando Mendoza', 'QB', 96::numeric, true),
    ('Jordan Addison', 'WR', 97::numeric, false),
    ('DK Metcalf', 'WR', 99::numeric, false),
    ('Ricky Pearsall', 'WR', 100::numeric, false),
    ('Nicholas Singleton', 'RB', 101::numeric, true),
    ('Michael Pittman', 'WR', 102::numeric, false),
    ('Terry McLaurin', 'WR', 103::numeric, false),
    ('Dak Prescott', 'QB', 104::numeric, false),
    ('Davante Adams', 'WR', 105::numeric, false),
    ('Alec Pierce', 'WR', 106::numeric, false),
    ('Michael Wilson', 'WR', 108::numeric, false),
    ('Bhayshul Tuten', 'RB', 109::numeric, false),
    ('Kyle Monangai', 'RB', 110::numeric, false),
    ('Matthew Golden', 'WR', 111::numeric, false),
    ('Jaylen Warren', 'RB', 112::numeric, false),
    ('Jayden Higgins', 'WR', 114::numeric, false),
    ('Zach Charbonnet', 'RB', 115::numeric, false),
    ('George Kittle', 'TE', 116::numeric, false),
    ('Tyler Allgeier', 'RB', 117::numeric, false),
    ('Baker Mayfield', 'QB', 118::numeric, false),
    ('Cam Ward', 'QB', 119::numeric, false),
    ('Xavier Worthy', 'WR', 120::numeric, false),
    ('Parker Washington', 'WR', 121::numeric, false),
    ('Wan''Dale Robinson', 'WR', 122::numeric, false),
    ('Christian Watson', 'WR', 123::numeric, false),
    ('Dalton Kincaid', 'TE', 124::numeric, false),
    ('Jake Ferguson', 'TE', 125::numeric, false),
    ('Chuba Hubbard', 'RB', 126::numeric, false),
    ('Eli Stowers', 'TE', 127::numeric, true),
    ('Trey Benson', 'RB', 128::numeric, false),
    ('Quentin Johnston', 'WR', 130::numeric, false),
    ('C.J. Stroud', 'QB', 131::numeric, false),
    ('Rico Dowdle', 'RB', 132::numeric, false),
    ('Courtland Sutton', 'WR', 133::numeric, false),
    ('Jared Goff', 'QB', 134::numeric, false),
    ('Blake Corum', 'RB', 135::numeric, false),
    ('Mike Evans', 'WR', 136::numeric, false),
    ('David Montgomery', 'RB', 138::numeric, false),
    ('Jakobi Meyers', 'WR', 139::numeric, false),
    ('DJ Moore', 'WR', 140::numeric, false),
    ('Rhamondre Stevenson', 'RB', 141::numeric, false),
    ('Mike Washington', 'RB', 142::numeric, true),
    ('Omar Cooper', 'WR', 143::numeric, true),
    ('Woody Marks', 'RB', 144::numeric, false),
    ('Jonathon Brooks', 'RB', 145::numeric, false),
    ('Zachariah Branch', 'WR', 147::numeric, true),
    ('Kenneth Gainwell', 'RB', 148::numeric, false),
    ('Tyrone Tracy', 'RB', 149::numeric, false),
    ('Sam Darnold', 'QB', 150::numeric, false),
    ('Jayden Reed', 'WR', 151::numeric, false),
    ('Kaleb Johnson', 'RB', 152::numeric, false),
    ('Demond Claiborne', 'RB', 153::numeric, true),
    ('Khalil Shakir', 'WR', 154::numeric, false),
    ('J.K. Dobbins', 'RB', 155::numeric, false),
    ('Brandon Aiyuk', 'WR', 156::numeric, false),
    ('Chris Bell', 'WR', 157::numeric, true),
    ('Elijah Sarratt', 'WR', 159::numeric, true),
    ('Josh Downs', 'WR', 160::numeric, false),
    ('Tyreek Hill', 'WR', 161::numeric, false),
    ('Chris Brazzell', 'WR', 162::numeric, true),
    ('Braelon Allen', 'RB', 163::numeric, false),
    ('Rachaad White', 'RB', 164::numeric, false),
    ('Brenton Strange', 'TE', 165::numeric, false),
    ('Jalen Coker', 'WR', 166::numeric, false),
    ('Jacory Croskey-Merritt', 'RB', 167::numeric, false),
    ('Jauan Jennings', 'WR', 168::numeric, false),
    ('Alvin Kamara', 'RB', 169::numeric, false),
    ('Chris Godwin', 'WR', 170::numeric, false),
    ('Tyler Shough', 'QB', 171::numeric, false),
    ('Bryce Young', 'QB', 173::numeric, false),
    ('Romeo Doubs', 'WR', 174::numeric, false),
    ('Tyjae Spears', 'RB', 176::numeric, false),
    ('Germie Bernard', 'WR', 177::numeric, true),
    ('Stefon Diggs', 'WR', 178::numeric, false),
    ('Troy Franklin', 'WR', 179::numeric, false),
    ('Isaiah Likely', 'TE', 180::numeric, false),
    ('Kayshon Boutte', 'WR', 181::numeric, false),
    ('Tony Pollard', 'RB', 182::numeric, false),
    ('Tre'' Harris', 'WR', 184::numeric, false),
    ('Pat Bryant', 'WR', 185::numeric, false),
    ('Theo Johnson', 'TE', 186::numeric, false),
    ('Ja''Kobi Lane', 'WR', 187::numeric, true),
    ('Kyler Murray', 'QB', 189::numeric, false),
    ('Deebo Samuel', 'WR', 190::numeric, false),
    ('Keon Coleman', 'WR', 192::numeric, false),
    ('Jerry Jeudy', 'WR', 193::numeric, false),
    ('Devin Neal', 'RB', 195::numeric, false),
    ('Mason Taylor', 'TE', 196::numeric, false),
    ('Antonio Williams', 'WR', 197::numeric, true),
    ('Le''Veon Moss', 'RB', 198::numeric, true),
    ('Elic Ayomanor', 'WR', 199::numeric, false),
    ('Dylan Sampson', 'RB', 200::numeric, false),
    ('Malachi Fields', 'WR', 201::numeric, true),
    ('Terrance Ferguson', 'TE', 202::numeric, false),
    ('David Njoku', 'TE', 203::numeric, false),
    ('Chimere Dike', 'WR', 204::numeric, false),
    ('Jordan Mason', 'RB', 205::numeric, false),
    ('Adam Randall', 'RB', 206::numeric, true),
    ('Matthew Stafford', 'QB', 207::numeric, false),
    ('AJ Barner', 'TE', 209::numeric, false),
    ('Kimani Vidal', 'RB', 210::numeric, false),
    ('T.J. Hockenson', 'TE', 211::numeric, false),
    ('Jalen McMillan', 'WR', 212::numeric, false),
    ('Daniel Jones', 'QB', 213::numeric, false),
    ('Isaac TeSlaa', 'WR', 214::numeric, false),
    ('Max Klare', 'TE', 215::numeric, true),
    ('Rashid Shaheed', 'WR', 216::numeric, false),
    ('Juwan Johnson', 'TE', 218::numeric, false),
    ('Mark Andrews', 'TE', 219::numeric, false),
    ('J''Mari Taylor', 'RB', 220::numeric, true),
    ('Tory Horton', 'WR', 221::numeric, false),
    ('Dallas Goedert', 'TE', 222::numeric, false),
    ('Adonai Mitchell', 'WR', 223::numeric, false),
    ('Jaylin Noel', 'WR', 225::numeric, false),
    ('J.J. McCarthy', 'QB', 226::numeric, false),
    ('Ollie Gordon', 'RB', 228::numeric, false),
    ('Kyle Williams', 'WR', 229::numeric, false),
    ('Eric McAlister', 'WR', 231::numeric, true),
    ('CJ Daniels', 'WR', 232::numeric, true),
    ('Michael Penix', 'QB', 233::numeric, false),
    ('Tank Dell', 'WR', 234::numeric, false),
    ('Malik Willis', 'QB', 235::numeric, false),
    ('Ted Hurst', 'WR', 237::numeric, true),
    ('Joe Mixon', 'RB', 238::numeric, false),
    ('Sean Tucker', 'RB', 239::numeric, false),
    ('Deion Burks', 'WR', 240::numeric, true),
    ('Isiah Pacheco', 'RB', 242::numeric, false),
    ('Jack Bech', 'WR', 243::numeric, false),
    ('Gunnar Helm', 'TE', 244::numeric, false),
    ('Tank Bigsby', 'RB', 245::numeric, false),
    ('Brenen Thompson', 'WR', 246::numeric, true),
    ('Aaron Jones', 'RB', 247::numeric, false),
    ('Jack Endries', 'TE', 248::numeric, true),
    ('Ty Simpson', 'QB', 249::numeric, true),
    ('James Conner', 'RB', 252::numeric, false),
    ('CJ Donaldson', 'RB', 253::numeric, true),
    ('Shedeur Sanders', 'QB', 256::numeric, false),
    ('Brian Robinson', 'RB', 258::numeric, false),
    ('Travis Kelce', 'TE', 262::numeric, false),
    ('Hunter Henry', 'TE', 263::numeric, false),
    ('Brashard Smith', 'RB', 264::numeric, false),
    ('Oscar Delp', 'TE', 265::numeric, true),
    ('Jake Tonges', 'TE', 266::numeric, false),
    ('Tre Tucker', 'WR', 267::numeric, false),
    ('Tua Tagovailoa', 'QB', 268::numeric, false),
    ('Jaydon Blue', 'RB', 270::numeric, false),
    ('Isaiah Bond', 'WR', 271::numeric, false),
    ('Mac Jones', 'QB', 275::numeric, false),
    ('Kevin Coleman', 'WR', 276::numeric, true),
    ('Colby Parkinson', 'TE', 278::numeric, false),
    ('Dalton Schultz', 'TE', 280::numeric, false),
    ('Ben Sinnott', 'TE', 284::numeric, false),
    ('Cade Otton', 'TE', 285::numeric, false),
    ('Noah Thomas', 'WR', 286::numeric, true),
    ('Marlin Klein', 'TE', 287::numeric, true),
    ('Jaylen Wright', 'RB', 288::numeric, false),
    ('Tez Johnson', 'WR', 289::numeric, false),
    ('Marvin Mims', 'WR', 290::numeric, false),
    ('Najee Harris', 'RB', 291::numeric, false),
    ('Hollywood Smothers', 'RB', 293::numeric, true),
    ('Anthony Richardson', 'QB', 294::numeric, false),
    ('Emanuel Wilson', 'RB', 295::numeric, false),
    ('Elijah Arroyo', 'TE', 296::numeric, false),
    ('Josh Cameron', 'WR', 298::numeric, true),
    ('Carson Beck', 'QB', 299::numeric, true),
    ('Dylan Devezin', 'RB', 301::numeric, true),
    ('Keaton Mitchell', 'RB', 302::numeric, false),
    ('Dane Key', 'WR', 304::numeric, true),
    ('Dont''e Thornton', 'WR', 305::numeric, false),
    ('Xavier Legette', 'WR', 308::numeric, false),
    ('Aaron Anderson', 'WR', 312::numeric, true),
    ('Evan Engram', 'TE', 315::numeric, false),
    ('Pat Freiermuth', 'TE', 316::numeric, false),
    ('Michael Mayer', 'TE', 317::numeric, false),
    ('Malik Washington', 'WR', 318::numeric, false),
    ('Kendre Miller', 'RB', 319::numeric, false),
    ('Chris Rodriguez', 'RB', 320::numeric, false),
    ('Keenan Allen', 'WR', 321::numeric, false),
    ('Jacoby Brissett', 'QB', 322::numeric, false),
    ('DJ Giddens', 'RB', 323::numeric, false),
    ('Calvin Ridley', 'WR', 324::numeric, false),
    ('Isaiah Davis', 'RB', 325::numeric, false),
    ('Chig Okonkwo', 'TE', 326::numeric, false),
    ('Devaughn Vele', 'WR', 327::numeric, false),
    ('Audric Estime', 'RB', 328::numeric, false),
    ('Cooper Kupp', 'WR', 329::numeric, false),
    ('Drew Allar', 'QB', 330::numeric, true),
    ('Cole Kmet', 'TE', 331::numeric, false),
    ('Aaron Rodgers', 'QB', 332::numeric, false),
    ('Justin Fields', 'QB', 333::numeric, false),
    ('Cedric Tillman', 'WR', 334::numeric, false),
    ('Ja''Tavion Sanders', 'TE', 335::numeric, false),
    ('Darren Waller', 'TE', 336::numeric, false),
    ('Rashod Bateman', 'WR', 337::numeric, false),
    ('Kirk Cousins', 'QB', 338::numeric, false),
    ('Kareem Hunt', 'RB', 339::numeric, false),
    ('Dontayvion Wicks', 'WR', 340::numeric, false),
    ('Ryan Flournoy', 'WR', 341::numeric, false),
    ('Taylen Green', 'QB', 342::numeric, true),
    ('Jalen Milroe', 'QB', 343::numeric, false),
    ('Darnell Mooney', 'WR', 344::numeric, false),
    ('Ray Davis', 'RB', 345::numeric, false),
    ('Devin Singletary', 'RB', 346::numeric, false),
    ('John Metchie', 'WR', 347::numeric, false),
    ('Zach Ertz', 'TE', 348::numeric, false),
    ('Will Howard', 'QB', 349::numeric, false),
    ('Tahj Brooks', 'RB', 350::numeric, false),
    ('DeMario Douglas', 'WR', 351::numeric, false),
    ('Jordan James', 'RB', 352::numeric, false),
    ('Cade Klubnik', 'QB', 353::numeric, true),
    ('Riley Leonard', 'QB', 354::numeric, false),
    ('Joe Fagnano', 'QB', 355::numeric, true),
    ('Trevor Etienne', 'RB', 356::numeric, false),
    ('Quinn Ewers', 'QB', 357::numeric, false),
    ('Jalen Royals', 'WR', 358::numeric, false),
    ('Christian Kirk', 'WR', 359::numeric, false),
    ('Marquise Brown', 'WR', 360::numeric, false),
    ('Geno Smith', 'QB', 361::numeric, false),
    ('Zonovan Knight', 'RB', 362::numeric, false),
    ('LeQuint Allen', 'RB', 363::numeric, false),
    ('Jaylin Lane', 'WR', 364::numeric, false),
    ('Michael Carter', 'RB', 365::numeric, false),
    ('Roman Wilson', 'WR', 366::numeric, false),
    ('Darius Slayton', 'WR', 367::numeric, false),
    ('Jalen Nailor', 'WR', 368::numeric, false),
    ('Luke McCaffrey', 'WR', 369::numeric, false),
    ('Darnell Washington', 'TE', 370::numeric, false),
    ('MarShawn Lloyd', 'RB', 371::numeric, false),
    ('Deshaun Watson', 'QB', 372::numeric, false),
    ('Nick Chubb', 'RB', 373::numeric, false),
    ('Ja''Lynn Polk', 'WR', 374::numeric, false),
    ('Jarquez Hunter', 'RB', 375::numeric, false),
    ('Marcus Mariota', 'QB', 376::numeric, false),
    ('KeAndre Lambert-Smith', 'WR', 377::numeric, false),
    ('Luke Musgrave', 'TE', 378::numeric, false),
    ('Dillon Gabriel', 'QB', 379::numeric, false),
    ('Noah Gray', 'TE', 380::numeric, false),
    ('Jonnu Smith', 'TE', 381::numeric, false),
    ('Andrei Iosivas', 'WR', 382::numeric, false),
    ('Savion Williams', 'WR', 383::numeric, false),
    ('Dawson Knox', 'TE', 384::numeric, false),
    ('Joe Milton', 'QB', 385::numeric, false),
    ('Calvin Austin', 'WR', 386::numeric, false),
    ('Jerome Ford', 'RB', 387::numeric, false),
    ('Mike Gesicki', 'TE', 388::numeric, false),
    ('Jameis Winston', 'QB', 389::numeric, false),
    ('Davis Mills', 'QB', 390::numeric, false),
    ('Isaac Guerendo', 'RB', 391::numeric, false),
    ('Jimmy Horn', 'WR', 392::numeric, false),
    ('Efton Chism', 'WR', 393::numeric, false),
    ('Spencer Rattler', 'QB', 394::numeric, false),
    ('Xavier Hutchinson', 'WR', 395::numeric, false),
    ('Will Levis', 'QB', 396::numeric, false),
    ('Justice Hill', 'RB', 397::numeric, false),
    ('Max Brosmer', 'QB', 398::numeric, false),
    ('Tyler Higbee', 'TE', 399::numeric, false),
    ('Joe Flacco', 'QB', 400::numeric, false),
    ('Malik Davis', 'RB', 401::numeric, false),
    ('Greg Dulcich', 'TE', 402::numeric, false),
    ('Raheim Sanders', 'RB', 403::numeric, false),
    ('Mack Hollins', 'WR', 404::numeric, false),
    ('Trey Lance', 'QB', 405::numeric, false),
    ('Treylon Burks', 'WR', 406::numeric, false),
    ('Xavier Restrepo', 'WR', 407::numeric, false),
    ('Jawhar Jordan', 'RB', 408::numeric, false),
    ('Austin Ekeler', 'RB', 409::numeric, false),
    ('Samaje Perine', 'RB', 410::numeric, false),
    ('Ty Johnson', 'RB', 411::numeric, false),
    ('Noah Fant', 'TE', 412::numeric, false),
    ('Nathan Carter', 'RB', 413::numeric, false),
    ('Tyson Bagent', 'QB', 414::numeric, false),
    ('KaVontae Turpin', 'WR', 415::numeric, false),
    ('Jordan Whittington', 'WR', 416::numeric, false),
    ('Tyquan Thornton', 'WR', 417::numeric, false),
    ('Roschon Johnson', 'RB', 418::numeric, false),
    ('Will Shipley', 'RB', 419::numeric, false),
    ('Tanner McKee', 'QB', 420::numeric, false),
    ('Jahan Dotson', 'WR', 421::numeric, false),
    ('Konata Mumpfield', 'WR', 422::numeric, false),
    ('Tutu Atwell', 'WR', 423::numeric, false),
    ('Jahdae Walker', 'WR', 424::numeric, false),
    ('Phil Mafah', 'RB', 425::numeric, false),
    ('Jordan Watkins', 'WR', 426::numeric, false),
    ('Tai Felton', 'WR', 427::numeric, false),
    ('DeAndre Hopkins', 'WR', 428::numeric, false),
    ('Russell Wilson', 'QB', 429::numeric, false),
    ('Tyler Huntley', 'QB', 430::numeric, false),
    ('Erick All', 'TE', 431::numeric, false),
    ('Terrell Jennings', 'RB', 432::numeric, false),
    ('Joshua Palmer', 'WR', 433::numeric, false),
    ('Tyrod Taylor', 'QB', 434::numeric, false),
    ('Isaiah Williams', 'WR', 435::numeric, false),
    ('Mitchell Evans', 'TE', 436::numeric, false),
    ('Derek Carr', 'QB', 437::numeric, true),
    ('Jackson Hawes', 'TE', 438::numeric, false),
    ('Jimmy Garoppolo', 'QB', 439::numeric, false),
    ('Malachi Corley', 'WR', 440::numeric, false),
    ('Olamide Zaccheaus', 'WR', 441::numeric, false),
    ('Darius Cooper', 'WR', 442::numeric, false),
    ('Demarcus Robinson', 'WR', 443::numeric, false),
    ('Jarrett Stidham', 'QB', 444::numeric, false),
    ('Sam Howell', 'QB', 445::numeric, false),
    ('George Holani', 'RB', 446::numeric, false),
    ('Stetson Bennett', 'QB', 447::numeric, false)

),
aliases (input_name, db_name) AS (
  VALUES
    ('James Cook', 'James Cook III'),
    ('Marvin Harrison Jr', 'Marvin Harrison'),
    ('Harold Fannin', 'Harold Fannin Jr.'),
    ('Oronde Gadsden', 'Oronde Gadsden II'),
    ('Jonathon Brooks', 'Jonathan Brooks'),
    ('Travis Etienne', 'Travis Etienne Jr.'),
    ('Luther Burden', 'Luther Burden III'),
    ('Brian Thomas', 'Brian Thomas Jr.'),
    ('KC Concepcion', 'K.C. Concepcion'),
    ('Michael Pittman', 'Michael Pittman Jr.'),
    ('Brian Robinson', 'Brian Robinson Jr.'),
    ('LeQuint Allen', 'LeQuint Allen Jr.'),
    ('Dont''e Thornton', 'Dont''e Thornton Jr.'),
    ('Chris Rodriguez', 'Chris Rodriguez Jr.'),
    ('Ollie Gordon', 'Ollie Gordon II')
),
lookup AS (
  SELECT
    p.input_name,
    p.position,
    p.avg_rank,
    p.is_fa,
    COALESCE(a.db_name, p.input_name) AS match_name
  FROM parsed p
  LEFT JOIN aliases a ON a.input_name = p.input_name
),

ins_baseline AS (
  INSERT INTO public.baseline_community_rankings (scoring_format, league_type, is_superflex, player_id, rank)
  SELECT
    'standard'::text,
    'dynasty'::text,
    false,
    pl.id,
    l.avg_rank
  FROM lookup l
  INNER JOIN public.players pl ON pl.name = l.match_name AND pl.season = 2025
  ON CONFLICT (scoring_format, league_type, is_superflex, player_id)
  DO UPDATE SET rank = EXCLUDED.rank
)

INSERT INTO public.baseline_rookies (name, position, rank, scoring_format, league_type, is_superflex)
SELECT l.input_name, l.position, l.avg_rank, 'standard'::text, 'dynasty'::text, false
FROM lookup l
WHERE l.is_fa = true
  AND NOT EXISTS (
    SELECT 1 FROM public.players p
    WHERE (p.name = l.match_name OR p.name = l.input_name) AND p.season = 2025
  )
  AND NOT EXISTS (
    SELECT 1 FROM public.baseline_rookies br
    WHERE br.name = l.input_name
      AND br.scoring_format = 'standard'
      AND br.league_type = 'dynasty'
      AND br.is_superflex = false
  )
ON CONFLICT (scoring_format, league_type, is_superflex, name) DO NOTHING;
