-- PPR / dynasty / superflex baseline rankings
-- Inserts into baseline_community_rankings (matches players by name, season=2025)
-- Adds FA rookies to baseline_rookies if not in players or already in baseline_rookies

WITH parsed (input_name, position, avg_rank, is_fa) AS (
  VALUES
    ('Josh Allen', 'QB', 1.3::numeric, false),
    ('Drake Maye', 'QB', 2.4::numeric, false),
    ('Jayden Daniels', 'QB', 5.5::numeric, false),
    ('Joe Burrow', 'QB', 6.5::numeric, false),
    ('Ja''Marr Chase', 'WR', 6.8::numeric, false),
    ('Lamar Jackson', 'QB', 7.7::numeric, false),
    ('Puka Nacua', 'WR', 8.7::numeric, false),
    ('Jaxon Smith-Njigba', 'WR', 9.7::numeric, false),
    ('Patrick Mahomes II', 'QB', 10.3::numeric, false),
    ('Jalen Hurts', 'QB', 11.3::numeric, false),
    ('Bijan Robinson', 'RB', 14.2::numeric, false),
    ('Caleb Williams', 'QB', 14.3::numeric, false),
    ('Justin Herbert', 'QB', 14.3::numeric, false),
    ('Jahmyr Gibbs', 'RB', 15.8::numeric, false),
    ('CeeDee Lamb', 'WR', 15.9::numeric, false),
    ('Justin Jefferson', 'WR', 16.3::numeric, false),
    ('Amon-Ra St. Brown', 'WR', 18.8::numeric, false),
    ('Jaxson Dart', 'QB', 19.6::numeric, false),
    ('Malik Nabers', 'WR', 20.9::numeric, false),
    ('Ashton Jeanty', 'RB', 22.3::numeric, false),
    ('Brock Purdy', 'QB', 22.9::numeric, false),
    ('Bo Nix', 'QB', 23.4::numeric, false),
    ('Drake London', 'WR', 23.9::numeric, false),
    ('De''Von Achane', 'RB', 24.3::numeric, false),
    ('Trevor Lawrence', 'QB', 25.7::numeric, false),
    ('Jonathan Taylor', 'RB', 29.1::numeric, false),
    ('Nico Collins', 'WR', 29.2::numeric, false),
    ('James Cook III', 'RB', 29.4::numeric, false),
    ('Omarion Hampton', 'RB', 31.4::numeric, false),
    ('George Pickens', 'WR', 31.9::numeric, false),
    ('Jordan Love', 'QB', 32.4::numeric, false),
    ('Tetairoa McMillan', 'WR', 32.9::numeric, false),
    ('Brock Bowers', 'TE', 35.0::numeric, false),
    ('Rashee Rice', 'WR', 36.0::numeric, false),
    ('Dak Prescott', 'QB', 36.4::numeric, false),
    ('Trey McBride', 'TE', 37.0::numeric, false),
    ('Garrett Wilson', 'WR', 37.3::numeric, false),
    ('Jeremiyah Love', 'RB', 38.4::numeric, true),
    ('Chris Olave', 'WR', 38.5::numeric, false),
    ('Ladd McConkey', 'WR', 41.7::numeric, false),
    ('Baker Mayfield', 'QB', 42.8::numeric, false),
    ('Emeka Egbuka', 'WR', 43.6::numeric, false),
    ('A.J. Brown', 'WR', 46.7::numeric, false),
    ('Tee Higgins', 'WR', 47.1::numeric, false),
    ('Breece Hall', 'RB', 48.0::numeric, false),
    ('Bucky Irving', 'RB', 49.3::numeric, false),
    ('C.J. Stroud', 'QB', 49.4::numeric, false),
    ('Jordyn Tyson', 'WR', 50.0::numeric, true),
    ('Carnell Tate', 'WR', 51.8::numeric, true),
    ('Fernando Mendoza', 'QB', 52.0::numeric, true),
    ('Zay Flowers', 'WR', 52.5::numeric, false),
    ('Brian Thomas Jr.', 'WR', 52.9::numeric, false),
    ('TreVeyon Henderson', 'RB', 53.0::numeric, false),
    ('Rome Odunze', 'WR', 53.5::numeric, false),
    ('Makai Lemon', 'WR', 54.4::numeric, true),
    ('Jameson Williams', 'WR', 54.8::numeric, false),
    ('DeVonta Smith', 'WR', 54.9::numeric, false),
    ('Chase Brown', 'RB', 55.6::numeric, false),
    ('Colston Loveland', 'TE', 56.6::numeric, false),
    ('Marvin Harrison Jr.', 'WR', 57.0::numeric, false),
    ('Jared Goff', 'QB', 57.3::numeric, false),
    ('Luther Burden III', 'WR', 58.5::numeric, false),
    ('Jaylen Waddle', 'WR', 58.8::numeric, false),
    ('Christian McCaffrey', 'RB', 59.4::numeric, false),
    ('Saquon Barkley', 'RB', 59.8::numeric, false),
    ('Tyler Warren', 'TE', 60.7::numeric, false),
    ('Sam Darnold', 'QB', 62.2::numeric, false),
    ('Tucker Kraft', 'TE', 65.8::numeric, false),
    ('Harold Fannin Jr.', 'TE', 66.8::numeric, false),
    ('Quinshon Judkins', 'RB', 67.2::numeric, false),
    ('Kenneth Walker III', 'RB', 67.5::numeric, false),
    ('Kyren Williams', 'RB', 68.2::numeric, false),
    ('Sam LaPorta', 'TE', 70.0::numeric, false),
    ('Cam Ward', 'QB', 70.3::numeric, false),
    ('Josh Jacobs', 'RB', 70.3::numeric, false),
    ('RJ Harvey', 'RB', 71.5::numeric, false),
    ('Kyle Pitts Sr.', 'TE', 76.3::numeric, false),
    ('Jordan Addison', 'WR', 77.0::numeric, false),
    ('DK Metcalf', 'WR', 78.3::numeric, false),
    ('Cam Skattebo', 'RB', 79.5::numeric, false),
    ('Kyler Murray', 'QB', 81.0::numeric, false),
    ('Denzel Boston', 'WR', 82.8::numeric, true),
    ('Travis Etienne Jr.', 'RB', 83.9::numeric, false),
    ('Ricky Pearsall', 'WR', 84.0::numeric, false),
    ('Christian Watson', 'WR', 85.0::numeric, false),
    ('Tyler Shough', 'QB', 85.4::numeric, false),
    ('Travis Hunter', 'WR', 89.1::numeric, false),
    ('Javonte Williams', 'RB', 90.4::numeric, false),
    ('Bryce Young', 'QB', 90.7::numeric, false),
    ('Dalton Kincaid', 'TE', 91.1::numeric, false),
    ('J.J. McCarthy', 'QB', 92.3::numeric, false),
    ('Terry McLaurin', 'WR', 92.5::numeric, false),
    ('Courtland Sutton', 'WR', 94.0::numeric, false),
    ('Matthew Stafford', 'QB', 94.1::numeric, false),
    ('Michael Pittman Jr.', 'WR', 95.0::numeric, false),
    ('Derrick Henry', 'RB', 95.2::numeric, false),
    ('Oronde Gadsden II', 'TE', 95.3::numeric, false),
    ('Xavier Worthy', 'WR', 95.5::numeric, false),
    ('Michael Penix Jr.', 'QB', 97.8::numeric, false),
    ('Davante Adams', 'WR', 99.3::numeric, false),
    ('Daniel Jones', 'QB', 100.6::numeric, false),
    ('Jakobi Meyers', 'WR', 100.8::numeric, false),
    ('Michael Wilson', 'WR', 101.0::numeric, false),
    ('DJ Moore', 'WR', 103.4::numeric, false),
    ('Wan''Dale Robinson', 'WR', 103.6::numeric, false),
    ('D''Andre Swift', 'RB', 103.8::numeric, false),
    ('Jake Ferguson', 'TE', 104.5::numeric, false),
    ('Jayden Higgins', 'WR', 104.6::numeric, false),
    ('K.C. Concepcion', 'WR', 110.7::numeric, true),
    ('Alec Pierce', 'WR', 111.0::numeric, false),
    ('Jonah Coleman', 'RB', 111.8::numeric, true),
    ('George Kittle', 'TE', 111.8::numeric, false),
    ('Quentin Johnston', 'WR', 112.5::numeric, false),
    ('Kenyon Sadiq', 'TE', 112.5::numeric, true),
    ('Khalil Shakir', 'WR', 113.8::numeric, false),
    ('Jaylen Warren', 'RB', 114.3::numeric, false),
    ('Brenton Strange', 'TE', 114.4::numeric, false),
    ('Brandon Aiyuk', 'WR', 116.5::numeric, false),
    ('Kyle Monangai', 'RB', 117.8::numeric, false),
    ('Zach Charbonnet', 'RB', 118.8::numeric, false),
    ('Jayden Reed', 'WR', 119.0::numeric, false),
    ('Eli Stowers', 'TE', 119.5::numeric, true),
    ('Mike Evans', 'WR', 120.5::numeric, false),
    ('Matthew Golden', 'WR', 120.5::numeric, false),
    ('Jauan Jennings', 'WR', 121.5::numeric, false),
    ('Chris Godwin Jr.', 'WR', 125.2::numeric, false),
    ('Josh Downs', 'WR', 125.3::numeric, false),
    ('Blake Corum', 'RB', 127.2::numeric, false),
    ('Woody Marks', 'RB', 127.5::numeric, false),
    ('Trey Benson', 'RB', 128.4::numeric, false),
    ('Stefon Diggs', 'WR', 128.9::numeric, false),
    ('Bhayshul Tuten', 'RB', 130.8::numeric, false),
    ('Rhamondre Stevenson', 'RB', 133.9::numeric, false),
    ('Mason Taylor', 'TE', 134.9::numeric, false),
    ('Rico Dowdle', 'RB', 135.6::numeric, false),
    ('Parker Washington', 'WR', 135.7::numeric, false),
    ('Dallas Goedert', 'TE', 138.9::numeric, false),
    ('Jalen Coker', 'WR', 141.3::numeric, false),
    ('Troy Franklin', 'WR', 141.7::numeric, false),
    ('Ty Simpson', 'QB', 143.3::numeric, true),
    ('Chuba Hubbard', 'RB', 143.6::numeric, false),
    ('Theo Johnson', 'TE', 144.8::numeric, false),
    ('David Montgomery', 'RB', 145.9::numeric, false),
    ('Terrance Ferguson', 'TE', 146.2::numeric, false),
    ('Deebo Samuel Sr.', 'WR', 147.2::numeric, false),
    ('Romeo Doubs', 'WR', 147.5::numeric, false),
    ('Tyreek Hill', 'WR', 147.8::numeric, true),
    ('Tyrone Tracy Jr.', 'RB', 149.3::numeric, false),
    ('Tre Harris', 'WR', 150.1::numeric, false),
    ('Tyler Allgeier', 'RB', 151.4::numeric, false),
    ('Rashid Shaheed', 'WR', 151.6::numeric, false),
    ('Jalen McMillan', 'WR', 152.1::numeric, false),
    ('Malik Willis', 'QB', 116.9::numeric, false),
    ('Mark Andrews', 'TE', 155.1::numeric, false),
    ('Juwan Johnson', 'TE', 155.2::numeric, false),
    ('Jerry Jeudy', 'WR', 155.3::numeric, false),
    ('Isaiah Likely', 'TE', 155.8::numeric, false),
    ('Jacory Croskey-Merritt', 'RB', 160.3::numeric, false),
    ('Tua Tagovailoa', 'QB', 124.6::numeric, false),
    ('Tony Pollard', 'RB', 160.6::numeric, false),
    ('Elic Ayomanor', 'WR', 160.8::numeric, false),
    ('T.J. Hockenson', 'TE', 161.3::numeric, false),
    ('Jaylin Noel', 'WR', 161.8::numeric, false),
    ('Michael Trigg', 'TE', 162.2::numeric, true),
    ('Omar Cooper Jr.', 'WR', 162.8::numeric, true),
    ('Kayshon Boutte', 'WR', 163.4::numeric, false),
    ('Kenneth Gainwell', 'RB', 165.1::numeric, false),
    ('Pat Bryant', 'WR', 165.4::numeric, false),
    ('Adonai Mitchell', 'WR', 166.9::numeric, false),
    ('Jadarian Price', 'RB', 167.6::numeric, true),
    ('Malachi Fields', 'WR', 168.4::numeric, true),
    ('Hunter Henry', 'TE', 168.6::numeric, false),
    ('Chris Brazzell II', 'WR', 171.0::numeric, true),
    ('Shedeur Sanders', 'QB', 138.1::numeric, false),
    ('Mike Washington Jr.', 'RB', 173.6::numeric, true),
    ('Tyjae Spears', 'RB', 173.9::numeric, false),
    ('J.K. Dobbins', 'RB', 175.3::numeric, false),
    ('Dalton Schultz', 'TE', 177.3::numeric, false),
    ('Alvin Kamara', 'RB', 178.8::numeric, false),
    ('AJ Barner', 'TE', 170.1::numeric, false),
    ('Kyle Williams', 'WR', 180.0::numeric, false),
    ('David Njoku', 'TE', 180.9::numeric, false),
    ('Kaleb Johnson', 'RB', 181.2::numeric, false),
    ('Chimere Dike', 'WR', 181.9::numeric, false),
    ('Keon Coleman', 'WR', 182.3::numeric, false),
    ('Tory Horton', 'WR', 183.2::numeric, false),
    ('Germie Bernard', 'WR', 184.3::numeric, true),
    ('Elijah Arroyo', 'TE', 185.9::numeric, false),
    ('Elijah Sarratt', 'WR', 186.8::numeric, true),
    ('Darnell Mooney', 'WR', 187.1::numeric, false),
    ('Jordan Mason', 'RB', 187.9::numeric, false),
    ('Isaac TeSlaa', 'WR', 188.5::numeric, false),
    ('Chris Bell', 'WR', 188.7::numeric, true),
    ('Dylan Sampson', 'RB', 188.7::numeric, false),
    ('Zachariah Branch', 'WR', 189.8::numeric, true),
    ('Emmett Johnson', 'RB', 190.9::numeric, true),
    ('Aaron Jones Sr.', 'RB', 191.9::numeric, false),
    ('Calvin Ridley', 'WR', 193.3::numeric, false),
    ('Antonio Williams', 'WR', 193.4::numeric, true),
    ('Rachaad White', 'RB', 193.6::numeric, false),
    ('Travis Kelce', 'TE', 194.9::numeric, false),
    ('James Conner', 'RB', 195.2::numeric, false),
    ('Tank Dell', 'WR', 195.5::numeric, false),
    ('Marvin Mims Jr.', 'WR', 196.6::numeric, false),
    ('Isiah Pacheco', 'RB', 196.7::numeric, false),
    ('Brian Robinson Jr.', 'RB', 197.0::numeric, false),
    ('Anthony Richardson Sr.', 'QB', 143.0::numeric, false),
    ('Braelon Allen', 'RB', 198.5::numeric, false),
    ('Tank Bigsby', 'RB', 199.8::numeric, false),
    ('Ja''Kobi Lane', 'WR', 200.0::numeric, true),
    ('Pat Freiermuth', 'TE', 202.3::numeric, false),
    ('Jonathon Brooks', 'RB', 202.7::numeric, false),
    ('Cade Otton', 'TE', 204.1::numeric, false),
    ('Kimani Vidal', 'RB', 204.3::numeric, false),
    ('Chig Okonkwo', 'TE', 204.6::numeric, false),
    ('Devin Neal', 'RB', 206.4::numeric, false),
    ('Dontayvion Wicks', 'WR', 207.6::numeric, false),
    ('Rashod Bateman', 'WR', 200.4::numeric, false),
    ('Christian Kirk', 'WR', 210.8::numeric, false),
    ('Evan Engram', 'TE', 211.3::numeric, false),
    ('Kaytron Allen', 'RB', 211.5::numeric, true),
    ('Nicholas Singleton', 'RB', 213.2::numeric, true),
    ('Justin Fields', 'QB', 148.8::numeric, false),
    ('Cedric Tillman', 'WR', 206.1::numeric, false),
    ('Jack Bech', 'WR', 207.0::numeric, false),
    ('Mac Jones', 'QB', 152.1::numeric, false),
    ('Cooper Kupp', 'WR', 216.3::numeric, false),
    ('Xavier Legette', 'WR', 211.9::numeric, false),
    ('Ray Davis', 'RB', 221.3::numeric, false),
    ('Ollie Gordon II', 'RB', 221.4::numeric, false),
    ('Keenan Allen', 'WR', 215.7::numeric, false),
    ('Tez Johnson', 'WR', 223.1::numeric, false),
    ('Geno Smith', 'QB', 165.0::numeric, false),
    ('Sean Tucker', 'RB', 225.3::numeric, false),
    ('Tre Tucker', 'WR', 218.2::numeric, false),
    ('Michael Mayer', 'TE', 218.8::numeric, false),
    ('Jaylen Wright', 'RB', 226.8::numeric, false),
    ('Ben Sinnott', 'TE', 213.1::numeric, false),
    ('Marquise Brown', 'WR', 221.6::numeric, false),
    ('Malik Washington', 'WR', 223.4::numeric, false),
    ('DeMario Douglas', 'WR', 224.2::numeric, false),
    ('Darius Slayton', 'WR', 228.0::numeric, false),
    ('Devaughn Vele', 'WR', 234.4::numeric, false),
    ('Keaton Mitchell', 'RB', 234.7::numeric, false),
    ('Demond Claiborne', 'RB', 242.0::numeric, true),
    ('Kendre Miller', 'RB', 237.7::numeric, false),
    ('Skyler Bell', 'WR', 245.4::numeric, true),
    ('Najee Harris', 'RB', 239.3::numeric, false),
    ('Joe Mixon', 'RB', 235.1::numeric, false),
    ('Gunnar Helm', 'TE', 199.0::numeric, false),
    ('Jaydon Blue', 'RB', 243.3::numeric, false),
    ('Jalen Royals', 'WR', 245.2::numeric, false),
    ('Isaiah Bond', 'WR', 245.8::numeric, false),
    ('Brashard Smith', 'RB', 246.8::numeric, false),
    ('Isaiah Davis', 'RB', 247.6::numeric, false),
    ('Chris Rodriguez Jr.', 'RB', 244.5::numeric, false),
    ('Joshua Palmer', 'WR', 238.7::numeric, false),
    ('Emanuel Wilson', 'RB', 240.7::numeric, false),
    ('Roman Wilson', 'WR', 249.9::numeric, false),
    ('Adam Randall', 'RB', 262.2::numeric, true),
    ('Andrei Iosivas', 'WR', 245.2::numeric, false),
    ('Cole Kmet', 'TE', 240.4::numeric, false),
    ('DJ Giddens', 'RB', 260.2::numeric, false),
    ('Aaron Rodgers', 'QB', 167.0::numeric, false),
    ('Ryan Flournoy', 'WR', 233.3::numeric, false),
    ('Roman Hemby', 'RB', 266.5::numeric, true),
    ('Isaac Guerendo', 'RB', 267.1::numeric, false),
    ('Jarquez Hunter', 'RB', 267.3::numeric, false),
    ('Calvin Austin III', 'WR', 251.9::numeric, false),
    ('Ja''Tavion Sanders', 'TE', 245.0::numeric, false),
    ('Jonnu Smith', 'TE', 252.9::numeric, false),
    ('Colby Parkinson', 'TE', 228.0::numeric, false),
    ('Dont''e Thornton Jr.', 'WR', 247.5::numeric, false),
    ('Will Shipley', 'RB', 268.6::numeric, false),
    ('Kareem Hunt', 'RB', 261.2::numeric, false),
    ('Jordan Whittington', 'WR', 267.3::numeric, false),
    ('Nick Chubb', 'RB', 262.2::numeric, false),
    ('Audric Estime', 'RB', 255.5::numeric, false),
    ('Jake Tonges', 'TE', 230.9::numeric, false),
    ('Jaylin Lane', 'WR', 264.4::numeric, false),
    ('Devin Singletary', 'RB', 259.5::numeric, false),
    ('Tahj Brooks', 'RB', 277.2::numeric, false),
    ('Luke McCaffrey', 'WR', 260.1::numeric, false),
    ('Mike Gesicki', 'TE', 245.9::numeric, false),
    ('Jerome Ford', 'RB', 269.2::numeric, false),
    ('Trevor Etienne', 'RB', 275.7::numeric, false),
    ('Jalen Milroe', 'QB', 179.1::numeric, false),
    ('John Metchie III', 'WR', 253.4::numeric, false),
    ('Jacoby Brissett', 'QB', 184.5::numeric, false),
    ('Darnell Washington', 'TE', 248.8::numeric, false),
    ('Jordan James', 'RB', 278.8::numeric, false),
    ('MarShawn Lloyd', 'RB', 274.5::numeric, false),
    ('Jaleel McLaughlin', 'RB', 276.4::numeric, false),
    ('Jalen Nailor', 'WR', 265.1::numeric, false),
    ('Michael Carter', 'RB', 267.4::numeric, false),
    ('Kirk Cousins', 'QB', 185.0::numeric, false),
    ('Savion Williams', 'WR', 267.7::numeric, false),
    ('Justice Hill', 'RB', 279.0::numeric, false),
    ('Noah Gray', 'TE', 271.3::numeric, false),
    ('Bam Knight', 'RB', 267.4::numeric, false),
    ('Jalen Tolbert', 'WR', 268.2::numeric, false),
    ('KeAndre Lambert-Smith', 'WR', 269.4::numeric, false),
    ('DeAndre Hopkins', 'WR', 261.5::numeric, false),
    ('LeQuint Allen Jr.', 'RB', 279.8::numeric, false),
    ('Darren Waller', 'TE', 257.4::numeric, false),
    ('Roschon Johnson', 'RB', 277.1::numeric, false),
    ('Jameis Winston', 'QB', 205.0::numeric, false),
    ('Ty Johnson', 'RB', 284.8::numeric, false),
    ('Luke Musgrave', 'TE', 273.6::numeric, false),
    ('Noah Fant', 'TE', 275.9::numeric, false),
    ('Elijah Moore', 'WR', 267.7::numeric, true),
    ('Max Klare', 'TE', 156.5::numeric, true),
    ('Dawson Knox', 'TE', 275.1::numeric, false),
    ('Quinn Ewers', 'QB', 208.8::numeric, false),
    ('Russell Wilson', 'QB', 210.4::numeric, false),
    ('Konata Mumpfield', 'WR', 254.6::numeric, false),
    ('Tyler Lockett', 'WR', 268.6::numeric, false),
    ('Xavier Restrepo', 'WR', 282.3::numeric, false),
    ('Mack Hollins', 'WR', 272.5::numeric, false),
    ('Tyler Higbee', 'TE', 285.2::numeric, false),
    ('Greg Dulcich', 'TE', 275.9::numeric, false),
    ('Jack Endries', 'TE', 223.2::numeric, true),
    ('Ted Hurst', 'WR', 195.0::numeric, true),
    ('Zach Ertz', 'TE', 269.0::numeric, false),
    ('Marcus Mariota', 'QB', 232.4::numeric, false),
    ('Austin Ekeler', 'RB', 291.2::numeric, false),
    ('Samaje Perine', 'RB', 282.6::numeric, false),
    ('Tyrod Taylor', 'QB', 235.8::numeric, false),
    ('Tyquan Thornton', 'WR', 272.9::numeric, false),
    ('Miles Sanders', 'RB', 287.4::numeric, false),
    ('Spencer Rattler', 'QB', 241.8::numeric, false),
    ('Joe Flacco', 'QB', 212.0::numeric, false),
    ('Cade Stover', 'TE', 306.6::numeric, false),
    ('Demarcus Robinson', 'WR', 280.9::numeric, false),
    ('Antonio Gibson', 'RB', 291.5::numeric, false),
    ('Raheim Sanders', 'RB', 291.5::numeric, false),
    ('Ja''Lynn Polk', 'WR', 250.2::numeric, false),
    ('Brandin Cooks', 'WR', 293.1::numeric, false),
    ('Taysom Hill', 'TE', 265.2::numeric, false),
    ('Phil Mafah', 'RB', 266.2::numeric, false),
    ('Jawhar Jordan', 'RB', 245.0::numeric, false),
    ('Will Howard', 'QB', 246.8::numeric, false),
    ('Kevin Coleman Jr.', 'WR', 213.3::numeric, true),
    ('Gabe Davis', 'WR', 290.2::numeric, false),
    ('Chris Brooks', 'RB', 290.8::numeric, false),
    ('Jermaine Burton', 'WR', 276.6::numeric, true),
    ('Tai Felton', 'WR', 301.9::numeric, false),
    ('Diontae Johnson', 'WR', 220.3::numeric, true),
    ('Kendrick Bourne', 'WR', 278.2::numeric, false),
    ('Emari Demercado', 'RB', 257.5::numeric, false),
    ('Tyren Montgomery', 'WR', 223.3::numeric, true),
    ('Eric McAlister', 'WR', 228.0::numeric, true),
    ('Tanner Koziol', 'TE', 229.7::numeric, true),
    ('Tutu Atwell', 'WR', 297.3::numeric, false),
    ('Dillon Gabriel', 'QB', 267.8::numeric, false),
    ('Malik Davis', 'RB', 236.3::numeric, false),
    ('Rasheen Ali', 'RB', 289.2::numeric, false),
    ('Erick All Jr.', 'TE', 301.7::numeric, false),
    ('Justin Joly', 'TE', 239.7::numeric, true),
    ('Deion Burks', 'WR', 239.7::numeric, true),
    ('Malachi Corley', 'WR', 289.8::numeric, false),
    ('Le''Veon Moss', 'RB', 273.0::numeric, true),
    ('Jared Wiley', 'TE', 275.8::numeric, false),
    ('Nick Westbrook-Ikhine', 'WR', 296.8::numeric, true),
    ('Jimmy Garoppolo', 'QB', 197.0::numeric, false),
    ('Thomas Fidone II', 'TE', 298.4::numeric, false),
    ('Treylon Burks', 'WR', 298.4::numeric, false),
    ('Jahan Dotson', 'WR', 309.3::numeric, false),
    ('Efton Chism III', 'WR', 301.0::numeric, false),
    ('Jarrett Stidham', 'QB', 209.0::numeric, false),
    ('Brenen Thompson', 'WR', 260.7::numeric, true),
    ('Mitchell Evans', 'TE', 317.7::numeric, false),
    ('KaVontae Turpin', 'WR', 305.6::numeric, false),
    ('Jeremy McNichols', 'RB', 268.3::numeric, false),
    ('Bryce Lance', 'WR', 223.0::numeric, true),
    ('Dameon Pierce', 'RB', 294.3::numeric, false),
    ('Mason Rudolph', 'QB', 273.0::numeric, false),
    ('Greg Dortch', 'WR', 295.8::numeric, false),
    ('Tanner McKee', 'QB', 93.0::numeric, false),
    ('Xavier Hutchinson', 'WR', 310.6::numeric, false),
    ('Austin Hooper', 'TE', 310.6::numeric, false),
    ('Seth McGowan', 'RB', 276.0::numeric, true),
    ('Damien Martinez', 'RB', 276.0::numeric, false),
    ('Will Levis', 'QB', 232.5::numeric, false),
    ('Olamide Zaccheaus', 'WR', 311.4::numeric, false),
    ('Dyami Brown', 'WR', 312.2::numeric, false),
    ('Joe Milton III', 'QB', 235.5::numeric, false),
    ('Jimmy Horn Jr.', 'WR', 321.7::numeric, false),
    ('Gardner Minshew II', 'QB', 240.0::numeric, false),
    ('Philip Rivers', 'QB', 241.5::numeric, false),
    ('Brady Cook', 'QB', 243.0::numeric, false),
    ('JuJu Smith-Schuster', 'WR', 283.3::numeric, false),
    ('Tommy Tremble', 'TE', 303.8::numeric, false),
    ('J''Mari Taylor', 'RB', 284.0::numeric, true),
    ('Noah Brown', 'WR', 305.0::numeric, false),
    ('Tyler Huntley', 'QB', 247.0::numeric, false),
    ('Joe Royer', 'TE', 249.5::numeric, true),
    ('Devontez Walker', 'WR', 318.4::numeric, false),
    ('Robert Henry Jr.', 'RB', 251.0::numeric, true),
    ('Riley Leonard', 'QB', 251.0::numeric, false),
    ('Jam Miller', 'RB', 288.7::numeric, true),
    ('Trey Lance', 'QB', 251.5::numeric, false),
    ('Will Dissly', 'TE', 314.8::numeric, false),
    ('Josh Oliver', 'TE', 319.6::numeric, false),
    ('Tyrell Shavers', 'WR', 290.3::numeric, false),
    ('Elijah Higgins', 'TE', 319.8::numeric, false),
    ('Khalil Herbert', 'RB', 291.7::numeric, false),
    ('Aidan O''Connell', 'QB', 256.0::numeric, false),
    ('Javon Baker', 'WR', 256.0::numeric, true),
    ('Raheem Mostert', 'RB', 256.5::numeric, false),
    ('Darius Cooper', 'WR', 293.7::numeric, false),
    ('Davis Allen', 'TE', 328.4::numeric, false),
    ('Davis Mills', 'QB', 264.0::numeric, false),
    ('Zamir White', 'RB', 298.0::numeric, false),
    ('Elijah Mitchell', 'RB', 268.0::numeric, false),
    ('Theo Wease Jr.', 'WR', 272.5::numeric, false),
    ('Charlie Kolar', 'TE', 325.8::numeric, false),
    ('Carson Wentz', 'QB', 185.0::numeric, false),
    ('Garrett Nussmeier', 'QB', 185.0::numeric, true),
    ('Jaydn Ott', 'RB', 306.3::numeric, true),
    ('Kevin Austin Jr.', 'WR', 279.5::numeric, false),
    ('Romello Brinson', 'WR', 197.0::numeric, true),
    ('Daniel Bellinger', 'TE', 335.4::numeric, false),
    ('Harrison Wallace III', 'WR', 199.0::numeric, true),
    ('Zack Moss', 'RB', 282.0::numeric, true),
    ('Alexander Mattison', 'RB', 283.0::numeric, false),
    ('Aaron Anderson', 'WR', 286.0::numeric, true),
    ('Reggie Virgil', 'WR', 209.0::numeric, true),
    ('Tyler Conklin', 'TE', 333.0::numeric, false),
    ('Jahdae Walker', 'WR', 287.0::numeric, false),
    ('Ty Chandler', 'RB', 287.5::numeric, false),
    ('Curtis Samuel', 'WR', 326.3::numeric, false),
    ('Jordan Watkins', 'WR', 314.0::numeric, false),
    ('Brock Wright', 'TE', 332.8::numeric, false),
    ('Jalin Hyatt', 'WR', 338.0::numeric, false),
    ('Sterling Shepard', 'WR', 314.7::numeric, false),
    ('Jeremy Ruckert', 'TE', 333.8::numeric, false),
    ('Carson Beck', 'QB', 217.0::numeric, true),
    ('George Holani', 'RB', 328.3::numeric, false),
    ('Jaret Patterson', 'RB', 231.0::numeric, false),
    ('Tyler Badie', 'RB', 298.5::numeric, false),
    ('Sam Roush', 'TE', 298.5::numeric, true),
    ('Caleb Douglas', 'WR', 234.0::numeric, true),
    ('Isaiah Williams', 'WR', 299.5::numeric, false),
    ('Drew Allar', 'QB', 243.0::numeric, true),
    ('Eli Raridon', 'TE', 305.0::numeric, true),
    ('Josh Reynolds', 'WR', 305.5::numeric, false),
    ('Dallen Bentley', 'TE', 307.5::numeric, true),
    ('Barion Brown', 'WR', 253.0::numeric, true),
    ('Zavier Scott', 'RB', 254.0::numeric, false),
    ('Kaelon Black', 'RB', 309.5::numeric, true),
    ('Josh Cameron', 'WR', 256.0::numeric, true),
    ('Marlin Klein', 'TE', 310.0::numeric, true),
    ('Cole Payton', 'QB', 258.0::numeric, true),
    ('Isaiah Hodgins', 'WR', 313.0::numeric, false),
    ('Arian Smith', 'WR', 313.5::numeric, false),
    ('Brevin Jordan', 'TE', 264.0::numeric, false),
    ('Xavier Weaver', 'WR', 264.0::numeric, false),
    ('Eric Rivers', 'WR', 267.0::numeric, true),
    ('Sincere McCormick', 'RB', 269.0::numeric, true),
    ('Oscar Delp', 'TE', 318.0::numeric, true),
    ('John Bates', 'TE', 334.0::numeric, false),
    ('Mitch Tinsley', 'WR', 337.7::numeric, false),
    ('Vinny Anthony II', 'WR', 280.0::numeric, true),
    ('David Sills V', 'WR', 329.0::numeric, false),
    ('Tyler Goodson', 'RB', 284.0::numeric, false),
    ('Deshaun Watson', 'QB', 286.0::numeric, false),
    ('Mitchell Trubisky', 'QB', 291.0::numeric, false),
    ('Joshua Dobbs', 'QB', 292.0::numeric, false),
    ('Tip Reiman', 'TE', 293.0::numeric, false),
    ('Kalif Raymond', 'WR', 294.0::numeric, false),
    ('Cam Akers', 'RB', 329.0::numeric, false),
    ('Tyler Johnson', 'WR', 296.0::numeric, false),
    ('Nathan Carter', 'RB', 297.0::numeric, false),
    ('Dae''Quan Wright', 'TE', 306.0::numeric, true),
    ('Kalel Mullings', 'RB', 307.0::numeric, false),
    ('Jacob Cowing', 'WR', 335.5::numeric, false),
    ('John Michael Gyllenborg', 'TE', 308.0::numeric, true),
    ('Dare Ogunbowale', 'RB', 311.0::numeric, false),
    ('Marquez Valdes-Scantling', 'WR', 312.0::numeric, false),
    ('Josh Cuevas', 'TE', 312.0::numeric, true),
    ('Jackson Hawes', 'TE', 353.7::numeric, false),
    ('Van Jefferson', 'WR', 314.0::numeric, false),
    ('Terrell Jennings', 'RB', 315.0::numeric, false),
    ('Desmond Reid', 'RB', 315.0::numeric, true),
    ('Hunter Long', 'TE', 357.3::numeric, false),
    ('Hassan Haskins', 'RB', 318.0::numeric, false),
    ('Tyler Scott', 'WR', 323.0::numeric, false),
    ('Tyson Bagent', 'QB', 325.0::numeric, false),
    ('Tim Patrick', 'WR', 327.0::numeric, false),
    ('Isaiah Williams', 'WR', 331.0::numeric, true),
    ('Grant Calcaterra', 'TE', 331.0::numeric, false),
    ('Jared Wayne', 'WR', 331.0::numeric, false),
    ('Evan Hull', 'RB', 332.0::numeric, false),
    ('A.J. Dillon', 'RB', 333.0::numeric, false),
    ('C.J. Daniels', 'WR', 333.0::numeric, true),
    ('Dane Key', 'WR', 334.0::numeric, true),
    ('Luke Schoonmaker', 'TE', 336.0::numeric, false),
    ('Henry Ruggs III', 'WR', 337.0::numeric, true),
    ('Tanner Hudson', 'TE', 338.0::numeric, false),
    ('Nick Nash', 'WR', 347.0::numeric, false),
    ('Lil''Jordan Humphrey', 'WR', 350.0::numeric, false),
    ('Allen Lazard', 'WR', 356.0::numeric, true),
    ('Ricky White III', 'WR', 356.0::numeric, false),
    ('Kameron Johnson', 'WR', 358.0::numeric, false),
    ('Jamari Thrash', 'WR', 361.0::numeric, false),
    ('Chris Moore', 'WR', 363.0::numeric, false),
    ('Adam Trautman', 'TE', 365.0::numeric, false),
    ('Zay Jones', 'WR', 369.0::numeric, false),
    ('Cedrick Wilson Jr.', 'WR', 370.0::numeric, false),
    ('David Moore', 'WR', 371.0::numeric, false),
    ('Dante Pettis', 'WR', 372.0::numeric, false),
    ('Michael Bandy', 'WR', 373.0::numeric, true),
    ('Shedrick Jackson', 'WR', 374.0::numeric, false),
    ('Xavier Smith', 'WR', 375.0::numeric, false),
    ('Casey Washington', 'WR', 378.0::numeric, false),
    ('Scotty Miller', 'WR', 379.0::numeric, false),
    ('Jonathan Mingo', 'WR', 380.0::numeric, false),
    ('Trent Sherfield Sr.', 'WR', 381.0::numeric, true),
    ('Ben Skowronek', 'WR', 382.0::numeric, false),
    ('Foster Moreau', 'TE', 384.0::numeric, false),
    ('Julian Hill', 'TE', 397.0::numeric, false)
),
aliases (input_name, db_name) AS (
  VALUES
    ('Patrick Mahomes II', 'Patrick Mahomes'),
    ('Deebo Samuel Sr.', 'Deebo Samuel'),
    ('Aaron Jones Sr.', 'Aaron Jones'),
    ('Anthony Richardson Sr.', 'Anthony Richardson'),
    ('Chris Godwin Jr.', 'Chris Godwin'),
    ('Brian Thomas Jr.', 'Brian Thomas'),
    ('Kyle Pitts Sr.', 'Kyle Pitts'),
    ('Michael Pittman Jr.', 'Michael Pittman'),
    ('Marvin Harrison Jr.', 'Marvin Harrison'),
    ('Ollie Gordon II', 'Ollie Gordon'),
    ('Chris Rodriguez Jr.', 'Chris Rodriguez'),
    ('Jonathon Brooks', 'Jonathan Brooks'),
    ('Travis Etienne Jr.', 'Travis Etienne'),
    ('Michael Penix Jr.', 'Michael Penix'),
    ('Thomas Fidone II', 'Thomas Fidone'),
    ('Erick All Jr.', 'Erick All')
),
lookup AS (
  SELECT
    p.input_name,
    p.position,
    p.avg_rank,
    p.is_fa,
    COALESCE(a.db_name, p.input_name) AS match_name
  FROM parsed p
  LEFT JOIN aliases a ON a.input_name = p.input_name
),
-- Deduplicate by match_name (same player can appear twice, e.g. Isaiah Williams NYJ vs FA)
lookup_dedup AS (
  SELECT DISTINCT ON (match_name) input_name, position, avg_rank, is_fa, match_name
  FROM lookup
  ORDER BY match_name, avg_rank ASC
),

ins_baseline AS (
  INSERT INTO public.baseline_community_rankings (scoring_format, league_type, is_superflex, player_id, rank)
  SELECT
    'ppr'::text,
    'dynasty'::text,
    true,
    pl.id,
    l.avg_rank
  FROM lookup_dedup l
  INNER JOIN public.players pl ON pl.name = l.match_name AND pl.season = 2025
  ON CONFLICT (scoring_format, league_type, is_superflex, player_id)
  DO UPDATE SET rank = EXCLUDED.rank
)

INSERT INTO public.baseline_rookies (name, position, rank, scoring_format, league_type, is_superflex)
SELECT l.input_name, l.position, l.avg_rank, 'ppr'::text, 'dynasty'::text, true
FROM lookup_dedup l
WHERE l.is_fa = true
  AND NOT EXISTS (
    SELECT 1 FROM public.players p
    WHERE (p.name = l.match_name OR p.name = l.input_name) AND p.season = 2025
  )
  AND NOT EXISTS (
    SELECT 1 FROM public.baseline_rookies br
    WHERE br.name = l.input_name
      AND br.scoring_format = 'ppr'
      AND br.league_type = 'dynasty'
      AND br.is_superflex = true
  )
ON CONFLICT (scoring_format, league_type, is_superflex, name) DO NOTHING;
