-- Rookies-only dynasty non-superflex baseline.
-- Same list for PPR, half-PPR, and standard scoring (scoring_format = 'any').
-- Used when league has rookies_only=true, league_type=dynasty, is_superflex=false.

INSERT INTO public.baseline_rookies (name, position, rank, scoring_format, league_type, is_superflex)
VALUES
  ('Jeremiyah Love', 'RB', 1, 'any', 'dynasty', false),
  ('Carnell Tate', 'WR', 2, 'any', 'dynasty', false),
  ('Makai Lemon', 'WR', 3, 'any', 'dynasty', false),
  ('Jordyn Tyson', 'WR', 4, 'any', 'dynasty', false),
  ('Denzel Boston', 'WR', 5, 'any', 'dynasty', false),
  ('Jonah Coleman', 'RB', 6, 'any', 'dynasty', false),
  ('K.C. Concepcion', 'WR', 7, 'any', 'dynasty', false),
  ('Jadarian Price', 'RB', 8, 'any', 'dynasty', false),
  ('Kenyon Sadiq', 'TE', 9, 'any', 'dynasty', false),
  ('Emmett Johnson', 'RB', 10, 'any', 'dynasty', false),
  ('Fernando Mendoza', 'QB', 11, 'any', 'dynasty', false),
  ('Kaytron Allen', 'RB', 12, 'any', 'dynasty', false),
  ('Eli Stowers', 'TE', 13, 'any', 'dynasty', false),
  ('Omar Cooper Jr.', 'WR', 14, 'any', 'dynasty', false),
  ('Nicholas Singleton', 'RB', 15, 'any', 'dynasty', false),
  ('Chris Bell', 'WR', 16, 'any', 'dynasty', false),
  ('Elijah Sarratt', 'WR', 17, 'any', 'dynasty', false),
  ('Chris Brazzell II', 'WR', 18, 'any', 'dynasty', false),
  ('Zachariah Branch', 'WR', 19, 'any', 'dynasty', false),
  ('Germie Bernard', 'WR', 20, 'any', 'dynasty', false),
  ('Mike Washington Jr.', 'RB', 21, 'any', 'dynasty', false),
  ('Ty Simpson', 'QB', 22, 'any', 'dynasty', false),
  ('Malachi Fields', 'WR', 23, 'any', 'dynasty', false),
  ('Antonio Williams', 'WR', 24, 'any', 'dynasty', false),
  ('Demond Claiborne', 'RB', 25, 'any', 'dynasty', false),
  ('Ja''Kobi Lane', 'WR', 26, 'any', 'dynasty', false),
  ('J''Mari Taylor', 'RB', 27, 'any', 'dynasty', false),
  ('Garrett Nussmeier', 'QB', 28, 'any', 'dynasty', false),
  ('Max Klare', 'TE', 29, 'any', 'dynasty', false),
  ('Michael Trigg', 'TE', 30, 'any', 'dynasty', false),
  ('Adam Randall', 'RB', 31, 'any', 'dynasty', false),
  ('Skyler Bell', 'WR', 32, 'any', 'dynasty', false),
  ('Le''Veon Moss', 'RB', 33, 'any', 'dynasty', false),
  ('Roman Hemby', 'RB', 34, 'any', 'dynasty', false),
  ('Deion Burks', 'WR', 35, 'any', 'dynasty', false),
  ('Justin Joly', 'TE', 36, 'any', 'dynasty', false),
  ('Carson Beck', 'QB', 37, 'any', 'dynasty', false),
  ('Seth McGowan', 'RB', 38, 'any', 'dynasty', false),
  ('Jaydn Ott', 'RB', 39, 'any', 'dynasty', false),
  ('Jam Miller', 'RB', 40, 'any', 'dynasty', false),
  ('Drew Allar', 'QB', 41, 'any', 'dynasty', false),
  ('Jack Endries', 'TE', 42, 'any', 'dynasty', false),
  ('Eric McAlister', 'WR', 43, 'any', 'dynasty', false),
  ('Kevin Coleman Jr.', 'WR', 44, 'any', 'dynasty', false),
  ('Cade Klubnik', 'QB', 45, 'any', 'dynasty', false),
  ('Joe Royer', 'TE', 46, 'any', 'dynasty', false),
  ('Robert Henry Jr.', 'RB', 47, 'any', 'dynasty', false),
  ('Barion Brown', 'WR', 48, 'any', 'dynasty', false),
  ('Bryce Lance', 'WR', 49, 'any', 'dynasty', false),
  ('Cole Payton', 'QB', 50, 'any', 'dynasty', false),
  ('Tanner Koziol', 'TE', 51, 'any', 'dynasty', false),
  ('Ted Hurst', 'WR', 52, 'any', 'dynasty', false),
  ('Terion Stewart', 'RB', 53, 'any', 'dynasty', false),
  ('C.J. Daniels', 'WR', 54, 'any', 'dynasty', false),
  ('Aaron Anderson', 'WR', 55, 'any', 'dynasty', false),
  ('Brenen Thompson', 'WR', 56, 'any', 'dynasty', false),
  ('Dane Key', 'WR', 57, 'any', 'dynasty', false),
  ('Diego Pavia', 'QB', 58, 'any', 'dynasty', false),
  ('Oscar Delp', 'TE', 59, 'any', 'dynasty', false),
  ('De''Zhaun Stribling', 'WR', 60, 'any', 'dynasty', false),
  ('Noah Whittington', 'RB', 61, 'any', 'dynasty', false),
  ('TJ Harden', 'RB', 62, 'any', 'dynasty', false),
  ('Eric Rivers', 'WR', 63, 'any', 'dynasty', false),
  ('Desmond Reid', 'RB', 64, 'any', 'dynasty', false),
  ('Jamal Haynes', 'RB', 65, 'any', 'dynasty', false),
  ('Josh Cameron', 'WR', 66, 'any', 'dynasty', false),
  ('Rahsul Faison', 'RB', 67, 'any', 'dynasty', false),
  ('Taylen Green', 'QB', 68, 'any', 'dynasty', false),
  ('Kaelon Black', 'RB', 69, 'any', 'dynasty', false),
  ('Dean Connors', 'RB', 70, 'any', 'dynasty', false),
  ('Chase Roberts', 'WR', 71, 'any', 'dynasty', false),
  ('Eli Raridon', 'TE', 72, 'any', 'dynasty', false),
  ('RJ Maryland', 'TE', 73, 'any', 'dynasty', false),
  ('Sawyer Robertson', 'QB', 74, 'any', 'dynasty', false),
  ('Reggie Virgil', 'WR', 75, 'any', 'dynasty', false),
  ('J. Michael Sturdivant', 'WR', 76, 'any', 'dynasty', false),
  ('Caleb Douglas', 'WR', 77, 'any', 'dynasty', false),
  ('Dallen Bentley', 'TE', 78, 'any', 'dynasty', false),
  ('Rueben Owens', 'RB', 79, 'any', 'dynasty', false),
  ('Sam Roush', 'TE', 80, 'any', 'dynasty', false),
  ('Jack Velling', 'TE', 81, 'any', 'dynasty', false),
  ('Miller Moss', 'QB', 82, 'any', 'dynasty', false),
  ('Jalon Daniels', 'QB', 83, 'any', 'dynasty', false),
  ('Chip Trayanum', 'RB', 84, 'any', 'dynasty', false),
  ('Dae''Quan Wright', 'TE', 85, 'any', 'dynasty', false),
  ('Marlin Klein', 'TE', 86, 'any', 'dynasty', false),
  ('Lewis Bond', 'WR', 87, 'any', 'dynasty', false),
  ('Conner Weigman', 'QB', 88, 'any', 'dynasty', false),
  ('Cyrus Allen', 'WR', 89, 'any', 'dynasty', false),
  ('Tyren Montgomery', 'WR', 90, 'any', 'dynasty', false),
  ('Nyck Harbor', 'WR', 91, 'any', 'dynasty', false),
  ('Malachi Nelson', 'QB', 92, 'any', 'dynasty', false),
  ('Harrison Wallace III', 'WR', 93, 'any', 'dynasty', false),
  ('Josh Cuevas', 'TE', 94, 'any', 'dynasty', false),
  ('L.J. Martin', 'RB', 95, 'any', 'dynasty', false),
  ('Noah Thomas', 'WR', 96, 'any', 'dynasty', false),
  ('Eli Heidenreich', 'WR', 97, 'any', 'dynasty', false),
  ('Joey Aguilar', 'QB', 98, 'any', 'dynasty', false),
  ('Trebor Pena', 'WR', 99, 'any', 'dynasty', false),
  ('Hank Beatty', 'WR', 100, 'any', 'dynasty', false),
  ('Vinny Anthony II', 'WR', 101, 'any', 'dynasty', false),
  ('Luke Altmyer', 'QB', 102, 'any', 'dynasty', false),
  ('Arch Manning', 'QB', 103, 'any', 'dynasty', false),
  ('CJ Donaldson', 'RB', 104, 'any', 'dynasty', false),
  ('Malik Rutherford', 'WR', 105, 'any', 'dynasty', false),
  ('Jeff Caldwell', 'WR', 106, 'any', 'dynasty', false),
  ('Chris Hilton Jr.', 'WR', 107, 'any', 'dynasty', false),
  ('Kentrel Bullock', 'RB', 108, 'any', 'dynasty', false),
  ('Lake McRee', 'TE', 109, 'any', 'dynasty', false),
  ('John Michael Gyllenborg', 'TE', 110, 'any', 'dynasty', false),
  ('Dillon Bell', 'WR', 111, 'any', 'dynasty', false)
ON CONFLICT (scoring_format, league_type, is_superflex, name) DO UPDATE SET
  position = EXCLUDED.position,
  rank = EXCLUDED.rank;
