-- PPR / season / superflex baseline rankings
-- Inserts into baseline_community_rankings (matches players by name, season=2025)
-- Adds FA rookies to baseline_rookies if not in players or already in baseline_rookies

WITH parsed (input_name, position, avg_rank, is_fa) AS (
  VALUES
    ('Josh Allen', 'QB', 1.2::numeric, false),
    ('Lamar Jackson', 'QB', 2.8::numeric, false),
    ('Drake Maye', 'QB', 3.3::numeric, false),
    ('Joe Burrow', 'QB', 4.0::numeric, false),
    ('Jayden Daniels', 'QB', 7.5::numeric, false),
    ('Ja''Marr Chase', 'WR', 7.7::numeric, false),
    ('Jalen Hurts', 'QB', 8.2::numeric, false),
    ('Puka Nacua', 'WR', 8.5::numeric, false),
    ('Bijan Robinson', 'RB', 10.0::numeric, false),
    ('Justin Herbert', 'QB', 11.8::numeric, false),
    ('Jaxon Smith-Njigba', 'WR', 12.0::numeric, false),
    ('Jaxson Dart', 'QB', 13.0::numeric, false),
    ('Jahmyr Gibbs', 'RB', 13.0::numeric, false),
    ('Trevor Lawrence', 'QB', 14.7::numeric, false),
    ('CeeDee Lamb', 'WR', 15.0::numeric, false),
    ('Christian McCaffrey', 'RB', 16.2::numeric, false),
    ('Amon-Ra St. Brown', 'WR', 18.0::numeric, false),
    ('Patrick Mahomes II', 'QB', 19.3::numeric, false),
    ('Dak Prescott', 'QB', 19.5::numeric, false),
    ('Caleb Williams', 'QB', 19.8::numeric, false),
    ('Brock Purdy', 'QB', 20.8::numeric, false),
    ('De''Von Achane', 'RB', 22.3::numeric, false),
    ('Drake London', 'WR', 22.8::numeric, false),
    ('Justin Jefferson', 'WR', 22.8::numeric, false),
    ('Malik Nabers', 'WR', 23.0::numeric, false),
    ('Jonathan Taylor', 'RB', 23.5::numeric, false),
    ('Nico Collins', 'WR', 26.3::numeric, false),
    ('Rashee Rice', 'WR', 27.0::numeric, false),
    ('Chris Olave', 'WR', 31.2::numeric, false),
    ('George Pickens', 'WR', 31.7::numeric, false),
    ('Bo Nix', 'QB', 31.8::numeric, false),
    ('James Cook III', 'RB', 32.3::numeric, false),
    ('Ashton Jeanty', 'RB', 32.5::numeric, false),
    ('Matthew Stafford', 'QB', 32.8::numeric, false),
    ('Trey McBride', 'TE', 33.7::numeric, false),
    ('Brock Bowers', 'TE', 35.0::numeric, false),
    ('A.J. Brown', 'WR', 37.0::numeric, false),
    ('Jared Goff', 'QB', 38.5::numeric, false),
    ('Jordan Love', 'QB', 39.0::numeric, false),
    ('Omarion Hampton', 'RB', 39.2::numeric, false),
    ('Tetairoa McMillan', 'WR', 40.5::numeric, false),
    ('Chase Brown', 'RB', 40.5::numeric, false),
    ('Tee Higgins', 'WR', 44.3::numeric, false),
    ('Baker Mayfield', 'QB', 44.5::numeric, false),
    ('Saquon Barkley', 'RB', 44.8::numeric, false),
    ('Garrett Wilson', 'WR', 45.2::numeric, false),
    ('Josh Jacobs', 'RB', 48.2::numeric, false),
    ('Bucky Irving', 'RB', 48.7::numeric, false),
    ('Ladd McConkey', 'WR', 53.8::numeric, false),
    ('Breece Hall', 'RB', 53.8::numeric, false),
    ('Davante Adams', 'WR', 54.3::numeric, false),
    ('Zay Flowers', 'WR', 54.5::numeric, false),
    ('Malik Willis', 'QB', 56.2::numeric, false),
    ('Derrick Henry', 'RB', 56.8::numeric, false),
    ('Jameson Williams', 'WR', 56.8::numeric, false),
    ('Tyler Shough', 'QB', 57.2::numeric, false),
    ('DeVonta Smith', 'WR', 60.2::numeric, false),
    ('Jaylen Waddle', 'WR', 60.2::numeric, false),
    ('Luther Burden III', 'WR', 62.7::numeric, false),
    ('Terry McLaurin', 'WR', 63.2::numeric, false),
    ('Kenneth Walker III', 'RB', 63.2::numeric, false),
    ('Sam Darnold', 'QB', 64.0::numeric, false),
    ('Kyren Williams', 'RB', 64.7::numeric, false),
    ('Mike Evans', 'WR', 65.5::numeric, false),
    ('Kyler Murray', 'QB', 66.2::numeric, false),
    ('Harold Fannin Jr.', 'TE', 66.8::numeric, false),
    ('Cam Ward', 'QB', 67.0::numeric, false),
    ('RJ Harvey', 'RB', 67.2::numeric, false),
    ('C.J. Stroud', 'QB', 70.5::numeric, false),
    ('TreVeyon Henderson', 'RB', 70.8::numeric, false),
    ('Cam Skattebo', 'RB', 71.0::numeric, false),
    ('Emeka Egbuka', 'WR', 71.3::numeric, false),
    ('Courtland Sutton', 'WR', 72.0::numeric, false),
    ('Colston Loveland', 'TE', 72.3::numeric, false),
    ('Javonte Williams', 'RB', 72.7::numeric, false),
    ('Travis Etienne Jr.', 'RB', 72.8::numeric, false),
    ('Christian Watson', 'WR', 77.2::numeric, false),
    ('Rome Odunze', 'WR', 79.5::numeric, false),
    ('DK Metcalf', 'WR', 80.3::numeric, false),
    ('Quinshon Judkins', 'RB', 80.3::numeric, false),
    ('Brian Thomas Jr.', 'WR', 82.3::numeric, false),
    ('D''Andre Swift', 'RB', 83.5::numeric, false),
    ('Tucker Kraft', 'TE', 84.0::numeric, false),
    ('Tyler Warren', 'TE', 84.2::numeric, false),
    ('Jakobi Meyers', 'WR', 84.2::numeric, false),
    ('Ricky Pearsall', 'WR', 86.3::numeric, false),
    ('Jaylen Warren', 'RB', 88.7::numeric, false),
    ('Bryce Young', 'QB', 91.2::numeric, false),
    ('Chris Godwin Jr.', 'WR', 92.3::numeric, false),
    ('Stefon Diggs', 'WR', 93.5::numeric, false),
    ('Rhamondre Stevenson', 'RB', 98.5::numeric, false),
    ('Kyle Monangai', 'RB', 98.5::numeric, false),
    ('Rico Dowdle', 'RB', 98.7::numeric, false),
    ('Marvin Harrison Jr.', 'WR', 99.5::numeric, false),
    ('Michael Penix Jr.', 'QB', 99.7::numeric, false),
    ('Michael Wilson', 'WR', 100.3::numeric, false),
    ('Tony Pollard', 'RB', 100.7::numeric, false),
    ('Sam LaPorta', 'TE', 101.5::numeric, false),
    ('Michael Pittman Jr.', 'WR', 102.5::numeric, false),
    ('Daniel Jones', 'QB', 103.5::numeric, false),
    ('Kyle Pitts Sr.', 'TE', 106.5::numeric, false),
    ('Bhayshul Tuten', 'RB', 108.2::numeric, false),
    ('James Conner', 'RB', 109.2::numeric, false),
    ('Jordan Addison', 'WR', 109.7::numeric, false),
    ('Blake Corum', 'RB', 109.8::numeric, false),
    ('Chuba Hubbard', 'RB', 113.2::numeric, false),
    ('Zach Charbonnet', 'RB', 114.2::numeric, false),
    ('Wan''Dale Robinson', 'WR', 114.2::numeric, false),
    ('Quentin Johnston', 'WR', 114.5::numeric, false),
    ('Woody Marks', 'RB', 114.5::numeric, false),
    ('Dalton Kincaid', 'TE', 114.5::numeric, false),
    ('Aaron Jones Sr.', 'RB', 115.0::numeric, false),
    ('Khalil Shakir', 'WR', 116.0::numeric, false),
    ('Trey Benson', 'RB', 116.2::numeric, false),
    ('Jauan Jennings', 'WR', 117.7::numeric, false),
    ('Alec Pierce', 'WR', 119.2::numeric, false),
    ('Alvin Kamara', 'RB', 119.7::numeric, false),
    ('Brenton Strange', 'TE', 120.2::numeric, false),
    ('Jake Ferguson', 'TE', 120.5::numeric, false),
    ('Oronde Gadsden II', 'TE', 120.5::numeric, false),
    ('J.J. McCarthy', 'QB', 90.6::numeric, false),
    ('Parker Washington', 'WR', 122.5::numeric, false),
    ('Juwan Johnson', 'TE', 125.0::numeric, false),
    ('Travis Hunter', 'WR', 125.5::numeric, false),
    ('Tyreek Hill', 'WR', 126.8::numeric, true),
    ('DJ Moore', 'WR', 128.3::numeric, false),
    ('Jayden Higgins', 'WR', 129.2::numeric, false),
    ('David Montgomery', 'RB', 129.3::numeric, false),
    ('Jacory Croskey-Merritt', 'RB', 132.3::numeric, false),
    ('Xavier Worthy', 'WR', 133.2::numeric, false),
    ('Dylan Sampson', 'RB', 133.7::numeric, false),
    ('Jayden Reed', 'WR', 136.3::numeric, false),
    ('Shedeur Sanders', 'QB', 107.4::numeric, false),
    ('Braelon Allen', 'RB', 137.2::numeric, false),
    ('George Kittle', 'TE', 137.3::numeric, false),
    ('Josh Downs', 'WR', 137.8::numeric, false),
    ('Dalton Schultz', 'TE', 137.8::numeric, false),
    ('Deebo Samuel Sr.', 'WR', 138.8::numeric, false),
    ('Tyler Allgeier', 'RB', 141.3::numeric, false),
    ('Kenneth Gainwell', 'RB', 142.2::numeric, false),
    ('Jalen Coker', 'WR', 143.3::numeric, false),
    ('Tyjae Spears', 'RB', 146.3::numeric, false),
    ('Dallas Goedert', 'TE', 147.2::numeric, false),
    ('Tyrone Tracy Jr.', 'RB', 147.7::numeric, false),
    ('Jeremiyah Love', 'RB', 150.3::numeric, true),
    ('Adonai Mitchell', 'WR', 150.5::numeric, false),
    ('Jerry Jeudy', 'WR', 150.7::numeric, false),
    ('Troy Franklin', 'WR', 151.0::numeric, false),
    ('J.K. Dobbins', 'RB', 151.5::numeric, false),
    ('Hunter Henry', 'TE', 152.7::numeric, false),
    ('K.C. Concepcion', 'WR', 154.8::numeric, true),
    ('Jordan Mason', 'RB', 155.3::numeric, false),
    ('Kaleb Johnson', 'RB', 156.7::numeric, false),
    ('Rachaad White', 'RB', 157.5::numeric, false),
    ('Carnell Tate', 'WR', 158.8::numeric, true),
    ('Rashid Shaheed', 'WR', 160.7::numeric, false),
    ('Jacoby Brissett', 'QB', 137.2::numeric, false),
    ('Travis Kelce', 'TE', 162.5::numeric, false),
    ('Chimere Dike', 'WR', 162.7::numeric, false),
    ('Brandon Aiyuk', 'WR', 163.2::numeric, false),
    ('Jordyn Tyson', 'WR', 163.7::numeric, true),
    ('Devin Neal', 'RB', 165.2::numeric, false),
    ('Tua Tagovailoa', 'QB', 142.8::numeric, false),
    ('Tre Harris', 'WR', 166.0::numeric, false),
    ('Jaylin Noel', 'WR', 167.2::numeric, false),
    ('Tank Bigsby', 'RB', 167.2::numeric, false),
    ('Makai Lemon', 'WR', 167.3::numeric, true),
    ('Isiah Pacheco', 'RB', 167.3::numeric, false),
    ('Matthew Golden', 'WR', 167.5::numeric, false),
    ('Mark Andrews', 'TE', 167.7::numeric, false),
    ('Isaiah Likely', 'TE', 168.0::numeric, false),
    ('Mac Jones', 'QB', 146.4::numeric, false),
    ('Kimani Vidal', 'RB', 169.7::numeric, false),
    ('Romeo Doubs', 'WR', 170.2::numeric, false),
    ('Elic Ayomanor', 'WR', 172.3::numeric, false),
    ('Keaton Mitchell', 'RB', 173.7::numeric, false),
    ('Kayshon Boutte', 'WR', 174.8::numeric, false),
    ('Pat Bryant', 'WR', 176.7::numeric, false),
    ('Brian Robinson Jr.', 'RB', 179.0::numeric, false),
    ('Kendre Miller', 'RB', 180.5::numeric, false),
    ('Denzel Boston', 'WR', 131.0::numeric, true),
    ('Theo Johnson', 'TE', 182.7::numeric, false),
    ('Isaiah Davis', 'RB', 182.8::numeric, false),
    ('Tre Tucker', 'WR', 183.8::numeric, false),
    ('Joe Mixon', 'RB', 184.0::numeric, false),
    ('Darnell Mooney', 'WR', 186.7::numeric, false),
    ('Ryan Flournoy', 'WR', 187.0::numeric, false),
    ('Fernando Mendoza', 'QB', 97.3::numeric, true),
    ('Jalen McMillan', 'WR', 190.5::numeric, false),
    ('T.J. Hockenson', 'TE', 191.5::numeric, false),
    ('AJ Barner', 'TE', 194.3::numeric, false),
    ('Terrance Ferguson', 'TE', 195.0::numeric, false),
    ('Jaylen Wright', 'RB', 195.0::numeric, false),
    ('Emanuel Wilson', 'RB', 195.3::numeric, false),
    ('Keon Coleman', 'WR', 196.0::numeric, false),
    ('Mack Hollins', 'WR', 196.3::numeric, false),
    ('Marvin Mims Jr.', 'WR', 197.2::numeric, false),
    ('Isaac TeSlaa', 'WR', 197.3::numeric, false),
    ('Calvin Ridley', 'WR', 197.8::numeric, false),
    ('Geno Smith', 'QB', 182.4::numeric, false),
    ('Jadarian Price', 'RB', 117.3::numeric, true),
    ('Jonathon Brooks', 'RB', 200.0::numeric, false),
    ('Mason Taylor', 'TE', 200.3::numeric, false),
    ('Rashod Bateman', 'WR', 201.3::numeric, false),
    ('Kyle Williams', 'WR', 201.8::numeric, false),
    ('Brashard Smith', 'RB', 202.7::numeric, false),
    ('Xavier Legette', 'WR', 203.0::numeric, false),
    ('Emmett Johnson', 'RB', 125.7::numeric, true),
    ('Dontayvion Wicks', 'WR', 204.0::numeric, false),
    ('Sean Tucker', 'RB', 204.5::numeric, false),
    ('Najee Harris', 'RB', 205.0::numeric, false),
    ('Keenan Allen', 'WR', 205.2::numeric, false),
    ('Ray Davis', 'RB', 207.0::numeric, false),
    ('Gunnar Helm', 'TE', 208.0::numeric, false),
    ('Jonah Coleman', 'RB', 136.0::numeric, true),
    ('Chris Rodriguez Jr.', 'RB', 212.3::numeric, false),
    ('Cooper Kupp', 'WR', 212.7::numeric, false),
    ('Anthony Richardson Sr.', 'QB', 178.3::numeric, false),
    ('Jerome Ford', 'RB', 199.4::numeric, false),
    ('Darius Slayton', 'WR', 214.7::numeric, false),
    ('Tory Horton', 'WR', 215.5::numeric, false),
    ('David Njoku', 'TE', 217.7::numeric, false),
    ('Ollie Gordon II', 'RB', 217.7::numeric, false),
    ('Chig Okonkwo', 'TE', 219.0::numeric, false),
    ('Jaleel McLaughlin', 'RB', 220.2::numeric, false),
    ('Ty Johnson', 'RB', 222.0::numeric, false),
    ('Colby Parkinson', 'TE', 222.2::numeric, false),
    ('Aaron Rodgers', 'QB', 106.5::numeric, false),
    ('Isaiah Bond', 'WR', 223.8::numeric, false),
    ('Tank Dell', 'WR', 224.2::numeric, false),
    ('Pat Freiermuth', 'TE', 231.0::numeric, false),
    ('Evan Engram', 'TE', 231.5::numeric, false),
    ('Joe Milton III', 'QB', 182.0::numeric, false),
    ('Jalen Royals', 'WR', 233.2::numeric, false),
    ('Konata Mumpfield', 'WR', 233.8::numeric, false),
    ('Jack Bech', 'WR', 235.5::numeric, false),
    ('Cade Otton', 'TE', 235.5::numeric, false),
    ('Isaac Guerendo', 'RB', 228.2::numeric, false),
    ('Andrei Iosivas', 'WR', 230.6::numeric, false),
    ('Omar Cooper Jr.', 'WR', 157.5::numeric, true),
    ('Devaughn Vele', 'WR', 240.7::numeric, false),
    ('Kenyon Sadiq', 'TE', 200.7::numeric, true),
    ('Jake Tonges', 'TE', 236.8::numeric, false),
    ('Malachi Fields', 'WR', 170.5::numeric, true),
    ('Audric Estime', 'RB', 237.6::numeric, false),
    ('Christian Kirk', 'WR', 237.6::numeric, false),
    ('Mike Washington Jr.', 'RB', 172.5::numeric, true),
    ('Bam Knight', 'RB', 238.2::numeric, false),
    ('Marquise Brown', 'WR', 247.3::numeric, false),
    ('Malik Davis', 'RB', 240.8::numeric, false),
    ('Luke McCaffrey', 'WR', 247.8::numeric, false),
    ('Calvin Austin III', 'WR', 241.6::numeric, false),
    ('Chris Brazzell II', 'WR', 182.5::numeric, true),
    ('Jaydon Blue', 'RB', 249.0::numeric, false),
    ('Kaytron Allen', 'RB', 184.0::numeric, true),
    ('Noah Gray', 'TE', 243.4::numeric, false),
    ('Tyquan Thornton', 'WR', 245.6::numeric, false),
    ('DJ Giddens', 'RB', 252.7::numeric, false),
    ('Dont''e Thornton Jr.', 'WR', 247.2::numeric, false),
    ('Elijah Sarratt', 'WR', 195.5::numeric, true),
    ('LeQuint Allen Jr.', 'RB', 248.4::numeric, false),
    ('Cedric Tillman', 'WR', 254.3::numeric, false),
    ('Malik Washington', 'WR', 256.8::numeric, false),
    ('Germie Bernard', 'WR', 203.0::numeric, true),
    ('Eli Stowers', 'TE', 230.0::numeric, true),
    ('Mike Gesicki', 'TE', 251.4::numeric, false),
    ('Nicholas Singleton', 'RB', 206.5::numeric, true),
    ('Zachariah Branch', 'WR', 207.0::numeric, true),
    ('Devin Singletary', 'RB', 254.0::numeric, false),
    ('Chris Brooks', 'RB', 256.0::numeric, false),
    ('George Holani', 'RB', 260.8::numeric, false),
    ('Olamide Zaccheaus', 'WR', 263.0::numeric, false),
    ('Justice Hill', 'RB', 257.6::numeric, false),
    ('Antonio Williams', 'WR', 223.0::numeric, true),
    ('Trevor Etienne', 'RB', 258.4::numeric, false),
    ('Tez Johnson', 'WR', 264.7::numeric, false),
    ('John Bates', 'TE', 260.3::numeric, false),
    ('John Metchie III', 'WR', 262.4::numeric, false),
    ('Ben Sinnott', 'TE', 252.3::numeric, false),
    ('Darren Waller', 'TE', 247.3::numeric, false),
    ('Jarquez Hunter', 'RB', 261.4::numeric, false),
    ('Demond Claiborne', 'RB', 231.5::numeric, true),
    ('MarShawn Lloyd', 'RB', 261.8::numeric, false),
    ('Elijah Arroyo', 'TE', 248.7::numeric, false),
    ('Jaylin Lane', 'WR', 269.0::numeric, false),
    ('Michael Mayer', 'TE', 250.0::numeric, false),
    ('Joshua Palmer', 'WR', 270.2::numeric, false),
    ('Chris Bell', 'WR', 264.5::numeric, true),
    ('Jordan James', 'RB', 278.0::numeric, false),
    ('Xavier Hutchinson', 'WR', 275.0::numeric, false),
    ('Michael Carter', 'RB', 271.0::numeric, false),
    ('Will Shipley', 'RB', 275.4::numeric, false),
    ('DeMario Douglas', 'WR', 277.0::numeric, false),
    ('Samaje Perine', 'RB', 275.8::numeric, false),
    ('Greg Dulcich', 'TE', 257.0::numeric, false),
    ('Ja''Kobi Lane', 'WR', 221.0::numeric, true),
    ('Emari Demercado', 'RB', 273.0::numeric, false),
    ('Jalen Nailor', 'WR', 279.0::numeric, false),
    ('Adam Randall', 'RB', 223.0::numeric, true),
    ('Reggie Virgil', 'WR', 227.0::numeric, true),
    ('Darnell Washington', 'TE', 265.5::numeric, false),
    ('Tommy Myers', 'TE', 256.0::numeric, true),
    ('Ted Hurst', 'WR', 231.0::numeric, true),
    ('Tahj Brooks', 'RB', 279.2::numeric, false),
    ('Kareem Hunt', 'RB', 280.4::numeric, false),
    ('Austin Ekeler', 'RB', 280.8::numeric, false),
    ('Nick Chubb', 'RB', 280.8::numeric, false),
    ('Jared Wiley', 'TE', 244.0::numeric, false),
    ('Le''Veon Moss', 'RB', 246.0::numeric, true),
    ('Jam Miller', 'RB', 249.0::numeric, true),
    ('Tyler Higbee', 'TE', 283.5::numeric, false),
    ('J''Mari Taylor', 'RB', 258.0::numeric, true),
    ('Jawhar Jordan', 'RB', 278.6::numeric, false),
    ('Terrell Jennings', 'RB', 292.0::numeric, false),
    ('Antonio Gibson', 'RB', 277.7::numeric, false),
    ('Raheim Sanders', 'RB', 290.3::numeric, false),
    ('Dameon Pierce', 'RB', 295.0::numeric, false),
    ('Deion Burks', 'WR', 275.0::numeric, true),
    ('Caleb Douglas', 'WR', 278.0::numeric, true),
    ('Tyren Montgomery', 'WR', 279.0::numeric, true),
    ('Skyler Bell', 'WR', 282.0::numeric, true),
    ('Ja''Tavion Sanders', 'TE', 283.0::numeric, false),
    ('Kevin Coleman Jr.', 'WR', 285.0::numeric, true),
    ('Cole Kmet', 'TE', 286.0::numeric, false),
    ('Barion Brown', 'WR', 289.0::numeric, true),
    ('Seth McGowan', 'RB', 291.0::numeric, true),
    ('Jaydn Ott', 'RB', 293.0::numeric, true),
    ('Kaelon Black', 'RB', 296.0::numeric, true),
    ('Luke Musgrave', 'TE', 300.0::numeric, false),
    ('Bryce Lance', 'WR', 304.0::numeric, true),
    ('Josh Cameron', 'WR', 305.0::numeric, true),
    ('Vinny Anthony II', 'WR', 307.0::numeric, true),
    ('Brenen Thompson', 'WR', 308.0::numeric, true),
    ('Max Klare', 'TE', 310.0::numeric, true),
    ('Dawson Knox', 'TE', 312.0::numeric, false),
    ('Elijah Higgins', 'TE', 313.0::numeric, false),
    ('Jonnu Smith', 'TE', 316.0::numeric, false),
    ('Michael Trigg', 'TE', 322.0::numeric, true),
    ('Justin Joly', 'TE', 326.0::numeric, true),
    ('Aaron Anderson', 'WR', 328.0::numeric, true),
    ('Jack Endries', 'TE', 329.0::numeric, true),
    ('C.J. Daniels', 'WR', 330.0::numeric, true),
    ('Tanner Koziol', 'TE', 331.0::numeric, true),
    ('Dane Key', 'WR', 332.0::numeric, true),
    ('Chris Hilton Jr.', 'WR', 333.0::numeric, true),
    ('Robert Henry Jr.', 'RB', 335.0::numeric, true),
    ('Zach Ertz', 'TE', 336.0::numeric, false),
    ('Desmond Reid', 'RB', 337.0::numeric, true),
    ('Roman Hemby', 'RB', 338.0::numeric, true),
    ('Thomas Fidone II', 'TE', 340.0::numeric, false),
    ('Taysom Hill', 'TE', 341.0::numeric, false),
    ('Erick All Jr.', 'TE', 344.0::numeric, false)
),
aliases (input_name, db_name) AS (
  VALUES
    ('Patrick Mahomes II', 'Patrick Mahomes'),
    ('Deebo Samuel Sr.', 'Deebo Samuel'),
    ('Aaron Jones Sr.', 'Aaron Jones'),
    ('Anthony Richardson Sr.', 'Anthony Richardson'),
    ('Chris Godwin Jr.', 'Chris Godwin'),
    ('Brian Thomas Jr.', 'Brian Thomas'),
    ('Kyle Pitts Sr.', 'Kyle Pitts'),
    ('Michael Pittman Jr.', 'Michael Pittman'),
    ('Marvin Harrison Jr.', 'Marvin Harrison'),
    ('Ollie Gordon II', 'Ollie Gordon'),
    ('Chris Rodriguez Jr.', 'Chris Rodriguez'),
    ('Jonathon Brooks', 'Jonathan Brooks'),
    ('Travis Etienne Jr.', 'Travis Etienne'),
    ('Michael Penix Jr.', 'Michael Penix'),
    ('Thomas Fidone II', 'Thomas Fidone'),
    ('Erick All Jr.', 'Erick All')
),
lookup AS (
  SELECT
    p.input_name,
    p.position,
    p.avg_rank,
    p.is_fa,
    COALESCE(a.db_name, p.input_name) AS match_name
  FROM parsed p
  LEFT JOIN aliases a ON a.input_name = p.input_name
),

ins_baseline AS (
  INSERT INTO public.baseline_community_rankings (scoring_format, league_type, is_superflex, player_id, rank)
  SELECT
    'ppr'::text,
    'season'::text,
    true,
    pl.id,
    l.avg_rank
  FROM lookup l
  INNER JOIN public.players pl ON pl.name = l.match_name AND pl.season = 2025
  ON CONFLICT (scoring_format, league_type, is_superflex, player_id)
  DO UPDATE SET rank = EXCLUDED.rank
)

INSERT INTO public.baseline_rookies (name, position, rank, scoring_format, league_type, is_superflex)
SELECT l.input_name, l.position, l.avg_rank, 'ppr'::text, 'season'::text, true
FROM lookup l
WHERE l.is_fa = true
  AND NOT EXISTS (
    SELECT 1 FROM public.players p
    WHERE (p.name = l.match_name OR p.name = l.input_name) AND p.season = 2025
  )
  AND NOT EXISTS (
    SELECT 1 FROM public.baseline_rookies br
    WHERE br.name = l.input_name
      AND br.scoring_format = 'ppr'
      AND br.league_type = 'season'
      AND br.is_superflex = true
  )
ON CONFLICT (scoring_format, league_type, is_superflex, name) DO NOTHING;
