-- Standard / season / non-superflex baseline rankings
-- Overrides existing baseline for this bucket (scoring_format=standard, league_type=season, is_superflex=false)
-- Inserts into baseline_community_rankings (matches players by name, season=2025)
-- Adds FA rookies to baseline_rookies if not in players or already in baseline_rookies

-- Delete existing baseline for this bucket so we fully replace
DELETE FROM public.baseline_community_rankings
WHERE scoring_format = 'standard' AND league_type = 'season' AND is_superflex = false;

DELETE FROM public.baseline_rookies
WHERE scoring_format = 'standard' AND league_type = 'season' AND is_superflex = false;

WITH parsed (input_name, position, avg_rank, is_fa) AS (
  VALUES
    ('Bijan Robinson', 'RB', 1.0::numeric, false),
    ('Puka Nacua', 'WR', 2.0::numeric, false),
    ('Jahmyr Gibbs', 'RB', 3.0::numeric, false),
    ('Ja''Marr Chase', 'WR', 4.7::numeric, false),
    ('Jaxon Smith-Njigba', 'WR', 5.3::numeric, false),
    ('Jonathan Taylor', 'RB', 7.0::numeric, false),
    ('Christian McCaffrey', 'RB', 7.7::numeric, false),
    ('Amon-Ra St. Brown', 'WR', 8.5::numeric, false),
    ('CeeDee Lamb', 'WR', 8.8::numeric, false),
    ('Malik Nabers', 'WR', 10.2::numeric, false),
    ('James Cook III', 'RB', 11.8::numeric, false),
    ('Drake London', 'WR', 12.2::numeric, false),
    ('De''Von Achane', 'RB', 12.3::numeric, false),
    ('Nico Collins', 'WR', 14.8::numeric, false),
    ('Ashton Jeanty', 'RB', 16.5::numeric, false),
    ('George Pickens', 'WR', 18.0::numeric, false),
    ('Brock Bowers', 'TE', 19.0::numeric, false),
    ('Rashee Rice', 'WR', 19.8::numeric, false),
    ('Justin Jefferson', 'WR', 20.2::numeric, false),
    ('Derrick Henry', 'RB', 20.8::numeric, false),
    ('Omarion Hampton', 'RB', 22.5::numeric, false),
    ('Saquon Barkley', 'RB', 24.0::numeric, false),
    ('Josh Allen', 'QB', 25.0::numeric, false),
    ('Chris Olave', 'WR', 25.7::numeric, false),
    ('Tee Higgins', 'WR', 26.3::numeric, false),
    ('Josh Jacobs', 'RB', 28.2::numeric, false),
    ('Lamar Jackson', 'QB', 28.3::numeric, false),
    ('Drake Maye', 'QB', 29.2::numeric, false),
    ('Trey McBride', 'TE', 30.3::numeric, false),
    ('Chase Brown', 'RB', 30.8::numeric, false),
    ('Tetairoa McMillan', 'WR', 31.2::numeric, false),
    ('A.J. Brown', 'WR', 31.7::numeric, false),
    ('Breece Hall', 'RB', 32.7::numeric, false),
    ('Tucker Kraft', 'TE', 33.7::numeric, false),
    ('Davante Adams', 'WR', 35.8::numeric, false),
    ('Joe Burrow', 'QB', 37.7::numeric, false),
    ('Bucky Irving', 'RB', 38.7::numeric, false),
    ('Garrett Wilson', 'WR', 40.0::numeric, false),
    ('Kyren Williams', 'RB', 40.8::numeric, false),
    ('Jameson Williams', 'WR', 40.8::numeric, false),
    ('Kenneth Walker III', 'RB', 41.2::numeric, false),
    ('Colston Loveland', 'TE', 41.3::numeric, false),
    ('Jaylen Waddle', 'WR', 45.7::numeric, false),
    ('Ladd McConkey', 'WR', 46.3::numeric, false),
    ('Zay Flowers', 'WR', 47.0::numeric, false),
    ('Christian Watson', 'WR', 48.5::numeric, false),
    ('Terry McLaurin', 'WR', 48.7::numeric, false),
    ('Travis Etienne Jr.', 'RB', 49.3::numeric, false),
    ('TreVeyon Henderson', 'RB', 49.8::numeric, false),
    ('Javonte Williams', 'RB', 50.8::numeric, false),
    ('RJ Harvey', 'RB', 51.3::numeric, false),
    ('Cam Skattebo', 'RB', 52.2::numeric, false),
    ('Jayden Daniels', 'QB', 52.7::numeric, false),
    ('Mike Evans', 'WR', 55.3::numeric, false),
    ('Jalen Hurts', 'QB', 57.8::numeric, false),
    ('Luther Burden III', 'WR', 58.2::numeric, false),
    ('Quinshon Judkins', 'RB', 58.7::numeric, false),
    ('DeVonta Smith', 'WR', 59.0::numeric, false),
    ('Emeka Egbuka', 'WR', 59.8::numeric, false),
    ('D''Andre Swift', 'RB', 60.0::numeric, false),
    ('Courtland Sutton', 'WR', 61.0::numeric, false),
    ('Rome Odunze', 'WR', 64.0::numeric, false),
    ('Jaxson Dart', 'QB', 64.2::numeric, false),
    ('Jaylen Warren', 'RB', 65.3::numeric, false),
    ('Justin Herbert', 'QB', 68.8::numeric, false),
    ('DK Metcalf', 'WR', 70.2::numeric, false),
    ('Blake Corum', 'RB', 70.2::numeric, false),
    ('Kyle Monangai', 'RB', 71.5::numeric, false),
    ('Tyler Warren', 'TE', 71.5::numeric, false),
    ('Harold Fannin Jr.', 'TE', 71.5::numeric, false),
    ('Rhamondre Stevenson', 'RB', 76.8::numeric, false),
    ('Denzel Boston', 'WR', 78.0::numeric, true),
    ('Trevor Lawrence', 'QB', 79.0::numeric, false),
    ('Brian Thomas Jr.', 'WR', 79.5::numeric, false),
    ('Bhayshul Tuten', 'RB', 80.0::numeric, false),
    ('Caleb Williams', 'QB', 81.2::numeric, false),
    ('Rico Dowdle', 'RB', 81.7::numeric, false),
    ('Tony Pollard', 'RB', 82.3::numeric, false),
    ('Alec Pierce', 'WR', 82.8::numeric, false),
    ('Marvin Harrison Jr.', 'WR', 83.5::numeric, false),
    ('Sam LaPorta', 'TE', 84.3::numeric, false),
    ('Michael Wilson', 'WR', 86.3::numeric, false),
    ('Patrick Mahomes II', 'QB', 87.7::numeric, false),
    ('Jacory Croskey-Merritt', 'RB', 89.0::numeric, false),
    ('Kyle Pitts Sr.', 'TE', 90.3::numeric, false),
    ('Jordan Addison', 'WR', 91.7::numeric, false),
    ('Dak Prescott', 'QB', 92.2::numeric, false),
    ('Brock Purdy', 'QB', 92.2::numeric, false),
    ('Brandon Aiyuk', 'WR', 92.8::numeric, false),
    ('Woody Marks', 'RB', 93.2::numeric, false),
    ('Zach Charbonnet', 'RB', 93.7::numeric, false),
    ('Dalton Kincaid', 'TE', 93.7::numeric, false),
    ('Ricky Pearsall', 'WR', 96.2::numeric, false),
    ('Quentin Johnston', 'WR', 96.2::numeric, false),
    ('Carnell Tate', 'WR', 96.8::numeric, true),
    ('Oronde Gadsden II', 'TE', 98.3::numeric, false),
    ('Chris Godwin Jr.', 'WR', 99.2::numeric, false),
    ('Jakobi Meyers', 'WR', 99.3::numeric, false),
    ('Chuba Hubbard', 'RB', 99.5::numeric, false),
    ('Jordyn Tyson', 'WR', 99.8::numeric, true),
    ('Stefon Diggs', 'WR', 100.7::numeric, false),
    ('David Montgomery', 'RB', 101.3::numeric, false),
    ('Matthew Stafford', 'QB', 104.8::numeric, false),
    ('Aaron Jones Sr.', 'RB', 105.0::numeric, false),
    ('Bo Nix', 'QB', 105.3::numeric, false),
    ('James Conner', 'RB', 105.5::numeric, false),
    ('K.C. Concepcion', 'WR', 106.0::numeric, true),
    ('Tyler Allgeier', 'RB', 108.7::numeric, false),
    ('Michael Pittman Jr.', 'WR', 108.8::numeric, false),
    ('Jordan Love', 'QB', 109.0::numeric, false),
    ('Makai Lemon', 'WR', 109.7::numeric, true),
    ('Jauan Jennings', 'WR', 110.0::numeric, false),
    ('Jared Goff', 'QB', 111.3::numeric, false),
    ('Braelon Allen', 'RB', 111.8::numeric, false),
    ('Parker Washington', 'WR', 112.5::numeric, false),
    ('Brenton Strange', 'TE', 113.3::numeric, false),
    ('DJ Moore', 'WR', 115.5::numeric, false),
    ('Jake Ferguson', 'TE', 117.2::numeric, false),
    ('Baker Mayfield', 'QB', 119.7::numeric, false),
    ('Juwan Johnson', 'TE', 121.2::numeric, false),
    ('Dallas Goedert', 'TE', 123.7::numeric, false),
    ('Jayden Higgins', 'WR', 124.0::numeric, false),
    ('J.K. Dobbins', 'RB', 124.5::numeric, false),
    ('Jordan Mason', 'RB', 125.3::numeric, false),
    ('Wan''Dale Robinson', 'WR', 125.8::numeric, false),
    ('Malik Willis', 'QB', 126.2::numeric, false),
    ('George Kittle', 'TE', 126.7::numeric, false),
    ('Tyler Shough', 'QB', 128.0::numeric, false),
    ('Jeremiyah Love', 'RB', 128.8::numeric, true),
    ('Alvin Kamara', 'RB', 129.8::numeric, false),
    ('Tyrone Tracy Jr.', 'RB', 130.2::numeric, false),
    ('Trey Benson', 'RB', 131.0::numeric, false),
    ('Tyreek Hill', 'WR', 131.0::numeric, true),
    ('C.J. Stroud', 'QB', 133.8::numeric, false),
    ('Hunter Henry', 'TE', 134.7::numeric, false),
    ('Khalil Shakir', 'WR', 134.8::numeric, false),
    ('Xavier Worthy', 'WR', 136.0::numeric, false),
    ('Kaleb Johnson', 'RB', 136.7::numeric, false),
    ('Deebo Samuel Sr.', 'WR', 137.5::numeric, false),
    ('Sam Darnold', 'QB', 141.0::numeric, false),
    ('Jayden Reed', 'WR', 141.3::numeric, false),
    ('Travis Hunter', 'WR', 142.8::numeric, false),
    ('Dylan Sampson', 'RB', 143.0::numeric, false),
    ('Tank Bigsby', 'RB', 143.2::numeric, false),
    ('Kyler Murray', 'QB', 143.7::numeric, false),
    ('Kenneth Gainwell', 'RB', 144.3::numeric, false),
    ('Josh Downs', 'WR', 145.5::numeric, false),
    ('Cam Ward', 'QB', 149.3::numeric, false),
    ('Jalen Coker', 'WR', 149.3::numeric, false),
    ('Houston Texans', 'D/ST', 150.0::numeric, false),
    ('Troy Franklin', 'WR', 152.0::numeric, false),
    ('Mark Andrews', 'TE', 154.5::numeric, false),
    ('Adonai Mitchell', 'WR', 155.7::numeric, false),
    ('Kimani Vidal', 'RB', 157.2::numeric, false),
    ('Tyjae Spears', 'RB', 157.5::numeric, false),
    ('Rachaad White', 'RB', 157.7::numeric, false),
    ('Joe Mixon', 'RB', 158.2::numeric, false),
    ('Dalton Schultz', 'TE', 159.3::numeric, false),
    ('Denver Broncos', 'D/ST', 161.0::numeric, false),
    ('Isiah Pacheco', 'RB', 163.3::numeric, false),
    ('Keaton Mitchell', 'RB', 164.2::numeric, false),
    ('Kayshon Boutte', 'WR', 164.7::numeric, false),
    ('Brian Robinson Jr.', 'RB', 164.8::numeric, false),
    ('Seattle Seahawks', 'D/ST', 165.0::numeric, false),
    ('Travis Kelce', 'TE', 165.3::numeric, false),
    ('Jonathon Brooks', 'RB', 167.7::numeric, false),
    ('Romeo Doubs', 'WR', 169.7::numeric, false),
    ('Jerry Jeudy', 'WR', 170.0::numeric, false),
    ('Philadelphia Eagles', 'D/ST', 170.8::numeric, false),
    ('Los Angeles Rams', 'D/ST', 172.0::numeric, false),
    ('Tank Dell', 'WR', 172.3::numeric, false),
    ('Jaylen Wright', 'RB', 172.5::numeric, false),
    ('Rashid Shaheed', 'WR', 173.3::numeric, false),
    ('Chimere Dike', 'WR', 173.5::numeric, false),
    ('Sean Tucker', 'RB', 173.7::numeric, false),
    ('Terrance Ferguson', 'TE', 174.0::numeric, false),
    ('Kendre Miller', 'RB', 174.0::numeric, false),
    ('Bryce Young', 'QB', 176.2::numeric, false),
    ('Fernando Mendoza', 'QB', 177.5::numeric, true),
    ('Devin Neal', 'RB', 180.8::numeric, false),
    ('Chris Rodriguez Jr.', 'RB', 181.2::numeric, false),
    ('Elic Ayomanor', 'WR', 181.3::numeric, false),
    ('Minnesota Vikings', 'D/ST', 182.0::numeric, false),
    ('Isaac TeSlaa', 'WR', 183.7::numeric, false),
    ('Theo Johnson', 'TE', 183.7::numeric, false),
    ('New England Patriots', 'D/ST', 184.0::numeric, false),
    ('Jacksonville Jaguars', 'D/ST', 185.0::numeric, false),
    ('Isaiah Likely', 'TE', 186.0::numeric, false),
    ('Brandon Aubrey', 'K', 186.0::numeric, false),
    ('Los Angeles Chargers', 'D/ST', 187.0::numeric, false),
    ('J.J. McCarthy', 'QB', 189.0::numeric, false),
    ('Green Bay Packers', 'D/ST', 189.0::numeric, false),
    ('Pittsburgh Steelers', 'D/ST', 190.0::numeric, false),
    ('Ka''imi Fairbairn', 'K', 191.0::numeric, false),
    ('Cam Little', 'K', 192.0::numeric, false),
    ('Jaylin Noel', 'WR', 192.8::numeric, false),
    ('Cleveland Browns', 'D/ST', 195.0::numeric, false),
    ('Matthew Golden', 'WR', 196.0::numeric, false),
    ('Kyle Williams', 'WR', 197.0::numeric, false),
    ('Cameron Dicker', 'K', 197.0::numeric, false),
    ('Emanuel Wilson', 'RB', 199.3::numeric, false),
    ('Jadarian Price', 'RB', 81.3::numeric, true),
    ('AJ Barner', 'TE', 200.8::numeric, false),
    ('Evan McPherson', 'K', 201.3::numeric, false),
    ('Tre Harris', 'WR', 201.8::numeric, false),
    ('Jason Myers', 'K', 206.7::numeric, false),
    ('Tre Tucker', 'WR', 207.5::numeric, false),
    ('Kansas City Chiefs', 'D/ST', 208.0::numeric, false),
    ('Tyler Loop', 'K', 208.8::numeric, false),
    ('Emmett Johnson', 'RB', 98.0::numeric, true),
    ('Tory Horton', 'WR', 209.7::numeric, false),
    ('Andy Borregales', 'K', 211.3::numeric, false),
    ('Ryan Flournoy', 'WR', 211.7::numeric, false),
    ('Detroit Lions', 'D/ST', 212.0::numeric, false),
    ('Ray Davis', 'RB', 212.5::numeric, false),
    ('Pat Bryant', 'WR', 213.3::numeric, false),
    ('Eddy Pineiro', 'K', 214.0::numeric, false),
    ('Jonah Coleman', 'RB', 113.3::numeric, true),
    ('Chase McLaughlin', 'K', 217.3::numeric, false),
    ('Buffalo Bills', 'D/ST', 219.0::numeric, false),
    ('Isaiah Davis', 'RB', 219.7::numeric, false),
    ('T.J. Hockenson', 'TE', 219.7::numeric, false),
    ('Darnell Mooney', 'WR', 222.0::numeric, false),
    ('Michael Penix Jr.', 'QB', 222.3::numeric, false),
    ('Keon Coleman', 'WR', 223.2::numeric, false),
    ('Daniel Jones', 'QB', 223.5::numeric, false),
    ('Rashod Bateman', 'WR', 224.2::numeric, false),
    ('Jalen McMillan', 'WR', 224.8::numeric, false),
    ('Cairo Santos', 'K', 225.5::numeric, false),
    ('Calvin Ridley', 'WR', 225.7::numeric, false),
    ('Ollie Gordon II', 'RB', 227.5::numeric, false),
    ('Najee Harris', 'RB', 228.0::numeric, false),
    ('Mack Hollins', 'WR', 231.0::numeric, false),
    ('Marvin Mims Jr.', 'WR', 232.2::numeric, false),
    ('David Njoku', 'TE', 232.3::numeric, false),
    ('Jaleel McLaughlin', 'RB', 233.5::numeric, false),
    ('Xavier Legette', 'WR', 234.7::numeric, false),
    ('Kenyon Sadiq', 'TE', 150.3::numeric, true),
    ('Harrison Mevis', 'K', 235.5::numeric, false),
    ('Mason Taylor', 'TE', 236.0::numeric, false),
    ('Baltimore Ravens', 'D/ST', 236.3::numeric, false),
    ('Dontayvion Wicks', 'WR', 236.7::numeric, false),
    ('Colby Parkinson', 'TE', 237.7::numeric, false),
    ('Isaac Guerendo', 'RB', 221.6::numeric, false),
    ('Jake Bates', 'K', 238.0::numeric, false),
    ('Ty Johnson', 'RB', 245.2::numeric, false),
    ('Darius Slayton', 'WR', 248.8::numeric, false),
    ('Gunnar Helm', 'TE', 249.5::numeric, false),
    ('Isaiah Bond', 'WR', 250.7::numeric, false),
    ('Chris Boswell', 'K', 251.0::numeric, false),
    ('Cooper Kupp', 'WR', 251.5::numeric, false),
    ('Brashard Smith', 'RB', 252.8::numeric, false),
    ('Chig Okonkwo', 'TE', 254.5::numeric, false),
    ('Keenan Allen', 'WR', 254.8::numeric, false),
    ('DJ Giddens', 'RB', 254.8::numeric, false),
    ('Pat Freiermuth', 'TE', 255.2::numeric, false),
    ('Omar Cooper Jr.', 'WR', 131.0::numeric, true),
    ('Malik Davis', 'RB', 247.0::numeric, false),
    ('Wil Lutz', 'K', 259.7::numeric, false),
    ('Atlanta Falcons', 'D/ST', 260.8::numeric, false),
    ('Eli Stowers', 'TE', 203.3::numeric, true),
    ('Jaydon Blue', 'RB', 261.7::numeric, false),
    ('Charlie Smyth', 'K', 250.2::numeric, false),
    ('Malachi Fields', 'WR', 153.0::numeric, true),
    ('Harrison Butker', 'K', 264.3::numeric, false),
    ('Mike Washington Jr.', 'RB', 156.0::numeric, true),
    ('Chris Brazzell II', 'WR', 157.5::numeric, true),
    ('Shedeur Sanders', 'QB', 267.8::numeric, false),
    ('George Holani', 'RB', 269.3::numeric, false),
    ('Jake Tonges', 'TE', 258.6::numeric, false),
    ('New Orleans Saints', 'D/ST', 269.5::numeric, false),
    ('Kaytron Allen', 'RB', 169.0::numeric, true),
    ('Devaughn Vele', 'WR', 270.7::numeric, false),
    ('Andrei Iosivas', 'WR', 261.2::numeric, false),
    ('Luke McCaffrey', 'WR', 271.0::numeric, false),
    ('Konata Mumpfield', 'WR', 271.5::numeric, false),
    ('Bam Knight', 'RB', 264.2::numeric, false),
    ('San Francisco 49ers', 'D/ST', 250.8::numeric, false),
    ('Jarquez Hunter', 'RB', 264.6::numeric, false),
    ('Cade Otton', 'TE', 274.2::numeric, false),
    ('Audric Estime', 'RB', 266.2::numeric, false),
    ('Evan Engram', 'TE', 275.5::numeric, false),
    ('MarShawn Lloyd', 'RB', 268.0::numeric, false),
    ('Elijah Sarratt', 'WR', 191.5::numeric, true),
    ('Jack Bech', 'WR', 277.5::numeric, false),
    ('Marquise Brown', 'WR', 277.8::numeric, false),
    ('Tyquan Thornton', 'WR', 270.0::numeric, false),
    ('Nicholas Singleton', 'RB', 197.5::numeric, true),
    ('Tommy Myers', 'TE', 240.0::numeric, true),
    ('Germie Bernard', 'WR', 201.5::numeric, true),
    ('Calvin Austin III', 'WR', 272.6::numeric, false),
    ('Zachariah Branch', 'WR', 203.5::numeric, true),
    ('Devin Singletary', 'RB', 275.0::numeric, false),
    ('Christian Kirk', 'WR', 276.0::numeric, false),
    ('Ben Sinnott', 'TE', 274.5::numeric, false),
    ('Cedric Tillman', 'WR', 286.2::numeric, false),
    ('Mike Gesicki', 'TE', 282.4::numeric, false),
    ('Trevor Etienne', 'RB', 284.0::numeric, false),
    ('Mac Jones', 'QB', 290.0::numeric, false),
    ('Tez Johnson', 'WR', 294.0::numeric, false),
    ('Noah Gray', 'TE', 285.4::numeric, false),
    ('Jacoby Brissett', 'QB', 292.0::numeric, false),
    ('Jordan James', 'RB', 298.8::numeric, false),
    ('Jerome Ford', 'RB', 286.8::numeric, false),
    ('Darren Waller', 'TE', 265.0::numeric, false),
    ('Aaron Rodgers', 'QB', 286.0::numeric, false),
    ('Antonio Williams', 'WR', 239.0::numeric, true),
    ('Elijah Arroyo', 'TE', 280.0::numeric, false),
    ('Dont''e Thornton Jr.', 'WR', 288.2::numeric, false),
    ('Malik Washington', 'WR', 296.8::numeric, false),
    ('Chris Bell', 'WR', 274.5::numeric, true),
    ('Jaylin Lane', 'WR', 299.0::numeric, false),
    ('Kareem Hunt', 'RB', 299.8::numeric, false),
    ('Justice Hill', 'RB', 294.0::numeric, false),
    ('Indianapolis Colts', 'D/ST', 294.4::numeric, false),
    ('Emari Demercado', 'RB', 296.8::numeric, false),
    ('Tyler Higbee', 'TE', 292.3::numeric, false),
    ('Demond Claiborne', 'RB', 258.0::numeric, true),
    ('Will Reichard', 'K', 259.0::numeric, false),
    ('Samaje Perine', 'RB', 302.7::numeric, false),
    ('LeQuint Allen Jr.', 'RB', 296.0::numeric, false),
    ('Tahj Brooks', 'RB', 304.2::numeric, false),
    ('John Bates', 'TE', 299.5::numeric, false),
    ('Darnell Washington', 'TE', 291.0::numeric, false),
    ('Xavier Hutchinson', 'WR', 309.8::numeric, false),
    ('Jalen Royals', 'WR', 303.0::numeric, false),
    ('Joshua Palmer', 'WR', 309.6::numeric, false),
    ('Olamide Zaccheaus', 'WR', 307.7::numeric, false),
    ('Jalen Nailor', 'WR', 311.8::numeric, false),
    ('Tua Tagovailoa', 'QB', 304.7::numeric, false),
    ('John Metchie III', 'WR', 307.2::numeric, false),
    ('Nick Chubb', 'RB', 309.6::numeric, false),
    ('DeMario Douglas', 'WR', 313.6::numeric, false),
    ('Michael Mayer', 'TE', 293.3::numeric, false),
    ('Miami Dolphins', 'D/ST', 311.2::numeric, false),
    ('Chris Brooks', 'RB', 307.0::numeric, false),
    ('Greg Dulcich', 'TE', 297.5::numeric, false),
    ('Michael Carter', 'RB', 312.4::numeric, false),
    ('Zane Gonzalez', 'K', 313.8::numeric, false),
    ('Anthony Richardson Sr.', 'QB', 311.8::numeric, false),
    ('Terrell Jennings', 'RB', 327.0::numeric, false),
    ('Dameon Pierce', 'RB', 326.8::numeric, false),
    ('Joe Milton III', 'QB', 322.6::numeric, false),
    ('Antonio Gibson', 'RB', 329.3::numeric, false),
    ('Jawhar Jordan', 'RB', 313.8::numeric, false),
    ('Austin Ekeler', 'RB', 322.2::numeric, false),
    ('Geno Smith', 'QB', 321.2::numeric, false),
    ('Raheim Sanders', 'RB', 324.3::numeric, false),
    ('Will Shipley', 'RB', 322.6::numeric, false),
    ('Tyrod Taylor', 'QB', 308.0::numeric, false),
    ('Ty Simpson', 'QB', 316.5::numeric, true),
    ('Marcus Mariota', 'QB', 351.5::numeric, false)
),
aliases (input_name, db_name) AS (
  VALUES
    ('Patrick Mahomes II', 'Patrick Mahomes'),
    ('Deebo Samuel Sr.', 'Deebo Samuel'),
    ('Aaron Jones Sr.', 'Aaron Jones'),
    ('Anthony Richardson Sr.', 'Anthony Richardson'),
    ('Chris Godwin Jr.', 'Chris Godwin'),
    ('Brian Thomas Jr.', 'Brian Thomas'),
    ('Kyle Pitts Sr.', 'Kyle Pitts'),
    ('Michael Pittman Jr.', 'Michael Pittman'),
    ('Marvin Harrison Jr.', 'Marvin Harrison'),
    ('Ollie Gordon II', 'Ollie Gordon'),
    ('Chris Rodriguez Jr.', 'Chris Rodriguez'),
    ('Jonathon Brooks', 'Jonathan Brooks'),
    ('Travis Etienne Jr.', 'Travis Etienne'),
    ('Michael Penix Jr.', 'Michael Penix'),
    ('Thomas Fidone II', 'Thomas Fidone'),
    ('Erick All Jr.', 'Erick All')
),
lookup AS (
  SELECT
    p.input_name,
    p.position,
    p.avg_rank,
    p.is_fa,
    COALESCE(a.db_name, p.input_name) AS match_name
  FROM parsed p
  LEFT JOIN aliases a ON a.input_name = p.input_name
),
lookup_dedup AS (
  SELECT DISTINCT ON (match_name) input_name, position, avg_rank, is_fa, match_name
  FROM lookup
  ORDER BY match_name, avg_rank ASC
),

ins_baseline AS (
  INSERT INTO public.baseline_community_rankings (scoring_format, league_type, is_superflex, player_id, rank)
  SELECT
    'standard'::text,
    'season'::text,
    false,
    pl.id,
    l.avg_rank
  FROM lookup_dedup l
  INNER JOIN public.players pl ON pl.name = l.match_name AND pl.season = 2025
  ON CONFLICT (scoring_format, league_type, is_superflex, player_id)
  DO UPDATE SET rank = EXCLUDED.rank
)

INSERT INTO public.baseline_rookies (name, position, rank, scoring_format, league_type, is_superflex)
SELECT l.input_name, l.position, l.avg_rank, 'standard'::text, 'season'::text, false
FROM lookup_dedup l
WHERE l.is_fa = true
  AND NOT EXISTS (
    SELECT 1 FROM public.players p
    WHERE (p.name = l.match_name OR p.name = l.input_name) AND p.season = 2025
  )
  AND NOT EXISTS (
    SELECT 1 FROM public.baseline_rookies br
    WHERE br.name = l.input_name
      AND br.scoring_format = 'standard'
      AND br.league_type = 'season'
      AND br.is_superflex = false
  )
ON CONFLICT (scoring_format, league_type, is_superflex, name) DO NOTHING;
