-- Standard / dynasty / superflex baseline rankings
-- Inserts into baseline_community_rankings (matches players by name, season=2025)
-- Adds FA rookies to baseline_rookies if not in players or already in baseline_rookies

WITH parsed (input_name, position, avg_rank, is_fa) AS (
  VALUES
    ('Josh Allen', 'QB', 1::numeric, false),
    ('Bijan Robinson', 'RB', 2::numeric, false),
    ('Ja''Marr Chase', 'WR', 3::numeric, false),
    ('Drake Maye', 'QB', 4::numeric, false),
    ('Jaxon Smith-Njigba', 'WR', 5::numeric, false),
    ('Puka Nacua', 'WR', 6::numeric, false),
    ('Jahmyr Gibbs', 'RB', 7::numeric, false),
    ('Lamar Jackson', 'QB', 8::numeric, false),
    ('Malik Nabers', 'WR', 9::numeric, false),
    ('Amon-Ra St. Brown', 'WR', 10::numeric, false),
    ('Jayden Daniels', 'QB', 11::numeric, false),
    ('Brock Bowers', 'TE', 12::numeric, false),
    ('Justin Jefferson', 'WR', 13::numeric, false),
    ('Trey McBride', 'TE', 15::numeric, false),
    ('Joe Burrow', 'QB', 16::numeric, false),
    ('Caleb Williams', 'QB', 17::numeric, false),
    ('Ashton Jeanty', 'RB', 18::numeric, false),
    ('CeeDee Lamb', 'WR', 19::numeric, false),
    ('De''Von Achane', 'RB', 20::numeric, false),
    ('Justin Herbert', 'QB', 21::numeric, false),
    ('Jeremiyah Love', 'RB', 22::numeric, true),
    ('Drake London', 'WR', 23::numeric, false),
    ('Jalen Hurts', 'QB', 24::numeric, false),
    ('Omarion Hampton', 'RB', 25::numeric, false),
    ('Patrick Mahomes', 'QB', 26::numeric, false),
    ('Jaxson Dart', 'QB', 27::numeric, false),
    ('Jonathan Taylor', 'RB', 28::numeric, false),
    ('Bo Nix', 'QB', 29::numeric, false),
    ('Trevor Lawrence', 'QB', 31::numeric, false),
    ('Tetairoa McMillan', 'WR', 32::numeric, false),
    ('James Cook', 'RB', 33::numeric, false),
    ('Brock Purdy', 'QB', 34::numeric, false),
    ('George Pickens', 'WR', 35::numeric, false),
    ('Colston Loveland', 'TE', 36::numeric, false),
    ('Nico Collins', 'WR', 37::numeric, false),
    ('Makai Lemon', 'WR', 39::numeric, true),
    ('Carnell Tate', 'WR', 40::numeric, true),
    ('Jordan Love', 'QB', 41::numeric, false),
    ('Garrett Wilson', 'WR', 42::numeric, false),
    ('Tyler Warren', 'TE', 43::numeric, false),
    ('Chris Olave', 'WR', 44::numeric, false),
    ('Fernando Mendoza', 'QB', 45::numeric, true),
    ('Emeka Egbuka', 'WR', 46::numeric, false),
    ('Bucky Irving', 'RB', 47::numeric, false),
    ('TreVeyon Henderson', 'RB', 48::numeric, false),
    ('Christian McCaffrey', 'RB', 50::numeric, false),
    ('Dak Prescott', 'QB', 51::numeric, false),
    ('Breece Hall', 'RB', 52::numeric, false),
    ('Ladd McConkey', 'WR', 53::numeric, false),
    ('Rashee Rice', 'WR', 54::numeric, false),
    ('Quinshon Judkins', 'RB', 56::numeric, false),
    ('Chase Brown', 'RB', 57::numeric, false),
    ('Marvin Harrison Jr', 'WR', 58::numeric, false),
    ('Jordyn Tyson', 'WR', 59::numeric, true),
    ('Saquon Barkley', 'RB', 60::numeric, false),
    ('Baker Mayfield', 'QB', 61::numeric, false),
    ('Cam Ward', 'QB', 62::numeric, false),
    ('Brian Thomas', 'WR', 63::numeric, false),
    ('Kyren Williams', 'RB', 64::numeric, false),
    ('Rome Odunze', 'WR', 65::numeric, false),
    ('C.J. Stroud', 'QB', 66::numeric, false),
    ('Jared Goff', 'QB', 67::numeric, false),
    ('Kenneth Walker', 'RB', 68::numeric, false),
    ('A.J. Brown', 'WR', 69::numeric, false),
    ('Tee Higgins', 'WR', 70::numeric, false),
    ('Harold Fannin', 'TE', 71::numeric, false),
    ('Josh Jacobs', 'RB', 72::numeric, false),
    ('Tucker Kraft', 'TE', 73::numeric, false),
    ('Zay Flowers', 'WR', 74::numeric, false),
    ('Cam Skattebo', 'RB', 76::numeric, false),
    ('Sam LaPorta', 'TE', 80::numeric, false),
    ('Luther Burden', 'WR', 81::numeric, false),
    ('Jameson Williams', 'WR', 82::numeric, false),
    ('Denzel Boston', 'WR', 83::numeric, true),
    ('Sam Darnold', 'QB', 84::numeric, false),
    ('Kyle Pitts', 'TE', 85::numeric, false),
    ('Jonah Coleman', 'RB', 86::numeric, true),
    ('DeVonta Smith', 'WR', 87::numeric, false),
    ('Tyler Shough', 'QB', 89::numeric, false),
    ('Bryce Young', 'QB', 90::numeric, false),
    ('Jaylen Waddle', 'WR', 91::numeric, false),
    ('Kenyon Sadiq', 'TE', 92::numeric, true),
    ('RJ Harvey', 'RB', 93::numeric, false),
    ('Travis Etienne', 'RB', 94::numeric, false),
    ('KC Concepcion', 'WR', 95::numeric, true),
    ('Javonte Williams', 'RB', 97::numeric, false),
    ('Kyler Murray', 'QB', 98::numeric, false),
    ('Derrick Henry', 'RB', 99::numeric, false),
    ('Matthew Stafford', 'QB', 100::numeric, false),
    ('Daniel Jones', 'QB', 102::numeric, false),
    ('Oronde Gadsden', 'TE', 103::numeric, false),
    ('Travis Hunter', 'WR', 105::numeric, false),
    ('Jadarian Price', 'RB', 106::numeric, true),
    ('J.J. McCarthy', 'QB', 108::numeric, false),
    ('Jordan Addison', 'WR', 109::numeric, false),
    ('DK Metcalf', 'WR', 110::numeric, false),
    ('Ricky Pearsall', 'WR', 112::numeric, false),
    ('D''Andre Swift', 'RB', 113::numeric, false),
    ('Michael Pittman', 'WR', 114::numeric, false),
    ('Terry McLaurin', 'WR', 115::numeric, false),
    ('Davante Adams', 'WR', 116::numeric, false),
    ('Emmett Johnson', 'RB', 117::numeric, true),
    ('Alec Pierce', 'WR', 118::numeric, false),
    ('Michael Penix', 'QB', 119::numeric, false),
    ('George Kittle', 'TE', 120::numeric, false),
    ('Malik Willis', 'QB', 121::numeric, false),
    ('Michael Wilson', 'WR', 122::numeric, false),
    ('Dalton Kincaid', 'TE', 124::numeric, false),
    ('Jake Ferguson', 'TE', 125::numeric, false),
    ('Eli Stowers', 'TE', 126::numeric, true),
    ('Matthew Golden', 'WR', 127::numeric, false),
    ('Nicholas Singleton', 'RB', 128::numeric, true),
    ('Jayden Higgins', 'WR', 130::numeric, false),
    ('Ty Simpson', 'QB', 131::numeric, true),
    ('Xavier Worthy', 'WR', 132::numeric, false),
    ('Parker Washington', 'WR', 133::numeric, false),
    ('Wan''Dale Robinson', 'WR', 134::numeric, false),
    ('Christian Watson', 'WR', 135::numeric, false),
    ('Bhayshul Tuten', 'RB', 136::numeric, false),
    ('Quentin Johnston', 'WR', 138::numeric, false),
    ('Kyle Monangai', 'RB', 139::numeric, false),
    ('Jaylen Warren', 'RB', 140::numeric, false),
    ('Courtland Sutton', 'WR', 141::numeric, false),
    ('Shedeur Sanders', 'QB', 142::numeric, false),
    ('Mike Evans', 'WR', 143::numeric, false),
    ('Zach Charbonnet', 'RB', 145::numeric, false),
    ('Tyler Allgeier', 'RB', 146::numeric, false),
    ('Jakobi Meyers', 'WR', 147::numeric, false),
    ('DJ Moore', 'WR', 148::numeric, false),
    ('Chuba Hubbard', 'RB', 149::numeric, false),
    ('Trey Benson', 'RB', 150::numeric, false),
    ('Omar Cooper', 'WR', 151::numeric, true),
    ('Brenton Strange', 'TE', 152::numeric, false),
    ('Rico Dowdle', 'RB', 154::numeric, false),
    ('Tua Tagovailoa', 'QB', 155::numeric, false),
    ('Blake Corum', 'RB', 156::numeric, false),
    ('Zachariah Branch', 'WR', 157::numeric, true),
    ('Jayden Reed', 'WR', 159::numeric, false),
    ('Isaiah Likely', 'TE', 160::numeric, false),
    ('David Montgomery', 'RB', 161::numeric, false),
    ('Khalil Shakir', 'WR', 162::numeric, false),
    ('Brandon Aiyuk', 'WR', 163::numeric, false),
    ('Chris Bell', 'WR', 164::numeric, true),
    ('Elijah Sarratt', 'WR', 167::numeric, true),
    ('Josh Downs', 'WR', 168::numeric, false),
    ('Tyreek Hill', 'WR', 169::numeric, false),
    ('Chris Brazzell', 'WR', 170::numeric, true),
    ('Rhamondre Stevenson', 'RB', 171::numeric, false),
    ('Mike Washington', 'RB', 172::numeric, true),
    ('Theo Johnson', 'TE', 173::numeric, false),
    ('Jalen Coker', 'WR', 174::numeric, false),
    ('Jauan Jennings', 'WR', 175::numeric, false),
    ('Woody Marks', 'RB', 177::numeric, false),
    ('Jonathon Brooks', 'RB', 178::numeric, false),
    ('Chris Godwin', 'WR', 179::numeric, false),
    ('Mac Jones', 'QB', 180::numeric, false),
    ('Romeo Doubs', 'WR', 181::numeric, false),
    ('Mason Taylor', 'TE', 182::numeric, false),
    ('Kenneth Gainwell', 'RB', 183::numeric, false),
    ('Tyrone Tracy', 'RB', 184::numeric, false),
    ('Germie Bernard', 'WR', 186::numeric, true),
    ('Kaleb Johnson', 'RB', 187::numeric, false),
    ('Terrance Ferguson', 'TE', 188::numeric, false),
    ('Demond Claiborne', 'RB', 189::numeric, true),
    ('David Njoku', 'TE', 190::numeric, false),
    ('Stefon Diggs', 'WR', 191::numeric, false),
    ('Troy Franklin', 'WR', 192::numeric, false),
    ('Kayshon Boutte', 'WR', 193::numeric, false),
    ('J.K. Dobbins', 'RB', 194::numeric, false),
    ('AJ Barner', 'TE', 196::numeric, false),
    ('Tre'' Harris', 'WR', 197::numeric, false),
    ('T.J. Hockenson', 'TE', 198::numeric, false),
    ('Pat Bryant', 'WR', 199::numeric, false),
    ('Braelon Allen', 'RB', 200::numeric, false),
    ('Rachaad White', 'RB', 202::numeric, false),
    ('Ja''Kobi Lane', 'WR', 203::numeric, true),
    ('Jacory Croskey-Merritt', 'RB', 204::numeric, false),
    ('Alvin Kamara', 'RB', 205::numeric, false),
    ('Max Klare', 'TE', 206::numeric, true),
    ('Deebo Samuel', 'WR', 207::numeric, false),
    ('Keon Coleman', 'WR', 208::numeric, false),
    ('Jerry Jeudy', 'WR', 209::numeric, false),
    ('Anthony Richardson', 'QB', 210::numeric, false),
    ('Juwan Johnson', 'TE', 211::numeric, false),
    ('Mark Andrews', 'TE', 212::numeric, false),
    ('Antonio Williams', 'WR', 213::numeric, true),
    ('Tyjae Spears', 'RB', 215::numeric, false),
    ('Dallas Goedert', 'TE', 216::numeric, false),
    ('Elic Ayomanor', 'WR', 217::numeric, false),
    ('Malachi Fields', 'WR', 218::numeric, true),
    ('Carson Beck', 'QB', 219::numeric, true),
    ('Chimere Dike', 'WR', 220::numeric, false),
    ('Tony Pollard', 'RB', 221::numeric, false),
    ('Jalen McMillan', 'WR', 223::numeric, false),
    ('Isaac TeSlaa', 'WR', 224::numeric, false),
    ('Rashid Shaheed', 'WR', 225::numeric, false),
    ('Devin Neal', 'RB', 227::numeric, false),
    ('Tory Horton', 'WR', 228::numeric, false),
    ('Le''Veon Moss', 'RB', 229::numeric, true),
    ('Adonai Mitchell', 'WR', 230::numeric, false),
    ('Dylan Sampson', 'RB', 232::numeric, false),
    ('Jaylin Noel', 'WR', 233::numeric, false),
    ('Jordan Mason', 'RB', 234::numeric, false),
    ('Adam Randall', 'RB', 235::numeric, true),
    ('Kimani Vidal', 'RB', 236::numeric, false),
    ('Kyle Williams', 'WR', 239::numeric, false),
    ('Gunnar Helm', 'TE', 240::numeric, false),
    ('J''Mari Taylor', 'RB', 241::numeric, true),
    ('Eric McAlister', 'WR', 242::numeric, true),
    ('Jack Endries', 'TE', 243::numeric, true),
    ('CJ Daniels', 'WR', 244::numeric, true),
    ('Tank Dell', 'WR', 246::numeric, false),
    ('Ted Hurst', 'WR', 247::numeric, true),
    ('Deion Burks', 'WR', 249::numeric, true),
    ('Ollie Gordon', 'RB', 250::numeric, false),
    ('Jack Bech', 'WR', 253::numeric, false),
    ('Jacoby Brissett', 'QB', 254::numeric, false),
    ('Brenen Thompson', 'WR', 255::numeric, true),
    ('Joe Mixon', 'RB', 258::numeric, false),
    ('Travis Kelce', 'TE', 260::numeric, false),
    ('Sean Tucker', 'RB', 261::numeric, false),
    ('Hunter Henry', 'TE', 263::numeric, false),
    ('Oscar Delp', 'TE', 264::numeric, true),
    ('Jake Tonges', 'TE', 265::numeric, false),
    ('Isiah Pacheco', 'RB', 267::numeric, false),
    ('Tank Bigsby', 'RB', 268::numeric, false),
    ('Aaron Jones', 'RB', 269::numeric, false),
    ('James Conner', 'RB', 271::numeric, false),
    ('CJ Donaldson', 'RB', 273::numeric, true),
    ('Drew Allar', 'QB', 275::numeric, true),
    ('Tre Tucker', 'WR', 276::numeric, false),
    ('Isaiah Bond', 'WR', 278::numeric, false),
    ('Aaron Rodgers', 'QB', 279::numeric, false),
    ('Colby Parkinson', 'TE', 280::numeric, false),
    ('Justin Fields', 'QB', 281::numeric, false),
    ('Brian Robinson', 'RB', 282::numeric, false),
    ('Dalton Schultz', 'TE', 284::numeric, false),
    ('Ben Sinnott', 'TE', 286::numeric, false),
    ('Cade Otton', 'TE', 287::numeric, false),
    ('Brashard Smith', 'RB', 288::numeric, false),
    ('Marlin Klein', 'TE', 289::numeric, true),
    ('Kirk Cousins', 'QB', 293::numeric, false),
    ('Jaydon Blue', 'RB', 294::numeric, false),
    ('Kevin Coleman', 'WR', 296::numeric, true),
    ('Elijah Arroyo', 'TE', 297::numeric, false),
    ('Taylen Green', 'QB', 301::numeric, true),
    ('Noah Thomas', 'WR', 302::numeric, true),
    ('Tez Johnson', 'WR', 304::numeric, false),
    ('Marvin Mims', 'WR', 305::numeric, false),
    ('Jalen Milroe', 'QB', 306::numeric, false),
    ('Josh Cameron', 'WR', 309::numeric, true),
    ('Will Howard', 'QB', 311::numeric, false),
    ('Dane Key', 'WR', 313::numeric, true),
    ('Dont''e Thornton', 'WR', 314::numeric, false),
    ('Jaylen Wright', 'RB', 315::numeric, false),
    ('Najee Harris', 'RB', 316::numeric, false),
    ('Hollywood Smothers', 'RB', 317::numeric, true),
    ('Cade Klubnik', 'QB', 318::numeric, true),
    ('Xavier Legette', 'WR', 319::numeric, false),
    ('Emanuel Wilson', 'RB', 320::numeric, false),
    ('Riley Leonard', 'QB', 321::numeric, false),
    ('Evan Engram', 'TE', 322::numeric, false),
    ('Joe Fagnano', 'QB', 323::numeric, true),
    ('Pat Freiermuth', 'TE', 324::numeric, false),
    ('Michael Mayer', 'TE', 325::numeric, false),
    ('Dylan Devezin', 'RB', 326::numeric, true),
    ('Quinn Ewers', 'QB', 327::numeric, false),
    ('Keaton Mitchell', 'RB', 328::numeric, false),
    ('Aaron Anderson', 'WR', 329::numeric, true),
    ('Malik Washington', 'WR', 330::numeric, false),
    ('Geno Smith', 'QB', 331::numeric, false),
    ('Keenan Allen', 'WR', 332::numeric, false),
    ('Chig Okonkwo', 'TE', 333::numeric, false),
    ('Kendre Miller', 'RB', 334::numeric, false),
    ('Chris Rodriguez', 'RB', 335::numeric, false),
    ('Calvin Ridley', 'WR', 336::numeric, false),
    ('Cole Kmet', 'TE', 337::numeric, false),
    ('DJ Giddens', 'RB', 338::numeric, false),
    ('Devaughn Vele', 'WR', 339::numeric, false),
    ('Ja''Tavion Sanders', 'TE', 340::numeric, false),
    ('Darren Waller', 'TE', 341::numeric, false),
    ('Cooper Kupp', 'WR', 342::numeric, false),
    ('Isaiah Davis', 'RB', 343::numeric, false),
    ('Cedric Tillman', 'WR', 344::numeric, false),
    ('Audric Estime', 'RB', 345::numeric, false),
    ('Rashod Bateman', 'WR', 346::numeric, false),
    ('Dontayvion Wicks', 'WR', 347::numeric, false),
    ('Zach Ertz', 'TE', 348::numeric, false),
    ('Ryan Flournoy', 'WR', 349::numeric, false),
    ('Deshaun Watson', 'QB', 350::numeric, false),
    ('Darnell Mooney', 'WR', 351::numeric, false),
    ('Kareem Hunt', 'RB', 352::numeric, false),
    ('John Metchie', 'WR', 353::numeric, false),
    ('Marcus Mariota', 'QB', 354::numeric, false),
    ('DeMario Douglas', 'WR', 355::numeric, false),
    ('Ray Davis', 'RB', 356::numeric, false),
    ('Devin Singletary', 'RB', 357::numeric, false),
    ('Tahj Brooks', 'RB', 358::numeric, false),
    ('Dillon Gabriel', 'QB', 359::numeric, false),
    ('Jalen Royals', 'WR', 360::numeric, false),
    ('Jordan James', 'RB', 361::numeric, false),
    ('Christian Kirk', 'WR', 362::numeric, false),
    ('Marquise Brown', 'WR', 363::numeric, false),
    ('Trevor Etienne', 'RB', 364::numeric, false),
    ('Joe Milton', 'QB', 365::numeric, false),
    ('Jameis Winston', 'QB', 366::numeric, false),
    ('Jaylin Lane', 'WR', 367::numeric, false),
    ('Davis Mills', 'QB', 368::numeric, false),
    ('Zonovan Knight', 'RB', 369::numeric, false),
    ('LeQuint Allen', 'RB', 370::numeric, false),
    ('Darius Slayton', 'WR', 371::numeric, false),
    ('Roman Wilson', 'WR', 372::numeric, false),
    ('Jalen Nailor', 'WR', 373::numeric, false),
    ('Darnell Washington', 'TE', 374::numeric, false),
    ('Michael Carter', 'RB', 375::numeric, false),
    ('Spencer Rattler', 'QB', 376::numeric, false),
    ('Luke McCaffrey', 'WR', 377::numeric, false),
    ('Will Levis', 'QB', 378::numeric, false),
    ('Max Brosmer', 'QB', 379::numeric, false),
    ('Luke Musgrave', 'TE', 380::numeric, false),
    ('Ja''Lynn Polk', 'WR', 381::numeric, false),
    ('MarShawn Lloyd', 'RB', 382::numeric, false),
    ('KeAndre Lambert-Smith', 'WR', 383::numeric, false),
    ('Jonnu Smith', 'TE', 384::numeric, false),
    ('Noah Gray', 'TE', 385::numeric, false),
    ('Joe Flacco', 'QB', 386::numeric, false),
    ('Nick Chubb', 'RB', 387::numeric, false),
    ('Jarquez Hunter', 'RB', 388::numeric, false),
    ('Dawson Knox', 'TE', 389::numeric, false),
    ('Andrei Iosivas', 'WR', 390::numeric, false),
    ('Savion Williams', 'WR', 391::numeric, false),
    ('Trey Lance', 'QB', 392::numeric, false),
    ('Mike Gesicki', 'TE', 393::numeric, false),
    ('Calvin Austin', 'WR', 394::numeric, false),
    ('Tyson Bagent', 'QB', 395::numeric, false),
    ('Jerome Ford', 'RB', 396::numeric, false),
    ('Jimmy Horn', 'WR', 397::numeric, false),
    ('Efton Chism', 'WR', 398::numeric, false),
    ('Isaac Guerendo', 'RB', 399::numeric, false),
    ('Tanner McKee', 'QB', 400::numeric, false),
    ('Xavier Hutchinson', 'WR', 401::numeric, false),
    ('Tyler Higbee', 'TE', 402::numeric, false),
    ('Greg Dulcich', 'TE', 403::numeric, false),
    ('Justice Hill', 'RB', 404::numeric, false),
    ('Malik Davis', 'RB', 405::numeric, false),
    ('Noah Fant', 'TE', 406::numeric, false),
    ('Mack Hollins', 'WR', 407::numeric, false),
    ('Treylon Burks', 'WR', 408::numeric, false),
    ('Xavier Restrepo', 'WR', 409::numeric, false),
    ('Russell Wilson', 'QB', 410::numeric, false),
    ('Tyler Huntley', 'QB', 411::numeric, false),
    ('Raheim Sanders', 'RB', 412::numeric, false),
    ('Jawhar Jordan', 'RB', 413::numeric, false),
    ('KaVontae Turpin', 'WR', 414::numeric, false),
    ('Austin Ekeler', 'RB', 415::numeric, false),
    ('Samaje Perine', 'RB', 416::numeric, false),
    ('Ty Johnson', 'RB', 417::numeric, false),
    ('Jordan Whittington', 'WR', 418::numeric, false),
    ('Nathan Carter', 'RB', 419::numeric, false),
    ('Tyquan Thornton', 'WR', 420::numeric, false),
    ('Tyrod Taylor', 'QB', 421::numeric, false),
    ('Roschon Johnson', 'RB', 422::numeric, false),
    ('Jahan Dotson', 'WR', 423::numeric, false),
    ('Konata Mumpfield', 'WR', 424::numeric, false),
    ('Tutu Atwell', 'WR', 425::numeric, false),
    ('Jahdae Walker', 'WR', 426::numeric, false),
    ('Will Shipley', 'RB', 427::numeric, false),
    ('Derek Carr', 'QB', 428::numeric, true),
    ('Jordan Watkins', 'WR', 429::numeric, false),
    ('Phil Mafah', 'RB', 430::numeric, false),
    ('Tai Felton', 'WR', 431::numeric, false),
    ('DeAndre Hopkins', 'WR', 432::numeric, false),
    ('Erick All', 'TE', 433::numeric, false),
    ('Joshua Palmer', 'WR', 434::numeric, false),
    ('Terrell Jennings', 'RB', 435::numeric, false),
    ('Jimmy Garoppolo', 'QB', 436::numeric, false),
    ('Mitchell Evans', 'TE', 437::numeric, false),
    ('Isaiah Williams', 'WR', 438::numeric, false),
    ('Jarrett Stidham', 'QB', 439::numeric, false),
    ('Sam Howell', 'QB', 440::numeric, false),
    ('Jackson Hawes', 'TE', 441::numeric, false),
    ('Malachi Corley', 'WR', 442::numeric, false),
    ('Olamide Zaccheaus', 'WR', 443::numeric, false),
    ('Darius Cooper', 'WR', 444::numeric, false),
    ('Demarcus Robinson', 'WR', 445::numeric, false),
    ('George Holani', 'RB', 446::numeric, false),
    ('Stetson Bennett', 'QB', 447::numeric, false)

),
aliases (input_name, db_name) AS (
  VALUES
    ('James Cook', 'James Cook III'),
    ('Marvin Harrison Jr', 'Marvin Harrison'),
    ('Harold Fannin', 'Harold Fannin Jr.'),
    ('Oronde Gadsden', 'Oronde Gadsden II'),
    ('Jonathon Brooks', 'Jonathan Brooks'),
    ('Travis Etienne', 'Travis Etienne Jr.'),
    ('Luther Burden', 'Luther Burden III'),
    ('Brian Thomas', 'Brian Thomas Jr.'),
    ('KC Concepcion', 'K.C. Concepcion'),
    ('Michael Pittman', 'Michael Pittman Jr.'),
    ('Brian Robinson', 'Brian Robinson Jr.'),
    ('LeQuint Allen', 'LeQuint Allen Jr.'),
    ('Dont''e Thornton', 'Dont''e Thornton Jr.'),
    ('Chris Rodriguez', 'Chris Rodriguez Jr.'),
    ('Ollie Gordon', 'Ollie Gordon II')
),
lookup AS (
  SELECT
    p.input_name,
    p.position,
    p.avg_rank,
    p.is_fa,
    COALESCE(a.db_name, p.input_name) AS match_name
  FROM parsed p
  LEFT JOIN aliases a ON a.input_name = p.input_name
),

ins_baseline AS (
  INSERT INTO public.baseline_community_rankings (scoring_format, league_type, is_superflex, player_id, rank)
  SELECT
    'standard'::text,
    'dynasty'::text,
    true,
    pl.id,
    l.avg_rank
  FROM lookup l
  INNER JOIN public.players pl ON pl.name = l.match_name AND pl.season = 2025
  ON CONFLICT (scoring_format, league_type, is_superflex, player_id)
  DO UPDATE SET rank = EXCLUDED.rank
)

INSERT INTO public.baseline_rookies (name, position, rank, scoring_format, league_type, is_superflex)
SELECT l.input_name, l.position, l.avg_rank, 'standard'::text, 'dynasty'::text, true
FROM lookup l
WHERE l.is_fa = true
  AND NOT EXISTS (
    SELECT 1 FROM public.players p
    WHERE (p.name = l.match_name OR p.name = l.input_name) AND p.season = 2025
  )
  AND NOT EXISTS (
    SELECT 1 FROM public.baseline_rookies br
    WHERE br.name = l.input_name
      AND br.scoring_format = 'standard'
      AND br.league_type = 'dynasty'
      AND br.is_superflex = true
  )
ON CONFLICT (scoring_format, league_type, is_superflex, name) DO NOTHING;
