-- 1/2 PPR / dynasty / non-superflex baseline rankings
-- Inserts into baseline_community_rankings (matches players by name, season=2025)
-- Adds FA rookies to baseline_rookies if not in players or already in baseline_rookies

WITH parsed (input_name, position, avg_rank, is_fa) AS (
  VALUES
    ('Bijan Robinson', 'RB', 1::numeric, false),
    ('Jahmyr Gibbs', 'RB', 2::numeric, false),
    ('Jaxon Smith-Njigba', 'WR', 3::numeric, false),
    ('Ja''Marr Chase', 'WR', 4::numeric, false),
    ('Puka Nacua', 'WR', 5::numeric, false),
    ('Malik Nabers', 'WR', 6::numeric, false),
    ('Amon-Ra St. Brown', 'WR', 7::numeric, false),
    ('Ashton Jeanty', 'RB', 8::numeric, false),
    ('Justin Jefferson', 'WR', 9::numeric, false),
    ('De''Von Achane', 'RB', 10::numeric, false),
    ('Brock Bowers', 'TE', 11::numeric, false),
    ('CeeDee Lamb', 'WR', 13::numeric, false),
    ('Jeremiyah Love', 'RB', 14::numeric, true),
    ('Trey McBride', 'TE', 15::numeric, false),
    ('Omarion Hampton', 'RB', 16::numeric, false),
    ('Drake London', 'WR', 17::numeric, false),
    ('Jonathan Taylor', 'RB', 18::numeric, false),
    ('Josh Allen', 'QB', 19::numeric, false),
    ('James Cook', 'RB', 20::numeric, false),
    ('Drake Maye', 'QB', 21::numeric, false),
    ('Tetairoa McMillan', 'WR', 22::numeric, false),
    ('George Pickens', 'WR', 23::numeric, false),
    ('Nico Collins', 'WR', 24::numeric, false),
    ('Bucky Irving', 'RB', 25::numeric, false),
    ('TreVeyon Henderson', 'RB', 26::numeric, false),
    ('Makai Lemon', 'WR', 27::numeric, true),
    ('Carnell Tate', 'WR', 28::numeric, true),
    ('Christian McCaffrey', 'RB', 29::numeric, false),
    ('Breece Hall', 'RB', 31::numeric, false),
    ('Colston Loveland', 'TE', 32::numeric, false),
    ('Emeka Egbuka', 'WR', 33::numeric, false),
    ('Chris Olave', 'WR', 34::numeric, false),
    ('Garrett Wilson', 'WR', 35::numeric, false),
    ('Chase Brown', 'RB', 36::numeric, false),
    ('Quinshon Judkins', 'RB', 37::numeric, false),
    ('Lamar Jackson', 'QB', 39::numeric, false),
    ('Saquon Barkley', 'RB', 40::numeric, false),
    ('Tyler Warren', 'TE', 41::numeric, false),
    ('Jayden Daniels', 'QB', 42::numeric, false),
    ('Ladd McConkey', 'WR', 43::numeric, false),
    ('Kyren Williams', 'RB', 44::numeric, false),
    ('Rashee Rice', 'WR', 45::numeric, false),
    ('Marvin Harrison Jr', 'WR', 46::numeric, false),
    ('Joe Burrow', 'QB', 47::numeric, false),
    ('Jordyn Tyson', 'WR', 49::numeric, true),
    ('Caleb Williams', 'QB', 50::numeric, false),
    ('Kenneth Walker', 'RB', 51::numeric, false),
    ('Brian Thomas', 'WR', 52::numeric, false),
    ('Rome Odunze', 'WR', 53::numeric, false),
    ('Josh Jacobs', 'RB', 54::numeric, false),
    ('Cam Skattebo', 'RB', 55::numeric, false),
    ('A.J. Brown', 'WR', 56::numeric, false),
    ('Tee Higgins', 'WR', 57::numeric, false),
    ('Justin Herbert', 'QB', 58::numeric, false),
    ('Zay Flowers', 'WR', 59::numeric, false),
    ('Jalen Hurts', 'QB', 60::numeric, false),
    ('Jonah Coleman', 'RB', 61::numeric, true),
    ('Patrick Mahomes', 'QB', 63::numeric, false),
    ('Luther Burden', 'WR', 64::numeric, false),
    ('Denzel Boston', 'WR', 65::numeric, true),
    ('Jameson Williams', 'WR', 66::numeric, false),
    ('RJ Harvey', 'RB', 67::numeric, false),
    ('Harold Fannin', 'TE', 68::numeric, false),
    ('Travis Etienne', 'RB', 69::numeric, false),
    ('Tucker Kraft', 'TE', 70::numeric, false),
    ('Jaxson Dart', 'QB', 71::numeric, false),
    ('DeVonta Smith', 'WR', 72::numeric, false),
    ('Javonte Williams', 'RB', 74::numeric, false),
    ('Sam LaPorta', 'TE', 75::numeric, false),
    ('Derrick Henry', 'RB', 76::numeric, false),
    ('Jaylen Waddle', 'WR', 77::numeric, false),
    ('Bo Nix', 'QB', 78::numeric, false),
    ('Trevor Lawrence', 'QB', 82::numeric, false),
    ('KC Concepcion', 'WR', 83::numeric, true),
    ('Kyle Pitts', 'TE', 84::numeric, false),
    ('Brock Purdy', 'QB', 85::numeric, false),
    ('Kenyon Sadiq', 'TE', 86::numeric, true),
    ('Jadarian Price', 'RB', 88::numeric, true),
    ('D''Andre Swift', 'RB', 89::numeric, false),
    ('Travis Hunter', 'WR', 90::numeric, false),
    ('Emmett Johnson', 'RB', 92::numeric, true),
    ('Jordan Love', 'QB', 93::numeric, false),
    ('Oronde Gadsden', 'TE', 94::numeric, false),
    ('Fernando Mendoza', 'QB', 95::numeric, true),
    ('Jordan Addison', 'WR', 96::numeric, false),
    ('DK Metcalf', 'WR', 97::numeric, false),
    ('Ricky Pearsall', 'WR', 99::numeric, false),
    ('Nicholas Singleton', 'RB', 100::numeric, true),
    ('Michael Pittman', 'WR', 102::numeric, false),
    ('Davante Adams', 'WR', 103::numeric, false),
    ('Alec Pierce', 'WR', 104::numeric, false),
    ('Dak Prescott', 'QB', 105::numeric, false),
    ('Terry McLaurin', 'WR', 106::numeric, false),
    ('Michael Wilson', 'WR', 107::numeric, false),
    ('Bhayshul Tuten', 'RB', 108::numeric, false),
    ('Matthew Golden', 'WR', 110::numeric, false),
    ('Kyle Monangai', 'RB', 111::numeric, false),
    ('Jaylen Warren', 'RB', 112::numeric, false),
    ('Jayden Higgins', 'WR', 113::numeric, false),
    ('George Kittle', 'TE', 114::numeric, false),
    ('Zach Charbonnet', 'RB', 115::numeric, false),
    ('Wan''Dale Robinson', 'WR', 116::numeric, false),
    ('Baker Mayfield', 'QB', 117::numeric, false),
    ('Cam Ward', 'QB', 119::numeric, false),
    ('Tyler Allgeier', 'RB', 120::numeric, false),
    ('Christian Watson', 'WR', 121::numeric, false),
    ('Xavier Worthy', 'WR', 122::numeric, false),
    ('Parker Washington', 'WR', 123::numeric, false),
    ('Eli Stowers', 'TE', 124::numeric, true),
    ('Dalton Kincaid', 'TE', 125::numeric, false),
    ('Jake Ferguson', 'TE', 126::numeric, false),
    ('Chuba Hubbard', 'RB', 127::numeric, false),
    ('Trey Benson', 'RB', 128::numeric, false),
    ('C.J. Stroud', 'QB', 129::numeric, false),
    ('Quentin Johnston', 'WR', 130::numeric, false),
    ('Courtland Sutton', 'WR', 131::numeric, false),
    ('Rico Dowdle', 'RB', 132::numeric, false),
    ('Jared Goff', 'QB', 134::numeric, false),
    ('Blake Corum', 'RB', 135::numeric, false),
    ('Mike Evans', 'WR', 136::numeric, false),
    ('Jakobi Meyers', 'WR', 137::numeric, false),
    ('DJ Moore', 'WR', 138::numeric, false),
    ('David Montgomery', 'RB', 139::numeric, false),
    ('Omar Cooper', 'WR', 141::numeric, true),
    ('Mike Washington', 'RB', 142::numeric, true),
    ('Jonathon Brooks', 'RB', 143::numeric, false),
    ('Rhamondre Stevenson', 'RB', 144::numeric, false),
    ('Woody Marks', 'RB', 145::numeric, false),
    ('Zachariah Branch', 'WR', 146::numeric, true),
    ('Kenneth Gainwell', 'RB', 147::numeric, false),
    ('Sam Darnold', 'QB', 148::numeric, false),
    ('Tyrone Tracy', 'RB', 150::numeric, false),
    ('Jayden Reed', 'WR', 151::numeric, false),
    ('J.K. Dobbins', 'RB', 152::numeric, false),
    ('Demond Claiborne', 'RB', 153::numeric, true),
    ('Brandon Aiyuk', 'WR', 154::numeric, false),
    ('Chris Bell', 'WR', 155::numeric, true),
    ('Kaleb Johnson', 'RB', 156::numeric, false),
    ('Khalil Shakir', 'WR', 157::numeric, false),
    ('Tyreek Hill', 'WR', 158::numeric, false),
    ('Elijah Sarratt', 'WR', 159::numeric, true),
    ('Josh Downs', 'WR', 160::numeric, false),
    ('Chris Brazzell', 'WR', 161::numeric, true),
    ('Braelon Allen', 'RB', 162::numeric, false),
    ('Brenton Strange', 'TE', 163::numeric, false),
    ('Jacory Croskey-Merritt', 'RB', 164::numeric, false),
    ('Jalen Coker', 'WR', 165::numeric, false),
    ('Alvin Kamara', 'RB', 166::numeric, false),
    ('Jauan Jennings', 'WR', 167::numeric, false),
    ('Rachaad White', 'RB', 168::numeric, false),
    ('Chris Godwin', 'WR', 170::numeric, false),
    ('Romeo Doubs', 'WR', 171::numeric, false),
    ('Tyler Shough', 'QB', 172::numeric, false),
    ('Bryce Young', 'QB', 173::numeric, false),
    ('Tyjae Spears', 'RB', 174::numeric, false),
    ('Germie Bernard', 'WR', 175::numeric, true),
    ('Isaiah Likely', 'TE', 177::numeric, false),
    ('Kayshon Boutte', 'WR', 178::numeric, false),
    ('Troy Franklin', 'WR', 179::numeric, false),
    ('Tony Pollard', 'RB', 181::numeric, false),
    ('Stefon Diggs', 'WR', 182::numeric, false),
    ('Theo Johnson', 'TE', 183::numeric, false),
    ('Tre'' Harris', 'WR', 184::numeric, false),
    ('Pat Bryant', 'WR', 185::numeric, false),
    ('Kyler Murray', 'QB', 186::numeric, false),
    ('Ja''Kobi Lane', 'WR', 187::numeric, true),
    ('Jerry Jeudy', 'WR', 188::numeric, false),
    ('Deebo Samuel', 'WR', 189::numeric, false),
    ('Mason Taylor', 'TE', 191::numeric, false),
    ('Keon Coleman', 'WR', 192::numeric, false),
    ('Antonio Williams', 'WR', 193::numeric, true),
    ('Devin Neal', 'RB', 194::numeric, false),
    ('Terrance Ferguson', 'TE', 196::numeric, false),
    ('Le''Veon Moss', 'RB', 197::numeric, true),
    ('Elic Ayomanor', 'WR', 198::numeric, false),
    ('David Njoku', 'TE', 199::numeric, false),
    ('Malachi Fields', 'WR', 201::numeric, true),
    ('Dylan Sampson', 'RB', 202::numeric, false),
    ('Chimere Dike', 'WR', 204::numeric, false),
    ('AJ Barner', 'TE', 205::numeric, false),
    ('Adam Randall', 'RB', 206::numeric, true),
    ('T.J. Hockenson', 'TE', 207::numeric, false),
    ('Matthew Stafford', 'QB', 208::numeric, false),
    ('Jordan Mason', 'RB', 209::numeric, false),
    ('Kimani Vidal', 'RB', 210::numeric, false),
    ('Isaac TeSlaa', 'WR', 211::numeric, false),
    ('Daniel Jones', 'QB', 212::numeric, false),
    ('Max Klare', 'TE', 213::numeric, true),
    ('Jalen McMillan', 'WR', 214::numeric, false),
    ('Rashid Shaheed', 'WR', 216::numeric, false),
    ('Dallas Goedert', 'TE', 217::numeric, false),
    ('Mark Andrews', 'TE', 218::numeric, false),
    ('Juwan Johnson', 'TE', 219::numeric, false),
    ('Tory Horton', 'WR', 220::numeric, false),
    ('J''Mari Taylor', 'RB', 221::numeric, true),
    ('Adonai Mitchell', 'WR', 223::numeric, false),
    ('Jaylin Noel', 'WR', 224::numeric, false),
    ('J.J. McCarthy', 'QB', 225::numeric, false),
    ('Ollie Gordon', 'RB', 227::numeric, false),
    ('Kyle Williams', 'WR', 228::numeric, false),
    ('Eric McAlister', 'WR', 230::numeric, true),
    ('Michael Penix', 'QB', 231::numeric, false),
    ('CJ Daniels', 'WR', 232::numeric, true),
    ('Tank Dell', 'WR', 233::numeric, false),
    ('Malik Willis', 'QB', 234::numeric, false),
    ('Ted Hurst', 'WR', 236::numeric, true),
    ('Deion Burks', 'WR', 237::numeric, true),
    ('Sean Tucker', 'RB', 238::numeric, false),
    ('Joe Mixon', 'RB', 239::numeric, false),
    ('Gunnar Helm', 'TE', 241::numeric, false),
    ('Tank Bigsby', 'RB', 242::numeric, false),
    ('Isiah Pacheco', 'RB', 243::numeric, false),
    ('Brenen Thompson', 'WR', 244::numeric, true),
    ('Jack Bech', 'WR', 245::numeric, false),
    ('Jack Endries', 'TE', 246::numeric, true),
    ('Aaron Jones', 'RB', 247::numeric, false),
    ('Ty Simpson', 'QB', 249::numeric, true),
    ('CJ Donaldson', 'RB', 250::numeric, true),
    ('James Conner', 'RB', 251::numeric, false),
    ('Shedeur Sanders', 'QB', 255::numeric, false),
    ('Brian Robinson', 'RB', 256::numeric, false),
    ('Travis Kelce', 'TE', 258::numeric, false),
    ('Brashard Smith', 'RB', 260::numeric, false),
    ('Hunter Henry', 'TE', 261::numeric, false),
    ('Jake Tonges', 'TE', 263::numeric, false),
    ('Oscar Delp', 'TE', 264::numeric, true),
    ('Jaydon Blue', 'RB', 266::numeric, false),
    ('Tua Tagovailoa', 'QB', 267::numeric, false),
    ('Tre Tucker', 'WR', 268::numeric, false),
    ('Isaiah Bond', 'WR', 270::numeric, false),
    ('Dalton Schultz', 'TE', 274::numeric, false),
    ('Kevin Coleman', 'WR', 275::numeric, true),
    ('Colby Parkinson', 'TE', 276::numeric, false),
    ('Mac Jones', 'QB', 278::numeric, false),
    ('Ben Sinnott', 'TE', 280::numeric, false),
    ('Marlin Klein', 'TE', 282::numeric, true),
    ('Noah Thomas', 'WR', 283::numeric, true),
    ('Marvin Mims', 'WR', 285::numeric, false),
    ('Najee Harris', 'RB', 286::numeric, false),
    ('Tez Johnson', 'WR', 288::numeric, false),
    ('Hollywood Smothers', 'RB', 290::numeric, true),
    ('Anthony Richardson', 'QB', 291::numeric, false),
    ('Jaylen Wright', 'RB', 292::numeric, false),
    ('Cade Otton', 'TE', 293::numeric, false),
    ('Josh Cameron', 'WR', 295::numeric, true),
    ('Emanuel Wilson', 'RB', 296::numeric, false),
    ('Elijah Arroyo', 'TE', 297::numeric, false),
    ('Carson Beck', 'QB', 298::numeric, true),
    ('Dont''e Thornton', 'WR', 299::numeric, false),
    ('Dylan Devezin', 'RB', 301::numeric, true),
    ('Dane Key', 'WR', 302::numeric, true),
    ('Xavier Legette', 'WR', 304::numeric, false),
    ('Keaton Mitchell', 'RB', 306::numeric, false),
    ('Aaron Anderson', 'WR', 311::numeric, true),
    ('Evan Engram', 'TE', 313::numeric, false),
    ('Michael Mayer', 'TE', 315::numeric, false),
    ('Pat Freiermuth', 'TE', 317::numeric, false),
    ('Malik Washington', 'WR', 318::numeric, false),
    ('Keenan Allen', 'WR', 319::numeric, false),
    ('Chris Rodriguez', 'RB', 320::numeric, false),
    ('Kendre Miller', 'RB', 321::numeric, false),
    ('Jacoby Brissett', 'QB', 322::numeric, false),
    ('DJ Giddens', 'RB', 323::numeric, false),
    ('Calvin Ridley', 'WR', 324::numeric, false),
    ('Isaiah Davis', 'RB', 325::numeric, false),
    ('Chig Okonkwo', 'TE', 326::numeric, false),
    ('Devaughn Vele', 'WR', 327::numeric, false),
    ('Audric Estime', 'RB', 328::numeric, false),
    ('Cooper Kupp', 'WR', 329::numeric, false),
    ('Cole Kmet', 'TE', 330::numeric, false),
    ('Drew Allar', 'QB', 331::numeric, true),
    ('Justin Fields', 'QB', 332::numeric, false),
    ('Aaron Rodgers', 'QB', 333::numeric, false),
    ('Ja''Tavion Sanders', 'TE', 334::numeric, false),
    ('Cedric Tillman', 'WR', 335::numeric, false),
    ('Kirk Cousins', 'QB', 336::numeric, false),
    ('Kareem Hunt', 'RB', 337::numeric, false),
    ('Darren Waller', 'TE', 338::numeric, false),
    ('Dontayvion Wicks', 'WR', 339::numeric, false),
    ('Rashod Bateman', 'WR', 340::numeric, false),
    ('Taylen Green', 'QB', 341::numeric, true),
    ('Ray Davis', 'RB', 342::numeric, false),
    ('Darnell Mooney', 'WR', 343::numeric, false),
    ('Ryan Flournoy', 'WR', 344::numeric, false),
    ('Devin Singletary', 'RB', 345::numeric, false),
    ('Jalen Milroe', 'QB', 346::numeric, false),
    ('Zach Ertz', 'TE', 347::numeric, false),
    ('DeMario Douglas', 'WR', 348::numeric, false),
    ('Tahj Brooks', 'RB', 349::numeric, false),
    ('Riley Leonard', 'QB', 350::numeric, false),
    ('Cade Klubnik', 'QB', 351::numeric, true),
    ('John Metchie', 'WR', 352::numeric, false),
    ('Will Howard', 'QB', 353::numeric, false),
    ('Joe Fagnano', 'QB', 354::numeric, true),
    ('Jordan James', 'RB', 355::numeric, false),
    ('Quinn Ewers', 'QB', 356::numeric, false),
    ('Trevor Etienne', 'RB', 357::numeric, false),
    ('Jalen Royals', 'WR', 358::numeric, false),
    ('Geno Smith', 'QB', 359::numeric, false),
    ('Zonovan Knight', 'RB', 360::numeric, false),
    ('LeQuint Allen', 'RB', 361::numeric, false),
    ('Christian Kirk', 'WR', 362::numeric, false),
    ('Marquise Brown', 'WR', 363::numeric, false),
    ('Jaylin Lane', 'WR', 364::numeric, false),
    ('Michael Carter', 'RB', 365::numeric, false),
    ('Darius Slayton', 'WR', 366::numeric, false),
    ('Roman Wilson', 'WR', 367::numeric, false),
    ('Jalen Nailor', 'WR', 368::numeric, false),
    ('Darnell Washington', 'TE', 369::numeric, false),
    ('MarShawn Lloyd', 'RB', 370::numeric, false),
    ('Deshaun Watson', 'QB', 371::numeric, false),
    ('Luke McCaffrey', 'WR', 372::numeric, false),
    ('Jarquez Hunter', 'RB', 373::numeric, false),
    ('Ja''Lynn Polk', 'WR', 374::numeric, false),
    ('KeAndre Lambert-Smith', 'WR', 375::numeric, false),
    ('Marcus Mariota', 'QB', 376::numeric, false),
    ('Noah Gray', 'TE', 377::numeric, false),
    ('Jonnu Smith', 'TE', 378::numeric, false),
    ('Dillon Gabriel', 'QB', 379::numeric, false),
    ('Andrei Iosivas', 'WR', 380::numeric, false),
    ('Nick Chubb', 'RB', 381::numeric, false),
    ('Luke Musgrave', 'TE', 382::numeric, false),
    ('Dawson Knox', 'TE', 383::numeric, false),
    ('Joe Milton', 'QB', 384::numeric, false),
    ('Calvin Austin', 'WR', 385::numeric, false),
    ('Jerome Ford', 'RB', 386::numeric, false),
    ('Mike Gesicki', 'TE', 387::numeric, false),
    ('Davis Mills', 'QB', 388::numeric, false),
    ('Savion Williams', 'WR', 389::numeric, false),
    ('Isaac Guerendo', 'RB', 390::numeric, false),
    ('Jameis Winston', 'QB', 391::numeric, false),
    ('Efton Chism', 'WR', 392::numeric, false),
    ('Spencer Rattler', 'QB', 393::numeric, false),
    ('Will Levis', 'QB', 394::numeric, false),
    ('Justice Hill', 'RB', 395::numeric, false),
    ('Max Brosmer', 'QB', 396::numeric, false),
    ('Greg Dulcich', 'TE', 397::numeric, false),
    ('Joe Flacco', 'QB', 398::numeric, false),
    ('Malik Davis', 'RB', 399::numeric, false),
    ('Xavier Hutchinson', 'WR', 400::numeric, false),
    ('Raheim Sanders', 'RB', 401::numeric, false),
    ('Mack Hollins', 'WR', 402::numeric, false),
    ('Jimmy Horn', 'WR', 403::numeric, false),
    ('Xavier Restrepo', 'WR', 404::numeric, false),
    ('Jawhar Jordan', 'RB', 405::numeric, false),
    ('Treylon Burks', 'WR', 406::numeric, false),
    ('Austin Ekeler', 'RB', 407::numeric, false),
    ('Samaje Perine', 'RB', 408::numeric, false),
    ('Ty Johnson', 'RB', 409::numeric, false),
    ('Noah Fant', 'TE', 410::numeric, false),
    ('Nathan Carter', 'RB', 411::numeric, false),
    ('Tyson Bagent', 'QB', 412::numeric, false),
    ('KaVontae Turpin', 'WR', 413::numeric, false),
    ('Tyler Higbee', 'TE', 414::numeric, false),
    ('Jordan Whittington', 'WR', 415::numeric, false),
    ('Tyquan Thornton', 'WR', 416::numeric, false),
    ('Roschon Johnson', 'RB', 417::numeric, false),
    ('Trey Lance', 'QB', 418::numeric, false),
    ('Will Shipley', 'RB', 419::numeric, false),
    ('Jahan Dotson', 'WR', 420::numeric, false),
    ('Konata Mumpfield', 'WR', 421::numeric, false),
    ('Tutu Atwell', 'WR', 422::numeric, false),
    ('Jahdae Walker', 'WR', 423::numeric, false),
    ('Phil Mafah', 'RB', 424::numeric, false),
    ('Tanner McKee', 'QB', 425::numeric, false),
    ('Jordan Watkins', 'WR', 426::numeric, false),
    ('Tai Felton', 'WR', 427::numeric, false),
    ('DeAndre Hopkins', 'WR', 428::numeric, false),
    ('Tyler Huntley', 'QB', 429::numeric, false),
    ('Erick All', 'TE', 430::numeric, false),
    ('Terrell Jennings', 'RB', 431::numeric, false),
    ('Joshua Palmer', 'WR', 432::numeric, false),
    ('Tyrod Taylor', 'QB', 433::numeric, false),
    ('Isaiah Williams', 'WR', 434::numeric, false),
    ('Mitchell Evans', 'TE', 435::numeric, false),
    ('Derek Carr', 'QB', 436::numeric, true),
    ('Jackson Hawes', 'TE', 437::numeric, false),
    ('Russell Wilson', 'QB', 438::numeric, false),
    ('Jimmy Garoppolo', 'QB', 439::numeric, false),
    ('Malachi Corley', 'WR', 440::numeric, false),
    ('Darius Cooper', 'WR', 441::numeric, false),
    ('Olamide Zaccheaus', 'WR', 442::numeric, false),
    ('Demarcus Robinson', 'WR', 443::numeric, false),
    ('Jarrett Stidham', 'QB', 444::numeric, false),
    ('Sam Howell', 'QB', 445::numeric, false),
    ('George Holani', 'RB', 446::numeric, false),
    ('Stetson Bennett', 'QB', 447::numeric, false)

),
aliases (input_name, db_name) AS (
  VALUES
    ('James Cook', 'James Cook III'),
    ('Marvin Harrison Jr', 'Marvin Harrison'),
    ('Harold Fannin', 'Harold Fannin Jr.'),
    ('Oronde Gadsden', 'Oronde Gadsden II'),
    ('Jonathon Brooks', 'Jonathan Brooks'),
    ('Travis Etienne', 'Travis Etienne Jr.'),
    ('Luther Burden', 'Luther Burden III'),
    ('Brian Thomas', 'Brian Thomas Jr.'),
    ('KC Concepcion', 'K.C. Concepcion'),
    ('Michael Pittman', 'Michael Pittman Jr.'),
    ('Brian Robinson', 'Brian Robinson Jr.'),
    ('LeQuint Allen', 'LeQuint Allen Jr.'),
    ('Dont''e Thornton', 'Dont''e Thornton Jr.'),
    ('Chris Rodriguez', 'Chris Rodriguez Jr.'),
    ('Ollie Gordon', 'Ollie Gordon II')
),
lookup AS (
  SELECT
    p.input_name,
    p.position,
    p.avg_rank,
    p.is_fa,
    COALESCE(a.db_name, p.input_name) AS match_name
  FROM parsed p
  LEFT JOIN aliases a ON a.input_name = p.input_name
),

ins_baseline AS (
  INSERT INTO public.baseline_community_rankings (scoring_format, league_type, is_superflex, player_id, rank)
  SELECT
    'half_ppr'::text,
    'dynasty'::text,
    false,
    pl.id,
    l.avg_rank
  FROM lookup l
  INNER JOIN public.players pl ON pl.name = l.match_name AND pl.season = 2025
  ON CONFLICT (scoring_format, league_type, is_superflex, player_id)
  DO UPDATE SET rank = EXCLUDED.rank
)

INSERT INTO public.baseline_rookies (name, position, rank, scoring_format, league_type, is_superflex)
SELECT l.input_name, l.position, l.avg_rank, 'half_ppr'::text, 'dynasty'::text, false
FROM lookup l
WHERE l.is_fa = true
  AND NOT EXISTS (
    SELECT 1 FROM public.players p
    WHERE (p.name = l.match_name OR p.name = l.input_name) AND p.season = 2025
  )
  AND NOT EXISTS (
    SELECT 1 FROM public.baseline_rookies br
    WHERE br.name = l.input_name
      AND br.scoring_format = 'half_ppr'
      AND br.league_type = 'dynasty'
      AND br.is_superflex = false
  )
ON CONFLICT (scoring_format, league_type, is_superflex, name) DO NOTHING;
