-- Rookies-only dynasty superflex baseline.
-- Same list for PPR, half-PPR, and standard (scoring_format = 'any').
-- Used when league has rookies_only=true, league_type=dynasty, is_superflex=true.

INSERT INTO public.baseline_rookies (name, position, rank, scoring_format, league_type, is_superflex)
VALUES
  ('Jeremiyah Love', 'RB', 1, 'any', 'dynasty', true),
  ('Fernando Mendoza', 'QB', 2, 'any', 'dynasty', true),
  ('Carnell Tate', 'WR', 3, 'any', 'dynasty', true),
  ('Makai Lemon', 'WR', 4, 'any', 'dynasty', true),
  ('Jordyn Tyson', 'WR', 5, 'any', 'dynasty', true),
  ('Jonah Coleman', 'RB', 6, 'any', 'dynasty', true),
  ('Denzel Boston', 'WR', 7, 'any', 'dynasty', true),
  ('K.C. Concepcion', 'WR', 8, 'any', 'dynasty', true),
  ('Jadarian Price', 'RB', 9, 'any', 'dynasty', true),
  ('Kenyon Sadiq', 'TE', 10, 'any', 'dynasty', true),
  ('Emmett Johnson', 'RB', 11, 'any', 'dynasty', true),
  ('Ty Simpson', 'QB', 12, 'any', 'dynasty', true),
  ('Eli Stowers', 'TE', 13, 'any', 'dynasty', true),
  ('Kaytron Allen', 'RB', 14, 'any', 'dynasty', true),
  ('Chris Bell', 'WR', 15, 'any', 'dynasty', true),
  ('Omar Cooper Jr.', 'WR', 16, 'any', 'dynasty', true),
  ('Nicholas Singleton', 'RB', 17, 'any', 'dynasty', true),
  ('Garrett Nussmeier', 'QB', 18, 'any', 'dynasty', true),
  ('Elijah Sarratt', 'WR', 19, 'any', 'dynasty', true),
  ('Chris Brazzell II', 'WR', 20, 'any', 'dynasty', true),
  ('Zachariah Branch', 'WR', 21, 'any', 'dynasty', true),
  ('Germie Bernard', 'WR', 22, 'any', 'dynasty', true),
  ('Mike Washington Jr.', 'RB', 23, 'any', 'dynasty', true),
  ('Malachi Fields', 'WR', 24, 'any', 'dynasty', true),
  ('Demond Claiborne', 'RB', 25, 'any', 'dynasty', true),
  ('Antonio Williams', 'WR', 26, 'any', 'dynasty', true),
  ('Ja''Kobi Lane', 'WR', 27, 'any', 'dynasty', true),
  ('J''Mari Taylor', 'RB', 28, 'any', 'dynasty', true),
  ('Max Klare', 'TE', 29, 'any', 'dynasty', true),
  ('Carson Beck', 'QB', 30, 'any', 'dynasty', true),
  ('Michael Trigg', 'TE', 31, 'any', 'dynasty', true),
  ('Drew Allar', 'QB', 32, 'any', 'dynasty', true),
  ('Le''Veon Moss', 'RB', 33, 'any', 'dynasty', true),
  ('Roman Hemby', 'RB', 34, 'any', 'dynasty', true),
  ('Skyler Bell', 'WR', 35, 'any', 'dynasty', true),
  ('Adam Randall', 'RB', 36, 'any', 'dynasty', true),
  ('Cade Klubnik', 'QB', 37, 'any', 'dynasty', true),
  ('Justin Joly', 'TE', 38, 'any', 'dynasty', true),
  ('Deion Burks', 'WR', 39, 'any', 'dynasty', true),
  ('Jaydn Ott', 'RB', 40, 'any', 'dynasty', true),
  ('Jam Miller', 'RB', 41, 'any', 'dynasty', true),
  ('Seth McGowan', 'RB', 42, 'any', 'dynasty', true),
  ('Jack Endries', 'TE', 43, 'any', 'dynasty', true),
  ('Cole Payton', 'QB', 44, 'any', 'dynasty', true),
  ('Kevin Coleman Jr.', 'WR', 45, 'any', 'dynasty', true),
  ('Eric McAlister', 'WR', 46, 'any', 'dynasty', true),
  ('Joe Royer', 'TE', 47, 'any', 'dynasty', true),
  ('Bryce Lance', 'WR', 48, 'any', 'dynasty', true),
  ('Barion Brown', 'WR', 49, 'any', 'dynasty', true),
  ('Tanner Koziol', 'TE', 50, 'any', 'dynasty', true),
  ('Diego Pavia', 'QB', 51, 'any', 'dynasty', true),
  ('Ted Hurst', 'WR', 52, 'any', 'dynasty', true),
  ('Robert Henry Jr.', 'RB', 53, 'any', 'dynasty', true),
  ('Terion Stewart', 'RB', 54, 'any', 'dynasty', true),
  ('Aaron Anderson', 'WR', 55, 'any', 'dynasty', true),
  ('C.J. Daniels', 'WR', 56, 'any', 'dynasty', true),
  ('Brenen Thompson', 'WR', 57, 'any', 'dynasty', true),
  ('Dane Key', 'WR', 58, 'any', 'dynasty', true),
  ('Sawyer Robertson', 'QB', 59, 'any', 'dynasty', true),
  ('Taylen Green', 'QB', 60, 'any', 'dynasty', true),
  ('Oscar Delp', 'TE', 61, 'any', 'dynasty', true),
  ('De''Zhaun Stribling', 'WR', 62, 'any', 'dynasty', true),
  ('Noah Whittington', 'RB', 63, 'any', 'dynasty', true),
  ('Desmond Reid', 'RB', 64, 'any', 'dynasty', true),
  ('Jamal Haynes', 'RB', 65, 'any', 'dynasty', true),
  ('TJ Harden', 'RB', 66, 'any', 'dynasty', true),
  ('Dean Connors', 'RB', 67, 'any', 'dynasty', true),
  ('Rahsul Faison', 'RB', 68, 'any', 'dynasty', true),
  ('Chase Roberts', 'WR', 69, 'any', 'dynasty', true),
  ('Eric Rivers', 'WR', 70, 'any', 'dynasty', true),
  ('Josh Cameron', 'WR', 71, 'any', 'dynasty', true),
  ('Kaelon Black', 'RB', 72, 'any', 'dynasty', true),
  ('Eli Raridon', 'TE', 73, 'any', 'dynasty', true),
  ('RJ Maryland', 'TE', 74, 'any', 'dynasty', true),
  ('J. Michael Sturdivant', 'WR', 75, 'any', 'dynasty', true),
  ('Jalon Daniels', 'QB', 76, 'any', 'dynasty', true),
  ('Reggie Virgil', 'WR', 77, 'any', 'dynasty', true),
  ('Dallen Bentley', 'TE', 78, 'any', 'dynasty', true),
  ('Miller Moss', 'QB', 79, 'any', 'dynasty', true),
  ('Caleb Douglas', 'WR', 80, 'any', 'dynasty', true),
  ('Sam Roush', 'TE', 81, 'any', 'dynasty', true),
  ('Rueben Owens', 'RB', 82, 'any', 'dynasty', true),
  ('Lewis Bond', 'WR', 83, 'any', 'dynasty', true),
  ('Conner Weigman', 'QB', 84, 'any', 'dynasty', true),
  ('Jack Velling', 'TE', 85, 'any', 'dynasty', true),
  ('Chip Trayanum', 'RB', 86, 'any', 'dynasty', true),
  ('Luke Altmyer', 'QB', 87, 'any', 'dynasty', true),
  ('Harrison Wallace III', 'WR', 88, 'any', 'dynasty', true),
  ('Tyren Montgomery', 'WR', 89, 'any', 'dynasty', true),
  ('Marlin Klein', 'TE', 90, 'any', 'dynasty', true),
  ('Cyrus Allen', 'WR', 91, 'any', 'dynasty', true),
  ('Dae''Quan Wright', 'TE', 92, 'any', 'dynasty', true),
  ('Malachi Nelson', 'QB', 93, 'any', 'dynasty', true),
  ('Nyck Harbor', 'WR', 94, 'any', 'dynasty', true),
  ('Trebor Pena', 'WR', 95, 'any', 'dynasty', true),
  ('Josh Cuevas', 'TE', 96, 'any', 'dynasty', true),
  ('Arch Manning', 'QB', 97, 'any', 'dynasty', true),
  ('L.J. Martin', 'RB', 98, 'any', 'dynasty', true),
  ('Noah Thomas', 'WR', 99, 'any', 'dynasty', true),
  ('Eli Heidenreich', 'WR', 100, 'any', 'dynasty', true),
  ('Hank Beatty', 'WR', 101, 'any', 'dynasty', true),
  ('Vinny Anthony II', 'WR', 102, 'any', 'dynasty', true),
  ('Malik Rutherford', 'WR', 103, 'any', 'dynasty', true),
  ('Joey Aguilar', 'QB', 104, 'any', 'dynasty', true),
  ('Lake McRee', 'TE', 105, 'any', 'dynasty', true),
  ('Jake Retzlaff', 'QB', 106, 'any', 'dynasty', true),
  ('CJ Donaldson', 'RB', 107, 'any', 'dynasty', true),
  ('Kentrel Bullock', 'RB', 108, 'any', 'dynasty', true),
  ('John Michael Gyllenborg', 'TE', 109, 'any', 'dynasty', true),
  ('Jeff Caldwell', 'WR', 110, 'any', 'dynasty', true),
  ('Athan Kaliakmanis', 'QB', 111, 'any', 'dynasty', true),
  ('Logan Diggs', 'RB', 112, 'any', 'dynasty', true),
  ('Dillon Bell', 'WR', 113, 'any', 'dynasty', true),
  ('Chris Hilton Jr.', 'WR', 114, 'any', 'dynasty', true),
  ('Malik Benson', 'WR', 115, 'any', 'dynasty', true),
  ('Kendrick Law', 'WR', 116, 'any', 'dynasty', true),
  ('Rohan Jones', 'TE', 117, 'any', 'dynasty', true),
  ('Roydell Williams', 'RB', 118, 'any', 'dynasty', true),
  ('Zavion Thomas', 'WR', 119, 'any', 'dynasty', true),
  ('Lance Mason', 'TE', 120, 'any', 'dynasty', true),
  ('Malachi Coleman', 'WR', 121, 'any', 'dynasty', true),
  ('Mel Brown', 'RB', 122, 'any', 'dynasty', true),
  ('Joe Fagnano', 'QB', 123, 'any', 'dynasty', true),
  ('Behren Morton', 'QB', 124, 'any', 'dynasty', true),
  ('Carsen Ryan', 'TE', 125, 'any', 'dynasty', true)
ON CONFLICT (scoring_format, league_type, is_superflex, name) DO UPDATE SET
  position = EXCLUDED.position,
  rank = EXCLUDED.rank;
