-- Standard / season / superflex baseline rankings
-- Overrides existing baseline for this bucket (scoring_format=standard, league_type=season, is_superflex=true)
-- Inserts into baseline_community_rankings (matches players by name, season=2025)
-- Adds FA rookies to baseline_rookies if not in players or already in baseline_rookies

-- Delete existing baseline for this bucket so we fully replace
DELETE FROM public.baseline_community_rankings
WHERE scoring_format = 'standard' AND league_type = 'season' AND is_superflex = true;

DELETE FROM public.baseline_rookies
WHERE scoring_format = 'standard' AND league_type = 'season' AND is_superflex = true;

WITH parsed (input_name, position, avg_rank, is_fa) AS (
  VALUES
    ('Josh Allen', 'QB', 1.2::numeric, false),
    ('Lamar Jackson', 'QB', 2.8::numeric, false),
    ('Drake Maye', 'QB', 3.2::numeric, false),
    ('Joe Burrow', 'QB', 4.0::numeric, false),
    ('Bijan Robinson', 'RB', 7.0::numeric, false),
    ('Jalen Hurts', 'QB', 7.5::numeric, false),
    ('Jayden Daniels', 'QB', 7.5::numeric, false),
    ('Puka Nacua', 'WR', 10.0::numeric, false),
    ('Jahmyr Gibbs', 'RB', 11.0::numeric, false),
    ('Justin Herbert', 'QB', 11.8::numeric, false),
    ('Ja''Marr Chase', 'WR', 12.7::numeric, false),
    ('Jaxson Dart', 'QB', 13.0::numeric, false),
    ('Jaxon Smith-Njigba', 'WR', 13.0::numeric, false),
    ('Trevor Lawrence', 'QB', 14.7::numeric, false),
    ('Jonathan Taylor', 'RB', 16.5::numeric, false),
    ('Christian McCaffrey', 'RB', 18.3::numeric, false),
    ('CeeDee Lamb', 'WR', 19.2::numeric, false),
    ('Amon-Ra St. Brown', 'WR', 19.2::numeric, false),
    ('Patrick Mahomes II', 'QB', 19.3::numeric, false),
    ('Dak Prescott', 'QB', 19.5::numeric, false),
    ('Caleb Williams', 'QB', 19.8::numeric, false),
    ('Malik Nabers', 'WR', 20.2::numeric, false),
    ('Brock Purdy', 'QB', 20.8::numeric, false),
    ('James Cook III', 'RB', 21.8::numeric, false),
    ('De''Von Achane', 'RB', 22.5::numeric, false),
    ('Drake London', 'WR', 23.0::numeric, false),
    ('Nico Collins', 'WR', 26.7::numeric, false),
    ('Ashton Jeanty', 'RB', 30.3::numeric, false),
    ('George Pickens', 'WR', 31.5::numeric, false),
    ('Bo Nix', 'QB', 31.8::numeric, false),
    ('Matthew Stafford', 'QB', 32.8::numeric, false),
    ('Rashee Rice', 'WR', 33.3::numeric, false),
    ('Brock Bowers', 'TE', 35.0::numeric, false),
    ('Justin Jefferson', 'WR', 35.8::numeric, false),
    ('Derrick Henry', 'RB', 35.8::numeric, false),
    ('Saquon Barkley', 'RB', 37.0::numeric, false),
    ('Omarion Hampton', 'RB', 37.2::numeric, false),
    ('Jared Goff', 'QB', 38.5::numeric, false),
    ('Jordan Love', 'QB', 39.0::numeric, false),
    ('Chris Olave', 'WR', 41.0::numeric, false),
    ('Tee Higgins', 'WR', 42.5::numeric, false),
    ('Josh Jacobs', 'RB', 42.8::numeric, false),
    ('Chase Brown', 'RB', 44.2::numeric, false),
    ('Baker Mayfield', 'QB', 44.5::numeric, false),
    ('Tetairoa McMillan', 'WR', 45.0::numeric, false),
    ('Trey McBride', 'TE', 46.3::numeric, false),
    ('Tucker Kraft', 'TE', 47.0::numeric, false),
    ('A.J. Brown', 'WR', 47.2::numeric, false),
    ('Breece Hall', 'RB', 48.7::numeric, false),
    ('Davante Adams', 'WR', 50.0::numeric, false),
    ('Bucky Irving', 'RB', 54.3::numeric, false),
    ('Garrett Wilson', 'WR', 54.8::numeric, false),
    ('Kenneth Walker III', 'RB', 55.5::numeric, false),
    ('Kyren Williams', 'RB', 55.7::numeric, false),
    ('Malik Willis', 'QB', 56.2::numeric, false),
    ('Tyler Shough', 'QB', 57.2::numeric, false),
    ('Jameson Williams', 'WR', 57.3::numeric, false),
    ('Colston Loveland', 'TE', 57.8::numeric, false),
    ('Sam Darnold', 'QB', 64.0::numeric, false),
    ('Jaylen Waddle', 'WR', 64.5::numeric, false),
    ('Zay Flowers', 'WR', 64.7::numeric, false),
    ('Ladd McConkey', 'WR', 64.8::numeric, false),
    ('Kyler Murray', 'QB', 66.2::numeric, false),
    ('TreVeyon Henderson', 'RB', 66.2::numeric, false),
    ('Cam Ward', 'QB', 67.0::numeric, false),
    ('Christian Watson', 'WR', 67.3::numeric, false),
    ('Travis Etienne Jr.', 'RB', 67.3::numeric, false),
    ('Terry McLaurin', 'WR', 67.3::numeric, false),
    ('Javonte Williams', 'RB', 67.7::numeric, false),
    ('Cam Skattebo', 'RB', 69.2::numeric, false),
    ('RJ Harvey', 'RB', 69.7::numeric, false),
    ('C.J. Stroud', 'QB', 70.5::numeric, false),
    ('Mike Evans', 'WR', 74.7::numeric, false),
    ('Luther Burden III', 'WR', 75.5::numeric, false),
    ('Emeka Egbuka', 'WR', 76.7::numeric, false),
    ('Quinshon Judkins', 'RB', 76.8::numeric, false),
    ('D''Andre Swift', 'RB', 77.3::numeric, false),
    ('Courtland Sutton', 'WR', 77.8::numeric, false),
    ('DeVonta Smith', 'WR', 78.5::numeric, false),
    ('Rome Odunze', 'WR', 79.7::numeric, false),
    ('Jaylen Warren', 'RB', 83.8::numeric, false),
    ('DK Metcalf', 'WR', 87.0::numeric, false),
    ('Harold Fannin Jr.', 'TE', 88.0::numeric, false),
    ('Blake Corum', 'RB', 89.0::numeric, false),
    ('Bryce Young', 'QB', 90.0::numeric, false),
    ('Kyle Monangai', 'RB', 90.7::numeric, false),
    ('Tyler Warren', 'TE', 91.0::numeric, false),
    ('Denzel Boston', 'WR', 91.8::numeric, true),
    ('Brian Thomas Jr.', 'WR', 94.5::numeric, false),
    ('Rhamondre Stevenson', 'RB', 94.7::numeric, false),
    ('Bhayshul Tuten', 'RB', 95.5::numeric, false),
    ('Michael Penix Jr.', 'QB', 98.7::numeric, false),
    ('Rico Dowdle', 'RB', 98.8::numeric, false),
    ('Marvin Harrison Jr.', 'WR', 99.3::numeric, false),
    ('Tony Pollard', 'RB', 99.5::numeric, false),
    ('Alec Pierce', 'WR', 101.7::numeric, false),
    ('Sam LaPorta', 'TE', 102.2::numeric, false),
    ('Daniel Jones', 'QB', 102.3::numeric, false),
    ('Michael Wilson', 'WR', 103.0::numeric, false),
    ('Zach Charbonnet', 'RB', 104.3::numeric, false),
    ('Jacory Croskey-Merritt', 'RB', 104.3::numeric, false),
    ('Carnell Tate', 'WR', 105.5::numeric, true),
    ('Jordan Addison', 'WR', 105.7::numeric, false),
    ('Kyle Pitts Sr.', 'TE', 107.7::numeric, false),
    ('Woody Marks', 'RB', 108.2::numeric, false),
    ('Brandon Aiyuk', 'WR', 108.8::numeric, false),
    ('Dalton Kincaid', 'TE', 108.8::numeric, false),
    ('Jordyn Tyson', 'WR', 109.5::numeric, true),
    ('Ricky Pearsall', 'WR', 110.7::numeric, false),
    ('Quentin Johnston', 'WR', 112.0::numeric, false),
    ('Chris Godwin Jr.', 'WR', 112.2::numeric, false),
    ('Jakobi Meyers', 'WR', 112.5::numeric, false),
    ('Oronde Gadsden II', 'TE', 114.3::numeric, false),
    ('K.C. Concepcion', 'WR', 114.5::numeric, true),
    ('Chuba Hubbard', 'RB', 114.8::numeric, false),
    ('David Montgomery', 'RB', 115.7::numeric, false),
    ('Stefon Diggs', 'WR', 116.0::numeric, false),
    ('James Conner', 'RB', 117.5::numeric, false),
    ('Makai Lemon', 'WR', 118.8::numeric, true),
    ('Aaron Jones Sr.', 'RB', 119.2::numeric, false),
    ('Michael Pittman Jr.', 'WR', 120.8::numeric, false),
    ('J.J. McCarthy', 'QB', 89.4::numeric, false),
    ('Tyler Allgeier', 'RB', 122.0::numeric, false),
    ('Jauan Jennings', 'WR', 122.2::numeric, false),
    ('Braelon Allen', 'RB', 122.8::numeric, false),
    ('Brenton Strange', 'TE', 124.2::numeric, false),
    ('Parker Washington', 'WR', 125.0::numeric, false),
    ('Jeremiyah Love', 'RB', 125.3::numeric, true),
    ('DJ Moore', 'WR', 126.3::numeric, false),
    ('Jake Ferguson', 'TE', 128.7::numeric, false),
    ('Juwan Johnson', 'TE', 131.7::numeric, false),
    ('Jayden Higgins', 'WR', 133.5::numeric, false),
    ('J.K. Dobbins', 'RB', 133.7::numeric, false),
    ('Shedeur Sanders', 'QB', 106.2::numeric, false),
    ('Dallas Goedert', 'TE', 135.5::numeric, false),
    ('Wan''Dale Robinson', 'WR', 135.7::numeric, false),
    ('George Kittle', 'TE', 136.7::numeric, false),
    ('Jordan Mason', 'RB', 137.0::numeric, false),
    ('Alvin Kamara', 'RB', 138.5::numeric, false),
    ('Tyrone Tracy Jr.', 'RB', 139.7::numeric, false),
    ('Tyreek Hill', 'WR', 141.2::numeric, true),
    ('Trey Benson', 'RB', 141.8::numeric, false),
    ('Khalil Shakir', 'WR', 142.0::numeric, false),
    ('Hunter Henry', 'TE', 142.2::numeric, false),
    ('Kaleb Johnson', 'RB', 144.3::numeric, false),
    ('Xavier Worthy', 'WR', 146.0::numeric, false),
    ('Deebo Samuel Sr.', 'WR', 147.0::numeric, false),
    ('Jayden Reed', 'WR', 148.5::numeric, false),
    ('Travis Hunter', 'WR', 148.7::numeric, false),
    ('Tank Bigsby', 'RB', 150.5::numeric, false),
    ('Dylan Sampson', 'RB', 152.0::numeric, false),
    ('Kenneth Gainwell', 'RB', 152.3::numeric, false),
    ('Josh Downs', 'WR', 152.7::numeric, false),
    ('Jalen Coker', 'WR', 154.0::numeric, false),
    ('Troy Franklin', 'WR', 156.7::numeric, false),
    ('Mark Andrews', 'TE', 159.7::numeric, false),
    ('Jacoby Brissett', 'QB', 136.0::numeric, false),
    ('Kimani Vidal', 'RB', 160.8::numeric, false),
    ('Joe Mixon', 'RB', 161.8::numeric, false),
    ('Adonai Mitchell', 'WR', 161.8::numeric, false),
    ('Tyjae Spears', 'RB', 162.8::numeric, false),
    ('Dalton Schultz', 'TE', 163.7::numeric, false),
    ('Rachaad White', 'RB', 164.3::numeric, false),
    ('Isiah Pacheco', 'RB', 165.7::numeric, false),
    ('Tua Tagovailoa', 'QB', 142.6::numeric, false),
    ('Keaton Mitchell', 'RB', 165.8::numeric, false),
    ('Brian Robinson Jr.', 'RB', 167.3::numeric, false),
    ('Mac Jones', 'QB', 145.0::numeric, false),
    ('Kayshon Boutte', 'WR', 167.8::numeric, false),
    ('Travis Kelce', 'TE', 168.0::numeric, false),
    ('Jonathon Brooks', 'RB', 169.8::numeric, false),
    ('Jerry Jeudy', 'WR', 170.8::numeric, false),
    ('Romeo Doubs', 'WR', 172.0::numeric, false),
    ('Terrance Ferguson', 'TE', 172.7::numeric, false),
    ('Tank Dell', 'WR', 173.3::numeric, false),
    ('Kendre Miller', 'RB', 174.0::numeric, false),
    ('Jaylen Wright', 'RB', 174.0::numeric, false),
    ('Chimere Dike', 'WR', 174.3::numeric, false),
    ('Rashid Shaheed', 'WR', 174.5::numeric, false),
    ('Sean Tucker', 'RB', 175.5::numeric, false),
    ('Chris Rodriguez Jr.', 'RB', 178.8::numeric, false),
    ('Devin Neal', 'RB', 179.7::numeric, false),
    ('Isaiah Likely', 'TE', 180.5::numeric, false),
    ('Theo Johnson', 'TE', 181.2::numeric, false),
    ('Elic Ayomanor', 'WR', 181.2::numeric, false),
    ('Isaac TeSlaa', 'WR', 182.5::numeric, false),
    ('Jaylin Noel', 'WR', 185.5::numeric, false),
    ('Matthew Golden', 'WR', 187.0::numeric, false),
    ('Jadarian Price', 'RB', 94.0::numeric, true),
    ('Fernando Mendoza', 'QB', 96.0::numeric, true),
    ('Kyle Williams', 'WR', 189.2::numeric, false),
    ('Emanuel Wilson', 'RB', 190.0::numeric, false),
    ('AJ Barner', 'TE', 191.3::numeric, false),
    ('Tre Harris', 'WR', 191.8::numeric, false),
    ('Tre Tucker', 'WR', 194.3::numeric, false),
    ('Emmett Johnson', 'RB', 109.7::numeric, true),
    ('Tory Horton', 'WR', 196.5::numeric, false),
    ('Ryan Flournoy', 'WR', 197.5::numeric, false),
    ('Ray Davis', 'RB', 197.7::numeric, false),
    ('Geno Smith', 'QB', 182.6::numeric, false),
    ('Pat Bryant', 'WR', 199.2::numeric, false),
    ('Jonah Coleman', 'RB', 119.7::numeric, true),
    ('Isaiah Davis', 'RB', 201.8::numeric, false),
    ('Darnell Mooney', 'WR', 203.2::numeric, false),
    ('T.J. Hockenson', 'TE', 203.7::numeric, false),
    ('Rashod Bateman', 'WR', 204.8::numeric, false),
    ('Keon Coleman', 'WR', 205.2::numeric, false),
    ('Jalen McMillan', 'WR', 206.0::numeric, false),
    ('Calvin Ridley', 'WR', 206.5::numeric, false),
    ('Ollie Gordon II', 'RB', 207.0::numeric, false),
    ('Mack Hollins', 'WR', 210.3::numeric, false),
    ('Najee Harris', 'RB', 210.7::numeric, false),
    ('Jaleel McLaughlin', 'RB', 211.3::numeric, false),
    ('David Njoku', 'TE', 211.5::numeric, false),
    ('Marvin Mims Jr.', 'WR', 211.5::numeric, false),
    ('Anthony Richardson Sr.', 'QB', 178.3::numeric, false),
    ('Xavier Legette', 'WR', 213.2::numeric, false),
    ('Colby Parkinson', 'TE', 214.7::numeric, false),
    ('Mason Taylor', 'TE', 214.8::numeric, false),
    ('Dontayvion Wicks', 'WR', 215.3::numeric, false),
    ('Kenyon Sadiq', 'TE', 149.3::numeric, true),
    ('Isaac Guerendo', 'RB', 205.8::numeric, false),
    ('Gunnar Helm', 'TE', 222.2::numeric, false),
    ('Darius Slayton', 'WR', 222.2::numeric, false),
    ('Ty Johnson', 'RB', 222.5::numeric, false),
    ('Aaron Rodgers', 'QB', 106.5::numeric, false),
    ('Chig Okonkwo', 'TE', 226.2::numeric, false),
    ('Pat Freiermuth', 'TE', 226.5::numeric, false),
    ('Isaiah Bond', 'WR', 227.0::numeric, false),
    ('Cooper Kupp', 'WR', 227.0::numeric, false),
    ('Brashard Smith', 'RB', 227.5::numeric, false),
    ('Keenan Allen', 'WR', 227.7::numeric, false),
    ('DJ Giddens', 'RB', 229.0::numeric, false),
    ('Joe Milton III', 'QB', 183.0::numeric, false),
    ('Omar Cooper Jr.', 'WR', 134.0::numeric, true),
    ('Malik Davis', 'RB', 224.2::numeric, false),
    ('Jaydon Blue', 'RB', 234.3::numeric, false),
    ('Eli Stowers', 'TE', 188.7::numeric, true),
    ('Malachi Fields', 'WR', 151.5::numeric, true),
    ('Jake Tonges', 'TE', 230.2::numeric, false),
    ('Chris Brazzell II', 'WR', 155.0::numeric, true),
    ('Konata Mumpfield', 'WR', 240.2::numeric, false),
    ('Kaytron Allen', 'RB', 158.0::numeric, true),
    ('Mike Washington Jr.', 'RB', 158.0::numeric, true),
    ('Luke McCaffrey', 'WR', 241.7::numeric, false),
    ('Andrei Iosivas', 'WR', 234.4::numeric, false),
    ('George Holani', 'RB', 243.2::numeric, false),
    ('Devaughn Vele', 'WR', 243.0::numeric, false),
    ('Cade Otton', 'TE', 243.0::numeric, false),
    ('Evan Engram', 'TE', 243.3::numeric, false),
    ('Bam Knight', 'RB', 236.4::numeric, false),
    ('Jarquez Hunter', 'RB', 236.8::numeric, false),
    ('Audric Estime', 'RB', 237.4::numeric, false),
    ('Jack Bech', 'WR', 246.2::numeric, false),
    ('MarShawn Lloyd', 'RB', 239.2::numeric, false),
    ('Elijah Sarratt', 'WR', 180.0::numeric, true),
    ('Tyquan Thornton', 'WR', 241.2::numeric, false),
    ('Marquise Brown', 'WR', 249.2::numeric, false),
    ('Nicholas Singleton', 'RB', 184.5::numeric, true),
    ('Germie Bernard', 'WR', 186.0::numeric, true),
    ('Calvin Austin III', 'WR', 243.8::numeric, false),
    ('Tommy Myers', 'TE', 218.7::numeric, true),
    ('Zachariah Branch', 'WR', 188.0::numeric, true),
    ('Ben Sinnott', 'TE', 241.5::numeric, false),
    ('Devin Singletary', 'RB', 246.0::numeric, false),
    ('Christian Kirk', 'WR', 247.4::numeric, false),
    ('Mike Gesicki', 'TE', 249.2::numeric, false),
    ('Cedric Tillman', 'WR', 254.8::numeric, false),
    ('Noah Gray', 'TE', 251.6::numeric, false),
    ('Elijah Arroyo', 'TE', 244.5::numeric, false),
    ('Tez Johnson', 'WR', 260.3::numeric, false),
    ('Antonio Williams', 'WR', 209.5::numeric, true),
    ('Trevor Etienne', 'RB', 254.0::numeric, false),
    ('Jerome Ford', 'RB', 254.8::numeric, false),
    ('Darren Waller', 'TE', 238.3::numeric, false),
    ('Dont''e Thornton Jr.', 'WR', 256.2::numeric, false),
    ('Malik Washington', 'WR', 263.2::numeric, false),
    ('Jordan James', 'RB', 267.2::numeric, false),
    ('Jaylin Lane', 'WR', 265.3::numeric, false),
    ('Chris Bell', 'WR', 250.0::numeric, true),
    ('Demond Claiborne', 'RB', 223.5::numeric, true),
    ('Tyler Higbee', 'TE', 257.3::numeric, false),
    ('Kareem Hunt', 'RB', 266.6::numeric, false),
    ('Darnell Washington', 'TE', 253.3::numeric, false),
    ('Emari Demercado', 'RB', 263.4::numeric, false),
    ('Justice Hill', 'RB', 261.4::numeric, false),
    ('LeQuint Allen Jr.', 'RB', 263.2::numeric, false),
    ('Samaje Perine', 'RB', 269.2::numeric, false),
    ('John Bates', 'TE', 266.3::numeric, false),
    ('Tahj Brooks', 'RB', 270.5::numeric, false),
    ('Xavier Hutchinson', 'WR', 275.0::numeric, false),
    ('Joshua Palmer', 'WR', 274.8::numeric, false),
    ('Michael Mayer', 'TE', 256.3::numeric, false),
    ('Jalen Nailor', 'WR', 277.0::numeric, false),
    ('Jalen Royals', 'WR', 270.0::numeric, false),
    ('Olamide Zaccheaus', 'WR', 274.0::numeric, false),
    ('John Metchie III', 'WR', 273.2::numeric, false),
    ('Nick Chubb', 'RB', 275.4::numeric, false),
    ('DeMario Douglas', 'WR', 278.8::numeric, false),
    ('Greg Dulcich', 'TE', 258.0::numeric, false),
    ('Adam Randall', 'RB', 223.0::numeric, true),
    ('Ja''Kobi Lane', 'WR', 231.0::numeric, true),
    ('Reggie Virgil', 'WR', 233.0::numeric, true),
    ('Ted Hurst', 'WR', 234.0::numeric, true),
    ('Le''Veon Moss', 'RB', 235.0::numeric, true),
    ('Chris Brooks', 'RB', 273.2::numeric, false),
    ('Jam Miller', 'RB', 246.0::numeric, true),
    ('Michael Carter', 'RB', 277.8::numeric, false),
    ('Jared Wiley', 'TE', 249.0::numeric, false),
    ('J''Mari Taylor', 'RB', 256.0::numeric, true),
    ('Terrell Jennings', 'RB', 290.5::numeric, false),
    ('Dameon Pierce', 'RB', 290.5::numeric, false),
    ('Jawhar Jordan', 'RB', 278.6::numeric, false),
    ('Austin Ekeler', 'RB', 285.6::numeric, false),
    ('Antonio Gibson', 'RB', 292.8::numeric, false),
    ('Raheim Sanders', 'RB', 287.8::numeric, false),
    ('Will Shipley', 'RB', 286.0::numeric, false),
    ('Deion Burks', 'WR', 279.0::numeric, true),
    ('Caleb Douglas', 'WR', 282.0::numeric, true),
    ('Ja''Tavion Sanders', 'TE', 283.0::numeric, false),
    ('Tyren Montgomery', 'WR', 285.0::numeric, true),
    ('Cole Kmet', 'TE', 286.0::numeric, false),
    ('Seth McGowan', 'RB', 288.0::numeric, true),
    ('Skyler Bell', 'WR', 289.0::numeric, true),
    ('Jaydn Ott', 'RB', 290.0::numeric, true),
    ('Kaelon Black', 'RB', 291.0::numeric, true),
    ('Kevin Coleman Jr.', 'WR', 292.0::numeric, true),
    ('Barion Brown', 'WR', 294.0::numeric, true),
    ('Luke Musgrave', 'TE', 300.0::numeric, false),
    ('Bryce Lance', 'WR', 307.0::numeric, true),
    ('Josh Cameron', 'WR', 308.0::numeric, true),
    ('Max Klare', 'TE', 310.0::numeric, true),
    ('Dawson Knox', 'TE', 312.0::numeric, false),
    ('Elijah Higgins', 'TE', 313.0::numeric, false),
    ('Jonnu Smith', 'TE', 316.0::numeric, false),
    ('Vinny Anthony II', 'WR', 317.0::numeric, true),
    ('Roman Hemby', 'RB', 321.0::numeric, true),
    ('Michael Trigg', 'TE', 322.0::numeric, true),
    ('Brenen Thompson', 'WR', 323.0::numeric, true),
    ('Robert Henry Jr.', 'RB', 324.0::numeric, true),
    ('Justin Joly', 'TE', 326.0::numeric, true),
    ('Jack Endries', 'TE', 329.0::numeric, true),
    ('Tanner Koziol', 'TE', 331.0::numeric, true),
    ('Aaron Anderson', 'WR', 332.0::numeric, true),
    ('C.J. Daniels', 'WR', 333.0::numeric, true),
    ('Dane Key', 'WR', 334.0::numeric, true),
    ('Desmond Reid', 'RB', 335.0::numeric, true),
    ('Zach Ertz', 'TE', 336.0::numeric, false),
    ('Chris Hilton Jr.', 'WR', 338.0::numeric, true),
    ('Thomas Fidone II', 'TE', 342.0::numeric, false),
    ('Taysom Hill', 'TE', 343.0::numeric, false),
    ('Jamal Haynes', 'RB', 345.0::numeric, true),
    ('Erick All Jr.', 'TE', 346.0::numeric, false)
),
aliases (input_name, db_name) AS (
  VALUES
    ('Patrick Mahomes II', 'Patrick Mahomes'),
    ('Deebo Samuel Sr.', 'Deebo Samuel'),
    ('Aaron Jones Sr.', 'Aaron Jones'),
    ('Anthony Richardson Sr.', 'Anthony Richardson'),
    ('Chris Godwin Jr.', 'Chris Godwin'),
    ('Brian Thomas Jr.', 'Brian Thomas'),
    ('Kyle Pitts Sr.', 'Kyle Pitts'),
    ('Michael Pittman Jr.', 'Michael Pittman'),
    ('Marvin Harrison Jr.', 'Marvin Harrison'),
    ('Ollie Gordon II', 'Ollie Gordon'),
    ('Chris Rodriguez Jr.', 'Chris Rodriguez'),
    ('Jonathon Brooks', 'Jonathan Brooks'),
    ('Travis Etienne Jr.', 'Travis Etienne'),
    ('Michael Penix Jr.', 'Michael Penix'),
    ('Thomas Fidone II', 'Thomas Fidone'),
    ('Erick All Jr.', 'Erick All')
),
lookup AS (
  SELECT
    p.input_name,
    p.position,
    p.avg_rank,
    p.is_fa,
    COALESCE(a.db_name, p.input_name) AS match_name
  FROM parsed p
  LEFT JOIN aliases a ON a.input_name = p.input_name
),
lookup_dedup AS (
  SELECT DISTINCT ON (match_name) input_name, position, avg_rank, is_fa, match_name
  FROM lookup
  ORDER BY match_name, avg_rank ASC
),

ins_baseline AS (
  INSERT INTO public.baseline_community_rankings (scoring_format, league_type, is_superflex, player_id, rank)
  SELECT
    'standard'::text,
    'season'::text,
    true,
    pl.id,
    l.avg_rank
  FROM lookup_dedup l
  INNER JOIN public.players pl ON pl.name = l.match_name AND pl.season = 2025
  ON CONFLICT (scoring_format, league_type, is_superflex, player_id)
  DO UPDATE SET rank = EXCLUDED.rank
)

INSERT INTO public.baseline_rookies (name, position, rank, scoring_format, league_type, is_superflex)
SELECT l.input_name, l.position, l.avg_rank, 'standard'::text, 'season'::text, true
FROM lookup_dedup l
WHERE l.is_fa = true
  AND NOT EXISTS (
    SELECT 1 FROM public.players p
    WHERE (p.name = l.match_name OR p.name = l.input_name) AND p.season = 2025
  )
  AND NOT EXISTS (
    SELECT 1 FROM public.baseline_rookies br
    WHERE br.name = l.input_name
      AND br.scoring_format = 'standard'
      AND br.league_type = 'season'
      AND br.is_superflex = true
  )
ON CONFLICT (scoring_format, league_type, is_superflex, name) DO NOTHING;
